### ISSUE TITLE
Opens in Notepad

### ISSUE THREAD

**Issue by troffaholic** [OgarProject/Ogar#122]
Okay, so I downloaded it on my Mac and all files seemed to work fine but I can't manage to open Launch.bat in Terminal. It tries to open in notepad ( which was installed in a virtual machine on this mac, running Windows. ) and I tried "Open With" and selected "Other" and searched for Terminal but it didn't find anything.

**Comment by Gjum** [comment]
`.bat` files are scripts for the Windows console.

**Comment by abalabahaha** [comment]
On Mac, cd into the Ogar/src directory and do
```
node index.js
```

**Comment by z3ntu** [comment]
Please close this issue if it was solved by @abalabahaha 's answer!
