### ISSUE TITLE
How to use the stats port?

### ISSUE THREAD

**Issue by Charlo74** [OgarProject/Ogar#130]
Hi, how to view stats with stats port? ty

**Comment by vram4** [comment]
Go to "[IP of your server]:[Stats port]" in your browser. For example if my server was hosted at 127.0.0.1 (locally) and my stats port is 88, i would type 127.0.0.1:88 in my browsers address bar.

**Comment by helma27** [comment]
How to display it on html?

**Comment by helma27** [comment]
@vram4 please help me

**Comment by vram4** [comment]
The address to access the stats is `[IP of your server]:[Stats Port]`. So if your ip is 127.0.0.1 and stats port is 88, you would type in `127.0.0.1:88` into your browser's address bar.

**Comment by helma27** [comment]
i mean, i'am using iframe to make private server, and, how to display it correctly on my page?
ex: in bottom right corner, Current Player: (12/68 ) 
Thank you

**Comment by vram4** [comment]
Unfortunately, we cannot offer support for modded/custom clients.
