### ISSUE TITLE
Uncaught Error's !

### ISSUE THREAD

**Issue by Jaden-Gabriel** [OgarProject/Ogar#133]
Greetings!
I've just made an agar.io private server and I got this as an error.
![image](https://cloud.githubusercontent.com/assets/13412091/8770302/8075a360-2ee1-11e5-9d79-15ecf07aabad.png)
I got the "Launch" opened and running perfectly. Help !

Thanks in advance,
Jaden

**Comment by Ephemerality** [comment]
Pretty much the same issue as #119 #124 #118 #112 #111, the server and client are not both up to date. Make sure you have the latest version from http://dl.ogarproject.com, that you're using the official client at agar.io, no mods/extensions/etc are enabled, and if all of that is true try a different browser.

**Comment by Jaden-Gabriel** [comment]
Thanks, it works. Now, how do I let other's connect through Hamachi?

**Comment by Jaden-Gabriel** [comment]
I asked my friend to try Connect ("ws://25.37.122.125:443") in Console and he said " Connect is not defined". Any ideas?

**Comment by Jaden-Gabriel** [comment]
25.37.122.125 is my Hamachi IP.

**Comment by vram4** [comment]
@Jaden-Gabriel "Connect" needs to be lowercase. The proper syntax is: connect("ws://25.37.122.125:443","")

**Comment by Jaden-Gabriel** [comment]
Aight, mind helping me trying out the server?

**Comment by Youtubrer** [comment]
@Jaden-Gabriel Oooh! Can i come?

**Comment by Jaden-Gabriel** [comment]
Sure, you got Hamachi?

**Comment by Youtubrer** [comment]
ya

**Comment by Youtubrer** [comment]
This is the ip for it
25.43.79.75
(not the agar.io server)

**Comment by Youtubrer** [comment]
uhhh....
hello?

**Comment by Jaden-Gabriel** [comment]
Sorry! Here you go,
Agario-Jaden
123

See you there! :)

**Comment by Jaden-Gabriel** [comment]
@vram4 ,
@Youtubrer got this error,
WebSocket connection to 'ws://25.37.122.125:443/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

What can I do to fix this?

**Comment by vram4** [comment]
@Jaden-Gabriel Are you playing the client on the same computer that is hosting the server? If so, try ```connect("ws://127.0.0.1:443","")```

**Comment by Youtubrer** [comment]
@vram4 
He is "Hosting" From a hamichi client, and i am at the other end, not able to connect.

**Comment by vram4** [comment]
@Youtubrer Oh my bad, hmm, check what color the status dot of the host is. If its red, then theres a connection problem with hamachi.

**Comment by Youtubrer** [comment]
The light is green, but at first it was relayed.
The message it gave me when i diagnosed him in hamachi is this:
Summary report
------------------------

Test name: Peer		Result: [YELLOW] -> Problems found
Details: 

Tunnel: OK

Local results:
	Adapter configuration: OK
	Traffic test: Inbound traffic blocked, check firewall settings
Peer results: [Redacted]
	Adapter configuration: OK
	Traffic test: This peer is not eligible for remote testing

---------------------------------------------

**Comment by Jaden-Gabriel** [comment]
I tried accessing @Youtubrer 's server using Console and this error pops-up : 
Uncaught DOMException: Failed to construct 'WebSocket': The URL '67.42.109.29:443' is invalid.
    at Error (native)
    at Ha (http://agar.io/:403:267)
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)

**Comment by vram4** [comment]
@Youtubrer @Jaden-Gabriel He needs port forwarding if hes going to use his public ip address. Anyways, i havent used hamachi in a long time so i wouldnt know what the exact problem is, but it seems to be something along the lines of a hamachi connection problem (maybe check that both connections are green?)

**Comment by Jaden-Gabriel** [comment]
I am currently using Hamachi IP and it gave that error I mentioned above when someone tries to connect to my server,

**Comment by Ephemerality** [comment]
`Failed to construct 'WebSocket': The URL 'IP' is invalid.` happens when you don't put `ws://` in front of the IP address.

**Comment by Youtubrer** [comment]
Yea, we caught that a second after we posted it, but even when ws:// is put, it still wont work.

**Comment by Vravinite** [comment]
There may be a problem on the metric of your hamachi, there are some things that u have to change on configuration in order to connect to other people using it.

**Comment by Vravinite** [comment]
Maybe u can check it with me, i had this problems when hosting on many games and i made out how to fix it.

**Comment by mafiakb** [comment]
@Jaden-Gabriel i help u send me u skype

**Comment by Youtubrer** [comment]
@mafiakb I already checked, he doesnt have skype
