### ISSUE TITLE
The console says the offset is outise the bounds....

### ISSUE THREAD

**Issue by kenzen99** [OgarProject/Ogar#147]
I made an ogar server and when i try to connect to it i only get this error... Uncaught RangeError: Offset is outside the bounds of the DataView.

**Comment by Youtubrer** [comment]
whats the config file? can you copy it into here?

**Comment by kenzen99** [comment]
Do you mean gameserver.ini?

**Comment by Youtubrer** [comment]
Ya, sorry.

**Comment by kenzen99** [comment]
// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// leaderboardUpdateClient: How often leaderboard data is sent to the client (1 tick = 50 milliseconds)
serverMaxConnections = 64
serverPort = 443
serverGamemode = 0
serverBots = 5
serverViewBaseX = 1024
serverViewBaseY = 592

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 11180.3398875
borderTop = 0
borderBottom = 11180.3398875

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 10000
foodMass = 1
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusFeedAmount = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur 
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15

// [Gamemode]
// Custom gamemode settings
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by Youtubrer** [comment]
Is this your first time loading it?

**Comment by Youtubrer** [comment]
If so, i think you can do the reload command, or restarting it. Otherwise, you would have to get someone else to help.

**Comment by vram4** [comment]
An ```Uncaught RangeError: Offset is outside the bounds of the DataView.``` means that either the client or server is not updated, most likely the server. If you have windows, the latest version of the server can be found at http://dl.ogarproject.com . Also make sure you are using the agario client from http://agar.io

**Comment by kenzen99** [comment]
I just now downloaded the server so thats not a possibility

**Comment by vram4** [comment]
Can you post a screen shot of you client (with the error)?

**Comment by kenzen99** [comment]
http://gyazo.com/d5f36ab5cd26902e666b5d9e7aeaff83

**Comment by vram4** [comment]
What is the file name of the server file you downloaded? It should be "Ogar-windows-68f746c".

**Comment by kenzen99** [comment]
its called ogar-master

**Comment by vram4** [comment]
You have the wrong server version, here is a direct link to the latest version: http://dl.ogarproject.com/binaries/68f746c0e0af5315988a1496ce71e9c3bf327e3c/Ogar-windows-68f746c.exe
