### ISSUE TITLE
My friend try's to join

### ISSUE THREAD

**Issue by thesidemen133** [OgarProject/Ogar#148]
When my friend tries to join my private server, it says connection refused. Can you please help me

**Comment by z3ntu** [comment]
Is the port you are using forwarded?

**Comment by thesidemen133** [comment]
no

**Comment by thesidemen133** [comment]
i decieded not to because i do not want to mess with my router

**Comment by z3ntu** [comment]
you have to... otherwise your router denies incoming connections on the server's port...

**Comment by thesidemen133** [comment]
oh

**Comment by thesidemen133** [comment]
ok ill try it

**Comment by vram4** [comment]
@thesidemen133 Also make sure youre giving your public ip for your friend to join, not your local one.

**Comment by thesidemen133** [comment]
ok how do i find it

**Comment by thesidemen133** [comment]
and if im portforwarding, my router is not on there

**Comment by z3ntu** [comment]
How to find out your public IP: https://www.whatismyip.com/

**Comment by thesidemen133** [comment]
ok

**Comment by z3ntu** [comment]
And what do you mean with "my router is not on there"?!

**Comment by thesidemen133** [comment]
but my kind of router is not listed on portforwarding

**Comment by z3ntu** [comment]
Do you know the IP address of your router?

**Comment by thesidemen133** [comment]
let me check

**Comment by z3ntu** [comment]
And do you use Windows, Linux or Mac?

**Comment by thesidemen133** [comment]
im using wondows

**Comment by thesidemen133** [comment]
i cant find my  routers ip

**Comment by thesidemen133** [comment]
oh nevermind i tried to login and it said the ip was updated to 10.0.0.1

**Comment by z3ntu** [comment]
Does it work now?

**Comment by thesidemen133** [comment]
im getting my static ip

**Comment by z3ntu** [comment]
Okay, please reply if you have any further question!

**Comment by thesidemen133** [comment]
ok

**Comment by thesidemen133** [comment]
i will be on for a couple more hours anyways

**Comment by thesidemen133** [comment]
hey im portforwarding what service type do i use?

**Comment by thesidemen133** [comment]
ok i think ive done it, going to test...

**Comment by z3ntu** [comment]
TCP

**Comment by thesidemen133** [comment]
ok it says thatthe connection timed out

**Comment by z3ntu** [comment]
How do you locally connect to your server?

**Comment by thesidemen133** [comment]
OMG I DOD IT

**Comment by thesidemen133** [comment]
you wanna join reall quick

**Comment by z3ntu** [comment]
nty
and please close this issue!
