### ISSUE TITLE
my  agar.io glitches when i join the server

### ISSUE THREAD

**Issue by kelanf** [OgarProject/Ogar#150]
my  agar.io glitches when i join the server

what it looks like: http://gyazo.com/c3ba57162fae5670198c3180858abfaf

please help

**Comment by Ephemerality** [comment]
I see an Ogar-master.zip in your downloads there. Are you running the game from an exe file or are you running it with the `node Ogar` (or similar) command in Command Prompt?  
If you are running it from an exe, you need the latest one from http://dl.ogarproject.com.  
If you are running it with Node, post your config file.

**Comment by kelanf** [comment]
i was running from exe, i am downloading the new one at the moment, sorry for the late reply

**Comment by kelanf** [comment]
it worked! thanks for your help :)
