### ISSUE TITLE
Cannot find module when making custom GameModes.

### ISSUE THREAD

**Issue by firestar115** [OgarProject/Ogar#152]
I am making gamemodes like NoDecay and AntiDecay and I am not good with Node. How do I do this?

Git Repo: https://github.com/firestar115/Ogar

**Comment by vram4** [comment]
You could just set "playerMassDecayRate" in gameserver.ini to 0 or a negative number. I would not recommend doing either however.

**Comment by firestar115** [comment]
I want to make sure I can add more gamemodes too not just change decay rate

**Comment by vram4** [comment]
When you make a gamemode, go to /src/gamemodes/index.js and add in 
```javascript
gamemode: require('./gamemode'),
```
underneath 
```javascript
module.exports = {
```
Then underneath
```javascript
var get = function(id) {
    var mode;
    switch (id) {
```
add
``` javascript
        case [ID of gamemode]:
            mode = new module.exports.gamemode();
            break;
```
where `gamemode` is the name of your game mode.

**Comment by firestar115** [comment]
I did that. Repo is (firestar115/Ogar)[https://github.com/firestar115/Ogar]

**Comment by firestar115** [comment]
Fixed by removing .js from the require statement. :P
