### ISSUE TITLE
How to get player's mass?

### ISSUE THREAD

**Issue by firestar115** [OgarProject/Ogar#153]
I am making a gamemode that uses the player's mass to spawn a cell (the w key) but I have no way to access the mass. How do I do this?

Edit: Well, I kind of accomplished what I wanted to...
![steroids](https://cloud.githubusercontent.com/assets/7751296/8883205/edf2d6d8-3201-11e5-9f29-9745bb030e05.png)

**Comment by z3ntu** [comment]
Issue resolved?

**Comment by firestar115** [comment]
No, I still want to find the player's mass.

On 7/28/15, vram4 <notifications@github.com> wrote:
> Closed #153.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/OgarProject/Ogar/issues/153#event-367467122


-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by vram4** [comment]
Look for 
```javascript
Mode.prototype.pressW = function(gameServer,player) {
    // Called when the W key is pressed
    gameServer.ejectMass(player);
};
```
Copy that function to your gamemode and edit it to your liking. Mass can then be found by using 
``` javascript
// Loop through all player cells
for (var i = 0; i < player.cells.length;i++) {
    // Get cell
    var cell = player.cells[i];
    // Get mass
    var mass = cell.mass;
}
```

**Comment by firestar115** [comment]
Oh... I was trying to use player.mass I think...

-- 


     ___      .__   __. .___________. __    __    ______   .__   __.
____    ____
    /   \     |  \ |  | |           ||  |  |  |  /  __  \  |  \ |  |
\   \     /   /
   /  ^  \    |   \|  | `---|  |----`|  |__|  | |  |  |  | |   \|  |
\   \   /   /
  /  /_\  \   |  . `  |     |  |     |   __   | |  |  |  | |  . `  |
  \_    _/
 /  _____  \  |  |\   |     |  |     |  |  |  | |  `--'  | |  |\   |     |  |
/__/     \__\ |__| \__|     |__|     |__|  |__|  \______/  |__| \__|     |__|

**Comment by z3ntu** [comment]
Is this then closed? If yes, please press the CLOSE button!

**Comment by DaFudgeWizzad** [comment]
Can you share how you ejected players?

**Comment by firestar115** [comment]
I didn't eject players, I set the consume mass to 1000 and got so big I
popped all the viruses.

**Comment by DaFudgeWizzad** [comment]
Oh, okay
