### ISSUE TITLE
Game Status Start Up

### ISSUE THREAD

**Issue by CameronRedGem** [OgarProject/Ogar#155]
Hello,

In an ealier issue of a grid and seem to work out pretty smooth. Now I am seeing an error on the launch for the server.

--------
[Game] Ogar - An open source Agar.io server implementation
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +
(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+
e+\+s+r+c+\+G+a+m+e+S+e+r+v+e+r+.+j+s.GameServer.startStatsServer (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +
(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+
e+\+s+r+c+\+G+a+m+e+S+e+r+v+e+r+.+j+s.GameServer.start (<anonymous>)
    at Object.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+
8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+
s+r+c+\+i+n+d+e+x+.+j+s.dev (<anonymous>)
    at u (<anonymous>)
    at <anonymous>
    at Math.Enclose (<anonymous>)
[Game] Listening on port <#>
[Game] Current game mode is Free For All
>
------------------------------------------------------

You know any ideas?

**Comment by Ephemerality** [comment]
From the readme:
> If you are getting an EADDRINUSE error, it means that the port required to run Ogar is being used. Usually, Skype is the culprit. To solve this, either close out skype, or change the serverPort value in gameserver.ini to a different port. You will have to change your connection ip to "127.0.0.1:PORT"

**Comment by CameronRedGem** [comment]
The ports I have set for Agar are 
156 - has error
260 - has error
263 - work fine

**Comment by Ephemerality** [comment]
If those other ports give an EADDRINUSE, it means what it says, they are in use by something else.

**Comment by vram4** [comment]
Can you copy and paste your config?

**Comment by CameronRedGem** [comment]
the config is the address right?

**Comment by vram4** [comment]
No, it is gameserver.ini (should be in the same folder as the ogar exe you ran). Can you copy and paste the contents here?

**Comment by z3ntu** [comment]
And which OS are you using?

**Comment by CameronRedGem** [comment]
Here is port 156 gameserver.ini

serverMaxConnections = 64
serverPort = 156
serverGamemode = 0
serverBots = 0
serverViewBaseX = 1024
serverViewBaseY = 592
serverStatsPort = 88
serverStatsUpdate = 60
serverLogLevel = 1
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 500
foodMass = 1
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusFeedAmount = 7
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = 0.002
playerMinMassDecay = 9
playerMaxNickLength = 15
playerDisconnectTime = 60
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyTimeLimit = 20
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1


Only thing that I change is the "156" to 260 or 263.


I have Windows 8 (Chrome browser for the game)

**Comment by z3ntu** [comment]
Please open cmd and post the output of `netstat -an` here

**Comment by CameronRedGem** [comment]
here is what it said for netstat - an on cmd 
 Proto  Local Address          Foreign Address        State
 TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
 TCP    0.0.0.0:88             0.0.0.0:0              LISTENING
 TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
 TCP    0.0.0.0:156            0.0.0.0:0              LISTENING
 TCP    0.0.0.0:260            0.0.0.0:0              LISTENING
 TCP    0.0.0.0:263            0.0.0.0:0              LISTENING
 TCP    0.0.0.0:443            0.0.0.0:0              LISTENING
 TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
 TCP    0.0.0.0:2869           0.0.0.0:0              LISTENING
 TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING
 TCP    0.0.0.0:6783           0.0.0.0:0              LISTENING
 TCP    0.0.0.0:26143          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49152          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49153          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49154          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49155          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49156          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49159          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49160          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:49161          0.0.0.0:0              LISTENING
 TCP    0.0.0.0:64180          0.0.0.0:0              LISTENING
 TCP    127.0.0.1:5354         0.0.0.0:0              LISTENING
 TCP    127.0.0.1:5354         127.0.0.1:49157        ESTABLISHED
 TCP    127.0.0.1:5354         127.0.0.1:49158        ESTABLISHED
 TCP    127.0.0.1:27015        0.0.0.0:0              LISTENING
 TCP    127.0.0.1:27015        127.0.0.1:49162        ESTABLISHED
 TCP    127.0.0.1:49157        127.0.0.1:5354         ESTABLISHED
 TCP    127.0.0.1:49158        127.0.0.1:5354         ESTABLISHED
 TCP    127.0.0.1:49162        127.0.0.1:27015        ESTABLISHED
 TCP    192.168.1.7:139        0.0.0.0:0              LISTENING
 TCP    192.168.1.7:2869       192.168.1.1:53719      TIME_WAIT
 TCP    192.168.1.7:2869       192.168.1.1:53723      TIME_WAIT
 TCP    192.168.1.7:2869       192.168.1.1:53724      TIME_WAIT
 TCP    192.168.1.7:2869       192.168.1.1:53725      TIME_WAIT
 TCP    192.168.1.7:2869       192.168.1.1:53726      TIME_WAIT
 TCP    192.168.1.7:49991      162.217.248.28:80      ESTABLISHED
 TCP    192.168.1.7:49992      199.16.156.39:443      ESTABLISHED
 TCP    192.168.1.7:50003      91.190.216.64:12350    ESTABLISHED
 TCP    192.168.1.7:50004      111.221.77.166:40012   ESTABLISHED
 TCP    192.168.1.7:50008      157.56.100.176:443     ESTABLISHED
 TCP    192.168.1.7:50017      54.149.51.143:443      TIME_WAIT
 TCP    192.168.1.7:50018      157.56.17.247:443      TIME_WAIT
 TCP    192.168.1.7:50021      157.56.17.247:443      TIME_WAIT
 TCP    192.168.1.7:50027      157.56.17.247:443      TIME_WAIT
 TCP    192.168.1.7:50030      54.215.39.214:443      ESTABLISHED
 TCP    192.168.1.7:50034      157.56.17.247:443      TIME_WAIT
 TCP    192.168.1.7:50046      134.170.19.166:443     ESTABLISHED
 TCP    192.168.1.7:50048      23.209.80.83:443       ESTABLISHED
 TCP    192.168.1.7:50049      23.209.80.83:443       ESTABLISHED
 TCP    192.168.1.7:50059      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50061      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50062      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50065      65.55.44.109:443       TIME_WAIT
 TCP    192.168.1.7:50066      199.16.156.81:443      ESTABLISHED
 TCP    192.168.1.7:50070      23.79.216.159:80       TIME_WAIT
 TCP    192.168.1.7:50076      23.194.113.174:443     ESTABLISHED
 TCP    192.168.1.7:50077      65.55.68.119:443       ESTABLISHED
 TCP    192.168.1.7:50083      65.52.108.11:443       ESTABLISHED
 TCP    192.168.1.7:50084      65.55.2.6:443          ESTABLISHED
 TCP    192.168.1.7:50088      204.79.197.200:443     ESTABLISHED
 TCP    192.168.1.7:50092      23.209.80.83:443       ESTABLISHED
 TCP    192.168.1.7:50094      192.229.163.25:443     ESTABLISHED
 TCP    192.168.1.7:50095      137.135.101.1:443      ESTABLISHED
 TCP    192.168.1.7:50096      192.229.163.25:443     ESTABLISHED
 TCP    192.168.1.7:50097      23.79.215.249:443      ESTABLISHED
 TCP    192.168.1.7:50100      216.58.216.226:80      ESTABLISHED
 TCP    192.168.1.7:50101      50.7.70.146:80         CLOSE_WAIT
 TCP    192.168.1.7:50103      54.152.167.168:443     CLOSE_WAIT
 TCP    192.168.1.7:50105      107.23.204.222:443     CLOSE_WAIT
 TCP    192.168.1.7:50107      173.194.46.124:443     ESTABLISHED
 TCP    192.168.1.7:50110      23.217.138.51:80       ESTABLISHED
 TCP    192.168.1.7:50111      173.194.46.77:80       ESTABLISHED
 TCP    192.168.1.7:50112      173.194.46.77:80       ESTABLISHED
 TCP    192.168.1.7:50114      54.243.146.98:80       CLOSE_WAIT
 TCP    192.168.1.7:50115      162.248.19.136:80      ESTABLISHED
 TCP    192.168.1.7:50116      192.229.163.25:443     ESTABLISHED
 TCP    192.168.1.7:50117      192.229.163.25:443     ESTABLISHED
 TCP    192.168.1.7:50118      192.229.163.25:443     ESTABLISHED
 TCP    192.168.1.7:50119      192.229.163.25:443     ESTABLISHED
 TCP    192.168.1.7:50120      23.79.206.73:443       ESTABLISHED
 TCP    192.168.1.7:50121      23.79.206.73:443       ESTABLISHED
 TCP    192.168.1.7:50122      216.58.216.226:80      ESTABLISHED
 TCP    192.168.1.7:50124      216.58.216.102:80      ESTABLISHED
 TCP    192.168.1.7:50125      205.234.175.175:443    CLOSE_WAIT
 TCP    192.168.1.7:50126      216.58.216.230:80      ESTABLISHED
 TCP    192.168.1.7:50127      54.201.101.91:80       CLOSE_WAIT
 TCP    192.168.1.7:50129      216.58.216.102:443     ESTABLISHED
 TCP    192.168.1.7:50130      216.58.216.230:80      ESTABLISHED
 TCP    192.168.1.7:50131      23.79.206.85:80        CLOSE_WAIT
 TCP    192.168.1.7:50135      23.73.28.77:80         ESTABLISHED
 TCP    192.168.1.7:50136      23.73.28.77:80         CLOSE_WAIT
 TCP    192.168.1.7:50139      75.126.166.172:443     ESTABLISHED
 TCP    192.168.1.7:50140      75.126.118.115:443     ESTABLISHED
 TCP    192.168.1.7:50141      75.126.118.115:443     TIME_WAIT
 TCP    192.168.1.7:50142      75.126.118.115:443     TIME_WAIT
 TCP    192.168.1.7:50143      75.126.118.115:443     ESTABLISHED
 TCP    192.168.1.7:50146      104.43.197.90:443      ESTABLISHED
 TCP    192.168.1.7:50147      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50152      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50153      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50156      199.16.156.81:443      ESTABLISHED
 TCP    192.168.1.7:50159      192.168.1.1:5000       TIME_WAIT
 TCP    192.168.1.7:50160      192.168.1.1:5000       TIME_WAIT
 TCP    [::]:88                [::]:0                 LISTENING
 TCP    [::]:135               [::]:0                 LISTENING
 TCP    [::]:445               [::]:0                 LISTENING
 TCP    [::]:2869              [::]:0                 LISTENING
 TCP    [::]:5357              [::]:0                 LISTENING
 TCP    [::]:26143             [::]:0                 LISTENING
 TCP    [::]:49152             [::]:0                 LISTENING
 TCP    [::]:49153             [::]:0                 LISTENING
 TCP    [::]:49154             [::]:0                 LISTENING
 TCP    [::]:49155             [::]:0                 LISTENING
 TCP    [::]:49156             [::]:0                 LISTENING
 TCP    [::]:49159             [::]:0                 LISTENING
 TCP    [::]:49161             [::]:0                 LISTENING
 TCP    [::1]:26143            [::1]:50050            ESTABLISHED
 TCP    [::1]:26143            [::1]:50051            ESTABLISHED
 TCP    [::1]:26143            [::1]:50052            ESTABLISHED
 TCP    [::1]:26143            [::1]:50053            ESTABLISHED
 TCP    [::1]:26143            [::1]:50054            ESTABLISHED
 TCP    [::1]:26143            [::1]:50055            ESTABLISHED
 TCP    [::1]:50050            [::1]:26143            ESTABLISHED
 TCP    [::1]:50051            [::1]:26143            ESTABLISHED
 TCP    [::1]:50052            [::1]:26143            ESTABLISHED
 TCP    [::1]:50053            [::1]:26143            ESTABLISHED
 TCP    [::1]:50054            [::1]:26143            ESTABLISHED
 TCP    [::1]:50055            [::1]:26143            ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:49994  [2607:f8b0:4002:c03::63
:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:49995  [2607:f8b0:4001:c03::bc
:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50011  [2a01:111:f004:21::240]
443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50014  [2607:f8b0:4009:809::20
e]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50015  [2607:f8b0:4009:809::20
e]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50047  [2607:f8b0:4009:80a::20
5]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50057  [2607:f8b0:4009:808::20
e]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50058  [2607:f8b0:4009:808::20
e]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50074  [2001:559:1c:186::236]:
43  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50075  [2a03:2880:f00b:1:face:
00c:0:1]:443  CLOSE_WAIT
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50079  [2606:2800:11f:179a:197
:2405:35b:459]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50089  [2606:2800:11f:179a:197
:2405:35b:459]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50091  [2001:559:1c:18b::eed]:
43  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50093  [2606:2800:11f:179a:197
:2405:35b:459]:443  CLOSE_WAIT
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50104  [2606:2800:11f:179a:197
:2405:35b:459]:443  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50108  [2607:f8b0:4009:808::20
2]:80  ESTABLISHED
 TCP    [2601:406:8100:4c74:9dbe:af8a:12f8:4d5a]:50113  [2607:f8b0:4009:808::20
2]:80  ESTABLISHED
 UDP    0.0.0.0:443            *:*
 UDP    0.0.0.0:500            *:*
 UDP    0.0.0.0:3544           *:*
 UDP    0.0.0.0:3702           *:*
 UDP    0.0.0.0:3702           *:*
 UDP    0.0.0.0:3702           *:*
 UDP    0.0.0.0:3702           *:*
 UDP    0.0.0.0:3702           *:*
 UDP    0.0.0.0:3702           *:*
 UDP    0.0.0.0:4500           *:*
 UDP    0.0.0.0:5355           *:*
 UDP    0.0.0.0:6783           *:*
 UDP    0.0.0.0:51328          *:*
 UDP    0.0.0.0:54453          *:*
 UDP    0.0.0.0:56934          *:*
 UDP    0.0.0.0:60398          *:*
 UDP    0.0.0.0:64180          *:*
 UDP    127.0.0.1:1900         *:*
 UDP    127.0.0.1:49152        *:*
 UDP    127.0.0.1:49153        *:*
 UDP    127.0.0.1:51204        *:*
 UDP    127.0.0.1:51205        *:*
 UDP    127.0.0.1:52884        *:*
 UDP    127.0.0.1:52885        *:*
 UDP    127.0.0.1:53129        *:*
 UDP    127.0.0.1:53130        *:*
 UDP    127.0.0.1:58949        *:*
 UDP    127.0.0.1:58950        *:*
 UDP    127.0.0.1:60523        *:*
 UDP    127.0.0.1:62700        *:*
 UDP    127.0.0.1:65104        *:*
 UDP    127.0.0.1:65105        *:*
 UDP    192.168.1.7:137        *:*
 UDP    192.168.1.7:138        *:*
 UDP    192.168.1.7:1900       *:*
 UDP    192.168.1.7:5353       *:*
 UDP    192.168.1.7:58750      *:*
 UDP    192.168.1.7:62699      *:*
 UDP    [::]:500               *:*
 UDP    [::]:3702              *:*
 UDP    [::]:3702              *:*
 UDP    [::]:3702              *:*
 UDP    [::]:3702              *:*
 UDP    [::]:3702              *:*
 UDP    [::]:3702              *:*
 UDP    [::]:4500              *:*
 UDP    [::]:5355              *:*
 UDP    [::]:51329             *:*
 UDP    [::]:54454             *:*
 UDP    [::]:56935             *:*
 UDP    [::]:60399             *:*
 UDP    [::1]:1900             *:*
 UDP    [::1]:5353             *:*
 UDP    [::1]:62698            *:*
 UDP    [fe80::1de7:24ac:e025:c310%3]:546  *:*
 UDP    [fe80::1de7:24ac:e025:c310%3]:1900  *:*
 UDP    [fe80::1de7:24ac:e025:c310%3]:62697  *:*

**Comment by z3ntu** [comment]
Jeah something is already listening on port 156...

**Comment by CameronRedGem** [comment]
I change the ports on all of them and still reading the same error.

**Comment by Ephemerality** [comment]
What ports did you choose?

**Comment by CameronRedGem** [comment]
156, 260, 263 were the ones I choose.


Then I switch to these ports 236, 263, 623. I think that message is bouncing in and out depending where I do start it.

**Comment by Ephemerality** [comment]
Not sure if you were running your server or not when the first netstat ran, but:
```TCP 0.0.0.0:156 0.0.0.0:0 LISTENING
TCP 0.0.0.0:260 0.0.0.0:0 LISTENING
TCP 0.0.0.0:263 0.0.0.0:0 LISTENING```
Those ports are in use. You need to choose which config you're going to use (the one in the current directory as you run the server command) and set ports that are not in use. Try 444 or 666, I didn't see those being used in your netstat. You can use that same netstat command that z3ntu mentioned to find out what is being used at the moment.
