### ISSUE TITLE
When i connect Ogar..

### ISSUE THREAD

**Issue by Ganggroid** [OgarProject/Ogar#164]
Using Official client and Ogar

![image](https://cloud.githubusercontent.com/assets/5188404/8904716/ca13895e-349c-11e5-9ca4-dbebfc0dc9b0.png)
![image](https://cloud.githubusercontent.com/assets/5188404/8904725/d7444c6c-349c-11e5-9344-04ba4a32b9a9.png)

Loop..  socket open and close.. why..

**Comment by Darwinkel** [comment]
According to the screenshots, the server is listening on port 444 but you're connecting to port 445.

**Comment by Ganggroid** [comment]
@Darwinkel Because of Portforwading

**Comment by Ephemerality** [comment]
If your client log says "Find THIRD-server" my guess would be that you aren't actually using the official client...

**Comment by Ganggroid** [comment]
@Ephemerality No.. It's Official client. but i revice that.

**Comment by Ganggroid** [comment]
Huh..

**Comment by NNickey** [comment]
You're NOT using the OFFICIAL client.
You MUST use the OFFICIAL client.
Ogar blocks any other connections if the user is NOT on the original website 'agar.io' for LEGAL reasons, undoing this will get you in trouble.
