### ISSUE TITLE
Kick people if they are too long in spectatorsmode

### ISSUE THREAD

**Issue by dazdylz** [OgarProject/Ogar#166]
Hi,

I have a limit of 40 players. Now I run into a problem, people are spectating and other players can't get in now.

Please add a option to kick players if they are too long in spectators mode.

**Comment by NNickey** [comment]
You are able to block the connection by terminating it by cmd, or blocking the IP by malwarebytes.

**Comment by dazdylz** [comment]
I don't want to block them, I want them to kick. I'm running it 24/7 with forever so I have no access to cmd. And I'm not always connected to the server. It should go automatic.

**Comment by dazdylz** [comment]
The server can max handle 40 players, its always full and not all players are alive but 15+ are spectacting.

**Comment by BenCat07** [comment]
How can you host the server 24/7?

**Comment by dazdylz** [comment]
With the forever package

**Comment by BenCat07** [comment]
what or whehre is the forever package?

**Comment by Ephemerality** [comment]
https://www.google.ca/?q=forever%20package

**Comment by z3ntu** [comment]
This link is better: http://lmgtfy.com/?q=forever+package

**Comment by Ephemerality** [comment]
I was trying to be helpful without being too rude :P

**Comment by z3ntu** [comment]
^^

**Comment by DaFudgeWizzad** [comment]
^^ He's right!

**Comment by dazdylz** [comment]
Back to topic please?

**Comment by DaFudgeWizzad** [comment]
This needs to be a thing, with an option to turn it off or customize the time.

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.

**Comment by NatsuTheGreat** [comment]
can someone teach me how to use forever package?

**Comment by mrmarktyy** [comment]
@NatsuTheGreat 
https://github.com/foreverjs/forever

**Comment by AgarioCheats** [comment]
Doesn't running forever cause the server to crash, eventually? Due to overload of memory usage, or processor usage? I thought it needed a restart every X hours.

**Comment by mrmarktyy** [comment]
@AgarioCheats yeah, you can still use forever to govern your game process and do auto restart by crontab or something else.
