### ISSUE TITLE
Friends Connecting

### ISSUE THREAD

**Issue by Zanecdavis** [OgarProject/Ogar#169]
I know I can do agar.io/?ip=127.0.0.1:443 and javascript:connect("ws://localhost:443") on my own computer (I'm using a Mac), but when I put the samething in my friend's computer, it says "WebSocket connection to 'ws://127.0.0.1:443' failed" He is running a Windows desktop. What do I do/what do I give him?

**Comment by Ephemerality** [comment]
http://ipchicken.com You need to give him your IP. 127.0.0.1 refers to your own computer and is only accessible from itself.

**Comment by Zanecdavis** [comment]
When I do that, it says "WebSocket connection to 'ws://myiphere/' failed: Error during WebSocket handshake: Unexpected response code: 200"

**Comment by Zanecdavis** [comment]
And when I put the :443 it says "failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET"

**Comment by Ephemerality** [comment]
Are you on the same network (same house)? If so, you'll probably have to use your internal IP. It would start with 192.168.X.X, you can find it in the Network and Sharing center if you're on Windows.

**Comment by Zanecdavis** [comment]
@Ephemerality Yes, we are. Thanks, I will try it and report back.

**Comment by Zanecdavis** [comment]
@Ephemerality It worked, thank you very much!
