### ISSUE TITLE
when i connect server

### ISSUE THREAD

**Issue by Ganggroid** [OgarProject/Ogar#170]
![image](https://cloud.githubusercontent.com/assets/5188404/8948908/5943f3e8-35e7-11e5-8a22-22b462604a88.png)
I had portforwading

**Comment by vram4** [comment]
What is the browser url that you are on when you connect to the server?

**Comment by Ganggroid** [comment]
@vram4 ganggroid2.iptime.org/kal/game

**Comment by Ganggroid** [comment]
Currently, use Cigar.
but i want officialclient and Ogar.

**Comment by vram4** [comment]
Well, you see, the official client only works with Ogar if you connect to it from the official website: http://agar.io/

**Comment by Ganggroid** [comment]
@vram4 Oh..sorry Site is here
ganggroid2.iptime.org/kal/newgame
that's officialcient's copy.

**Comment by Ganggroid** [comment]
currently, Server is Cigar.

**Comment by NNickey** [comment]
If you are trying to connect to the Ogar server, and the Ogar server is running on the exact pc that your trying to play agar.io from.. You need to use ws://localhost:445 instead.
Otherwise...

**Comment by NNickey** [comment]
@Ganggroid I may want to take that agar.io copy down if I were you.. If it isn't verified by the creator, it may be copyright and can be taken down by DMCA.. It's not legal, as in the Ogar config, they had to check to make sure your domain is at agar.io or block the connection.

**Comment by NNickey** [comment]
You can host an Ogar server anytime, but you CANNOT connect to it if your NOT on the original website that its REQUIRED and LEGALLY forced to use called 'AGAR.IO'..
If you're trying to connect from a different website, OGAR will block it for LEGAL reasons.
Uplifting this code that blocks users coming from other websites is ILLEGAL, as the comments around that code state that it will get you in trouble..

**Comment by NNickey** [comment]
No matter what.. You CANNOT connect to an OGAR server from "ganggroid2.iptime.org/kal/newgame".. as your connection will ALWAYS be blocked because you HAVE to be on the "agar.io" website to have it accept your connection..
