### ISSUE TITLE
Glitches when I join the server

### ISSUE THREAD

**Issue by csendo2** [OgarProject/Ogar#173]
I ran Ogar in the command prompt because if I want to run it in .exe, it quickly disappears. When I join to the server, I see this:https://www.dropbox.com/s/16ysmxufv1jb3jt/n%C3%A9vtelen.bmp?dl=0
I can control the game in the command prompt (kill cells with the kill command and add bots), but I can't play. Yes, I know Windows XP is old, but unfortunately my compter only works with this.

**Comment by BenCat07** [comment]
I see you are using an old version get the new one!
Http://dl.ogarproject.com

You got an error in the console that was in old versions of the server

**Comment by BenCat07** [comment]
The .exe should be called Ogar-Windows-bae606.exe

**Comment by BenCat07** [comment]
Ups i mean 
Ogar-Windows-bae606f.exe

**Comment by csendo2** [comment]
I wasn't running it with the exe file. I ran it with the Launch.bat. But I downloaded the exe what you said and still doesn't work.

**Comment by Ephemerality** [comment]
You would have to delete the exe (somewhere in the Ogar folder) and replace it with the new one you downloaded, changing the name to match whatever it was before (Ogar.exe possibly?).

**Comment by csendo2** [comment]
Still doesn't work... :(

**Comment by csendo2** [comment]
If i start the .exe, it appears, and I can see it for 0.1 second and then it disappears.

**Comment by Ephemerality** [comment]
If you properly replaced the old exe with the new one, you can still run with Launch.bat like you were doing.
Chances are, if you are just running the exe without changing the config or putting it in the right spot, the default port is in use and it's just failing. If you have Skype open, close it and try again.

**Comment by csendo2** [comment]
Thank you for the help, but I fixed it an other way. I downloaded the Ogar zip again, and started the game with Start.bat in the  src folder!

**Comment by Ephemerality** [comment]
That works too, if you have Node installed and the ws module already, yeah.
