### ISSUE TITLE
How can I access the virus and ejected mass in a custom game mode?

### ISSUE THREAD

**Issue by DaFudgeWizzad** [OgarProject/Ogar#175]
I recently made a change to my sever so I can eject viruses! I made this change to the index.js file in the entity folder:

module.exports = {
    Cell: require('./Cell'),
    PlayerCell: require('./PlayerCell'),
    Food: require('./Food'),
    Virus: require('./Virus'),
    EjectedMass: require('./Virus'),
};

As you can see, the ejected mass comes from the virus file, but how can I apply this change in my own gamemode.js file without modifying the index file?

**Comment by batbug** [comment]
this is absolutely wrong way

**Comment by DaFudgeWizzad** [comment]
@batbug I'm confused, could you explain more, please?

**Comment by DaFudgeWizzad** [comment]
I will figure it out, I guess no one knows...
