### ISSUE TITLE
I cant play on the server!!!???

### ISSUE THREAD

**Issue by JJJupiter** [OgarProject/Ogar#178]
I was so happy to have finally created my own agar.io server! and whn i spawn, I spawn out of the map!? please help me as fast as possible!!

                                                          Best Regards,
                                                                                Justin

**Comment by vram4** [comment]
What operating system are you on? Also are you on the official client at agar.io?

**Comment by JJJupiter** [comment]
Im using Windows 7 home premium why? and yes i am using the official site agar.io

**Comment by vram4** [comment]
The latest version of the server for windows can be downloaded from http://dl.ogarproject.com/

**Comment by JJJupiter** [comment]
Ok thx!i will try it. should I tell you if something didnt work?

**Comment by vram4** [comment]
Just comment here if it doesnt work

**Comment by JJJupiter** [comment]
ok thx so much!!! it works, but now i dont know how to connect to it

**Comment by vram4** [comment]
Wait.. how did you connect to it last time?

**Comment by vram4** [comment]
If you havent changed any settings, you can connect by typing ```agar.io/?ip=127.0.0.1:443``` in your browsers address bar

**Comment by JJJupiter** [comment]
ok thx!!
