### ISSUE TITLE
Unknown Issue Causes Impossible Game Play Upon Joining

### ISSUE THREAD

**Issue by Peekofwar** [OgarProject/Ogar#180]
With default settings, it won't work correctly. The server works, but it seems like the boundaries are really tight, even though they aren't. MAJOR BUG / ISSUE. I cannot specify what went wrong but it just will not work. Even tweaking the bounds doesn't work.

**Comment by vram4** [comment]
If you are on windows, please download the latest version at http://dl.ogarproject.com/ and make sure you are using the official client at agar.io . If you still get the problem, can you paste your config here?

**Comment by Peekofwar** [comment]
Thanks! It works now, even with AgarioMods installed!
