### ISSUE TITLE
how can my friend join my private agar.io server?

### ISSUE THREAD

**Issue by JJJupiter** [OgarProject/Ogar#182]
hello there,
yesterday i created an agar.io server and now i want to know how my friend can join it.
thx for the support 
best regards Justin

**Comment by Darwinkel** [comment]
Once the game server is running, you can connect by typing agar.io/?ip=your.ip:port into your browser's address bar.

**Comment by JJJupiter** [comment]
My friend isnt local though. does he have to type in agar.io/?ip=127.0.0.1:443 into his browser?
or how do i find out my ip?

**Comment by JJJupiter** [comment]
i live in germany and my friend in the usa and we want to play agar.io together on my private server so how do we do that ?

**Comment by abalabahaha** [comment]
Google port forwarding, forward port 443 to your computer.
Go to (http://whatsmyip.org)[http://whatsmyip.org] and get your ip
Tell your friend to connect to agar.io/?ip=<your-ip>:443, replacing <your-ip> with the IP you got from WhatsMyIP

**Comment by JJJupiter** [comment]
ok thx ill try

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
