### ISSUE TITLE
Whats The Normal Agario Map size numbers

### ISSUE THREAD

**Issue by AgarFan250** [OgarProject/Ogar#189]
i messed mine up on mistake i ment to change food pickup instead i changed map size

**Comment by kcxx** [comment]
In the config:
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)

**Comment by Ephemerality** [comment]
Those are the old values. New values are approx -7071.068 to 7071.068.
If you mess up your values, just delete the config file and it will recreate one when you run the server again.
