### ISSUE TITLE
How to Specify Team color in Experimental or FFA mode?

### ISSUE THREAD

**Issue by helma27** [OgarProject/Ogar#190]
Last issue, i had question with team color, and mr. @vram4 kindly help me :D 
That was i looking for, and this time, how to specify color in Experimental or FFA?
My intention is, to make admin in defferent color, like Blaack color :)
Thank you :)

**Comment by maixuanhan** [comment]
Why don't you use **color** command? And fyi, you can find it in README.md file, or read here https://github.com/OgarProject/Ogar

```javascript
// example
color <some_id> 7 7 7
```

**Comment by helma27** [comment]
i know it
Oh, i forgot to mention my earlier issue https://github.com/OgarProject/Ogar/issues/126

What i need is to specify it without command on terminal, so we can automatically specify to color what we want :)
Something like this:
```
Teams.prototype.getTeamColor = function(team) {
    // Gets the base color of the current team
    var color = this.colors[team];
    // Constructs a color json object
    return {
        // Each value is randomized a bit so not all colors of the people on the same team are identical
        r: this.fuzzColorComponent(color.r),
        b: this.fuzzColorComponent(color.b),
        g: this.fuzzColorComponent(color.g)
    };
};
```
Above code is about to specify color in team mode~

**Comment by Porama6400** [comment]
if you understand about javascript

Server:
you can go to Team.js (in gamemode folder) and change color
but you need to recompile it

Client:
Sorry , no way to change team color on client

**Comment by batbug** [comment]
actually at this point we cannot do this without modifiyng the client side code

**Comment by helma27** [comment]
@batbug yes, because i'm using agar-clone :)

**Comment by batbug** [comment]
ok i'll give you the idea
enter your team in the nickname, like "superplayer:[team1]"
then at server parse the nick. 


Teams.prototype.onPlayerSpawn = function(gameServer,player) {
    var dlina = player.name.length - 8;
    if (player.name.indexOf('[team:1]') != -1) {
        player.team = 1;
	player.name = player.name.substr(8,dlina);
    }
....
like that. 
got it?

**Comment by helma27** [comment]
@batbug i think that's for Teams Mode,
how to do that in FFA or Experimental Mode?
Sorry, i'm new at these language..

something like this?
'''javascript
FFA.prototype.onPlayerSpawn = function(gameServer,player) {
var dlina = player.name.length - 8;
if (player.name.indexOf('[team:1]') != -1) {
var color = e.getColor();
            player.setColor({
                ["#000000"], // black color
            });
player.name = player.name.substr(8,dlina);
}
'''

**Comment by batbug** [comment]
@helma27 no. you do not set color to make his. SET .TEAM

**Comment by helma27** [comment]
@batbug is that aplicable for FFA or Experimental mode?

**Comment by batbug** [comment]
Should be.

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support (this includes development assistance) on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
