### ISSUE TITLE
i can't join my server please help

### ISSUE THREAD

**Issue by thisisrami** [OgarProject/Ogar#191]
connect("ws://86.96.36.245:9090")
(index):403 Connecting to ...
VM7365:1 Connecting to ws://86.96.36.245:9090
undefined
WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM7365:1 socket error
VM7365:1 socket close
VM7365:1 Find EU-London
(index):403 Connecting to ...
VM7365:1 Connecting to ws://37.187.163.240:1504
VM7365:1 socket open (agariomods.com mod in place)
18VM7365:1 Skipping draw
VM7365:1 Find EU-London
(index):403 Connecting to ...
VM7365:1 Connecting to ws://151.80.98.61:1503
VM7365:1 socket open (agariomods.com mod in place)

**Comment by VakoNoway** [comment]
Try http://agar.io/?ip=86.96.36.245:9090

**Comment by VakoNoway** [comment]
Try to disable agariomods.com mod.

**Comment by thisisrami** [comment]
Find EU-London
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
pubads_impl_68r2.js:139 GET https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&correlator=361…r2&vrp=68r2&ga_vid=383853673.1435615853&ga_sid=1438882435&ga_hid=177371231 net::ERR_BLOCKED_BY_CLIENTrj @ pubads_impl_68r2.js:139Wj @ pubads_impl_68r2.js:171Xj @ pubads_impl_68r2.js:170Yj @ pubads_impl_68r2.js:169gk @ pubads_impl_68r2.js:176V.Y @ pubads_impl_68r2.js:173k.refresh @ pubads_impl_68r2.js:199k.refresh @ pubads_impl_68r2.js:226(anonymous function) @ ?ip=86.96.36.245:9090:401fd.push @ pubads_impl_68r2.js:16(anonymous function) @ pubads_impl_68r2.js:250(anonymous function) @ pubads_impl_68r2.js:252
pubads_impl_68r2.js:249 GET http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html net::ERR_BLOCKED_BY_CLIENTxl @ pubads_impl_68r2.js:249(anonymous function) @ pubads_impl_68r2.js:250(anonymous function) @ pubads_impl_68r2.js:252
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:404 socket close
mods.js:26 Testing complete, 31 units passed and 0 units failed.
VM9942:1 Find EU-London
?ip=86.96.36.245:9090:402 Find EU-London
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Connecting to ws://86.96.36.245:9090
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: WebSocket is closed before the connection is established.
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
?ip=86.96.36.245:9090:422 CAAJoMBwWJiMBAKMXzVneZCtlHzcDrcf4FQZAiBaOAkW12dSXrEntaHT5UH0DYATDsefHzqXTZCMnZCB72ZCezt5COLsjAZClOAJ3ogERjPaj6DtGNVTYacxu4QibCkwZAQfcRDtiWSZBEiBOz0z2pNHp5VZC0ALJ3RoLZB6CF78oN8WTPbMAX8wrl1h3ZCG9ZCn0jWLg0yIBvaXHgUvDUvIuoziX
WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM9942:1 socket error
VM9942:1 socket close
VM9942:1 Find EU-London
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: WebSocket is closed before the connection is established.
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Connecting to ws://86.96.36.245:9090
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:404 socket close
?ip=86.96.36.245:9090:402 Find EU-London
WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM9942:1 socket error
VM9942:1 socket close
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Find EU-London
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: WebSocket is closed before the connection is established.
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Connecting to ws://86.96.36.245:9090
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:404 socket close
WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM9942:1 socket error
VM9942:1 socket close
?ip=86.96.36.245:9090:402 Find EU-London
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Find EU-London
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: WebSocket is closed before the connection is established.
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Connecting to ws://86.96.36.245:9090
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:404 socket close
WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM9942:1 socket error
VM9942:1 socket close
?ip=86.96.36.245:9090:402 Find EU-London
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Find EU-London
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: WebSocket is closed before the connection is established.
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:403 Connecting to ws://86.96.36.245:9090
VM9942:1 Connecting to ws://86.96.36.245:9090
?ip=86.96.36.245:9090:403 WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
?ip=86.96.36.245:9090:404 socket error
?ip=86.96.36.245:9090:404 socket close
WebSocket connection to 'ws://86.96.36.245:9090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM9942:1 socket error
VM9942:1 socket close

**Comment by thisisrami** [comment]
Connecting
If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection.

**Comment by thisisrami** [comment]
thats what they say

**Comment by thisisrami** [comment]
ok i couldn't connect my friend did but the world was f up

**Comment by Ephemerality** [comment]
If you're trying to connect from the same computer you are running the server on, try 127.0.0.1:9090 (assuming 9090 is the port you are running it on) instead.
If the world looks messed up, you have the wrong version and should download the latest from http://dl.ogarproject.com.

**Comment by thisisrami** [comment]
ok man love you no homo tho
