### ISSUE TITLE
Can't Eat Food Cells Spawned by the Command-Prompt.

### ISSUE THREAD

**Issue by Darshil182** [OgarProject/Ogar#194]
Please help I Can't Eat Food Cells Spawned by the Command-Prompt.

**Comment by DaFudgeWizzad** [comment]
add "mass" and "pos" into the food command's parameters

**Comment by liampikee** [comment]
Cant even join mine

**Comment by higoing00** [comment]
I know this issue. Wherever you spawned it do not go there because it will instantly kill you no matter how big you are, even if u have 25k, it is an invisible killer.

**Comment by Agarian** [comment]
@liampikee  in case you don't know the ip is 127.0.0.1:PORT 
To find the port open gameserver.ini and find serverPort and use that port.

**Comment by NatsuTheGreat** [comment]
@higoing00 What are you talking about man? How does it kill... He was talking about him NOT being able to eat it.. I wouldn't kill, it would let you under it (ex. if you are smaller then a virus, you go under it.)

When you spawn this food cell, you had to give it coordinates, and the size of the food. For example:

food 3000 3000 400

Here's the syntax of the command:

food [X coordinate] [Y coordinate] [food cell mass]

If you don't specify the food mass, it will spawn a food pellet the size of all the food pellets, which is the mass you have in gameserver.ini, *foodMass*

This would spawn a food cell with 400 mass at X; 3000 Y: 3000. You can use the tp command to teleport yourself there, and set your mass if you're not big enough.
