### ISSUE TITLE
is it normal

### ISSUE THREAD

**Issue by Porama6400** [OgarProject/Ogar#196]
i'm trying to understand how ogar work
I'm use protocol analyzer to analyze Agar.io connection
and i got this Message from port 443

GET / HTTP/1.1
Host: localhost:443
Connection: Upgrade
Origin: http://agar.io
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Accept-Encoding: gzip, deflate, sdch
Accept-Language: th-TH,th;g=0.8
Sec-WebSocket-Key: ggm928lWZ7QOXXmH9qKw+Q==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

i don't see any code in  Ogar that look like use to read this message
is it normal?

**Comment by vram4** [comment]
This is part of the websocket handshake that is used to start an actual websocket connection. It is handled by the "ws" module, not ogar.

**Comment by Porama6400** [comment]
oh thanks
