### ISSUE TITLE
hai, connection issues?

### ISSUE THREAD

**Issue by smokes** [OgarProject/Ogar#197]
so idk if i'm just dumb or what, but i thought i didn't need anything to join a public ogar server other than a browser with agar... i can't seem to join any public servers that exist using any method i've seen listed. 
what am i doing wrong? 
do i need to install any of this code?

**Comment by Ephemerality** [comment]
If someone is already running a server properly, you don't need anything else. If the know the IP and port the server is on you should be able to go to http://agar.io/?IP:PORT and connect to it. Any errors show up in the JS console (F12, Console in Chrome).

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
