### ISSUE TITLE
Memory increases over time!

### ISSUE THREAD

**Issue by wpvn-info** [OgarProject/Ogar#198]
I open my server 24/24h by using forever on Centos 6.5.
At first it will occupy only a little memory about 100MB and it increased gradually thereafter.
After 24 hours it can be up to 2GB of memory. At this time I have about 40 user with 10 bot.

After I restarted nodejs. With same user and bot it only takes up very little memory about 300MB.

**Comment by wpvn-info** [comment]
![capture](https://cloud.githubusercontent.com/assets/10359131/9155077/3c9b1562-3ed6-11e5-8103-9f0f92f0f37c.PNG)
My Server run only Ogar latest version.

**Comment by Ephemerality** [comment]
Typically this only happens if someone is attacking your server, but random bugs in the websocket module could probably cause it as well. This shouldn't be an issue once Ogar 2 is released.

**Comment by wpvn-info** [comment]
I dont think this problem because someone attacking my server. After I restart server it take only ~100MB memory. And after about 24 hours this will increases memory to ~2000MB. It always happens after about 24 hours.

Thank you for your time! :)
