### ISSUE TITLE
Run command list

### ISSUE THREAD

**Issue by bulkiter0z** [OgarProject/Ogar#200]
how can i run the command if I use forever nodejs to execute the ogar?

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
