### ISSUE TITLE
Port does not using, but Server could not bind to port

### ISSUE THREAD

**Issue by Ganggroid** [OgarProject/Ogar#201]
![2015-08-11 16 09 41](https://cloud.githubusercontent.com/assets/5188404/9192169/6ff0fbac-4043-11e5-8606-4a2bcb529a58.PNG)

Server setting is here
serverMaxConnections = 128
serverPort = 454
serverGamemode = 0
serverBots = 30
serverViewBaseX = 1024
serverViewBaseY = 592
serverStatsPort = 88
serverStatsUpdate = 60
serverLogLevel = 1

Please help me!
currently, 451,452 are running(cigar).

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
