### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by genckaptan55** [OgarProject/Ogar#202]
Server memory usage increasing permanently and at a point the server needed to be restarted. What the problem about is that. I couldn't solve..

**Comment by wpvn-info** [comment]
Yes, I'm not the only person experiencing.
https://github.com/OgarProject/Ogar/issues/198

**Comment by wpvn-info** [comment]
I found this problem because the last function in GameServer.js file.
```javascript
WebSocket.prototype.sendPacket = function(packet) {
    function getBuf(data) {
        var array = new Uint8Array(data.buffer || data);
        var l = data.byteLength || data.length;
        var o = data.byteOffset || 0;
        var buffer = new Buffer(l);

        for (var i = 0; i < l; i++) {
            buffer[i] = array[o + i];
        }

        return buffer;
    }
    
    //if (this.readyState == WebSocket.OPEN && (this._socket.bufferSize == 0) && packet.build) {
    if (this.readyState == WebSocket.OPEN && packet.build) {
        var buf = packet.build();
        this.send(getBuf(buf), {binary: true});
    } else if (!packet.build) {
        // Do nothing
    } else {
        this.readyState = WebSocket.CLOSED;
        this.emit('close');
        this.removeAllListeners();
    }
};
```
For Now I fix this by using the old function of @vram4 author.
```javascript
WebSocket.prototype.sendPacket = function(packet) {
    // Send only if the buffer is empty
    if (this.readyState == WebSocket.OPEN && (this._socket.bufferSize == 0) && packet.build) {
        try {
            this.send(packet.build(), {binary: true});
        } catch (e) {
            console.log("[Error] "+e);
            // Remove socket
            this.emit('close');
            this.removeAllListeners();
        }
    } else if (!packet.build) {
        // Do nothing
    } else {
        // This will cause a memory leak so we need to remove the socket
        this.emit('close');
        this.removeAllListeners();
    }
};
```
It has fixed the memory problem but apparently caused LAG in game.
I do not know much about nodejs, so I'm not sure what is the problem here. I hope the author will fixed this soon.

Thanks alot for the people who created this game. It was very fun!

**Comment by genckaptan55** [comment]
Did you see this error?

RangeError: attempt to write beyond buffer bounds

**Comment by DaFudgeWizzad** [comment]
You have to use a fresh Ogar Server or make the make bigger. Sometimes only one works.

**Comment by CloudyM** [comment]
Yes, my server is having this issue too. Memory usage gets so high it freezes my VPS.

**Comment by alph43oss** [comment]
Just curious what version of NodeJs you guys with memory leaks are using. After upgrading to v10.40 (from v6.12) the runaway memory increases have stopped.

**Comment by MastaCoder** [comment]
I know this is quite old, but I just wanted to add on. If you use JXCore instead of Node.js to run the server, then you can remove the memory leak. JXCore is much better built and can support multi threading, etc.

**Comment by Ciao121** [comment]
I'm using jx the function ending with
`else {
        this.readyState = WebSocket.CLOSED;
        this.emit('close');
        this.removeAllListeners();
    }
};`
but the problem is stille there.
A server I made was using > 19 GB of memory.after 3 days.
Does anybody know a way to test fixes without waiting so much time to see results and if it happens only with real players or also using bots?

**Comment by Ciao121** [comment]
Maybe I did not understood... which should I use with jx? The versione with
"this.readyState = WebSocket.CLOSED;"
or without it? :)

**Comment by MastaCoder** [comment]
I while ago I read something that the bots had a major leak in the system. You can try using the old code that @vram4 adding onto an older version of Ogar, it fixed the leak but caused freezing. About the bot thing, I don't remember the fix, but I could have sworn I saw someone else have issues with this and was using bots.

Also I wouldn't keep a server up for 3 days straight with all those players. Even the Agar.io servers reset every 24 hours. You should try some sort of daily reset time for all the servers. :+1:

**Comment by Luka967** [comment]
@vram4 Close?

**Comment by Barbosik** [comment]
the problem with memory leaks is related to setTimeout and SetInterval. I removed it in MultiOgar, and now it works with no memory leaks
