### ISSUE TITLE
Cant move

### ISSUE THREAD

**Issue by CallyWasHere** [OgarProject/Ogar#204]
For some reason... I cant move...

Ive been using ogar for a while and its worked fine... all of a sudden i cant move

Im able to split and all the bots move

**Comment by vram4** [comment]
Please see 571bd36013df144f194c2d644ea3e3687201f1eb Update your server, if you havent already.

**Comment by CallyWasHere** [comment]
now i cant start the server

I just re downloaded it

**Comment by forairan** [comment]
Please redownload from the binaries page again; our binary builds were broken, but they're working again.

**Comment by CallyWasHere** [comment]
..

**Comment by CallyWasHere** [comment]
okay

**Comment by CallyWasHere** [comment]
So redownload and run?
