### ISSUE TITLE
Cell colors

### ISSUE THREAD

**Issue by Creeperman8362** [OgarProject/Ogar#208]
Cell colors are much more limited and too similar than on the regular version.

**Comment by vram4** [comment]
You can add your own colors in src/gameserver.js line 96.

**Comment by Creeperman8362** [comment]
ok i want a list of like 100+ colors im too lazy to do it myslelf

**Comment by Ephemerality** [comment]
And you want someone else to do it for you for free! #murica

**Comment by maixuanhan** [comment]
@Creeperman8362 : Give me 50 bucks, I'll do it for you :)

**Comment by maixuanhan** [comment]
Kidding! replace or change the `getRandomColor` function in that file to below code
```

    GameServer.prototype.getRandomColor = function () {
        var colorRGB = [0xFF, 0x07, ((Math.random() * (256 - 7)) >> 0) + 7];
        colorRGB.sort(function () { return 0.5 - Math.random() });
        return {
            r: colorRGB[0],
            b: colorRGB[1],
            g: colorRGB[2]
        };
    };
```
it helps generate random color with over 100+ colors. btw, i'm lazy too, so i think of this way...

**Comment by blueoiler** [comment]
but i just want to know ho to make a server

**Comment by Ephemerality** [comment]
@blueoiler https://www.youtube.com/watch?v=hKNld_MMFZs

**Comment by Creeperman8362** [comment]
thx the randomness should really be on by default
