### ISSUE TITLE
Buggy server

### ISSUE THREAD

**Issue by Quentin1o** [OgarProject/Ogar#210]
The server is started, when I join the game I turn into a big black glitchy block moving rapidly to the right and out of bounds. I have tried re-installing ogar but it does not solve the problem.
Can someone help me?

Thanks in advance

**Comment by genckaptan55** [comment]
Do you use client files or..?

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.
