### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by erol1602** [OgarProject/Ogar#215]
i installed to my debian server. when i start the node agar, 443 webpage says
"Upgrade Required"
and 88 is OK. no problem there. what is the problem ?

**Comment by Ephemerality** [comment]
Am I correct in assuming you are trying to host your own client or is it giving you that error when you try to connect to it from http://agar.io?

**Comment by Dubz** [comment]
I'm getting the same issue and visiting http://agar.io/?ip=example.com:443 does not work at all.

**Comment by NatsuTheGreat** [comment]
To connect to your server you could use http://agar.io/?ip=localhost:[PORT] or http://agar.io/?ip=127.0.0.1:[PORT]

I have tried to get this error many time and what I got was, you probably didn't include the *http://agar.io/?ip=* You probably just put in the second portion in.

**Comment by NatsuTheGreat** [comment]
Click ![here](http://prntscr.com/9kfr6e) to see what I mean

**Comment by NatsuTheGreat** [comment]
http://tinyurl.com/zsg4elw 

You probably did this.
