### ISSUE TITLE
Suddenly server says "Killed"

### ISSUE THREAD

**Issue by devcem** [OgarProject/Ogar#216]
I have server with 2 CPU and 2GB ram at Digitalocean. There is no memory usage or CPU problem. But sometimes, Ogar script says "Killed". And nodejs gameserver stops. Is that issue or bug? If it isn't a bug how can fix that problem?

**Comment by vram4** [comment]
What script are you using to run Ogar?

**Comment by devcem** [comment]
I didn't understand what do you mean with script but i'm using nodejs to run Ogar script. I upgraded my server to 4GB CPU but it says "Killed" again. If is there a bug on the script how can debug and fix it.

For example today, i was trying that script with 100 connection, it said "FATAL ERROR: Evacuation Allocation failed - process out of memory". Yes i can understand what is the problem with that message. That is very clear, but i can't understand "Killed" message. I need to mean of it.

**Comment by mafiakb** [comment]
me too say me killed

**Comment by AgarioCheats** [comment]
It's a problem. It suddenly says killed, after running for about 10+ hours. Perhaps the server needs a scheduled restart every X hours?

**Comment by Andrews54757** [comment]
It is probably a memory leak issue

**Comment by Andrews54757** [comment]
Currently there is no good solution. There is one solution but it causes lots of lag

**Comment by Luka967** [comment]
**Memory leak issue**. Please don't start it again.
