### ISSUE TITLE
Pointless Operation?

### ISSUE THREAD

**Issue by Joncom** [OgarProject/Ogar#226]
On [line 50 of Cell.js](https://github.com/OgarProject/Ogar/blob/master/src/entity/Cell.js#L50), we see the following function:

```
Cell.prototype.getSquareSize = function () {
    // R * R
    return (100 * this.mass) >> 0;
};
```

If the purpose of the `>>` operator is to shift bits to the right, and we therefore shift some number `0` bits to the right, nothing changed, correct?

So what's the point of having this `>>` operator here at all?

**Comment by mrmarktyy** [comment]
@Joncom  it's for clean the decimal number

**Comment by Joncom** [comment]
Oh I see! Thanks for the quick reply.
