### ISSUE TITLE
how do my friends connect i tried the IP i used and i could get in

### ISSUE THREAD

**Issue by DerpressedTiger** [OgarProject/Ogar#227]

**Comment by Youtubrer** [comment]
is the port forwarded?

**Comment by DerpressedTiger** [comment]
i figured out how to but thanks :D

**Comment by PreyasV** [comment]
I Also Have Same Issue.

**Comment by 14anthony7095** [comment]
if you've port forwarded then check your public ip to have your friend(s) connect with.
if not port forwarded (or just can't) you can use hamachi
ex: http://agar.io/?ip=135.x.x.x:443

**Comment by DaFudgeWizzad** [comment]
REQUEST CLOSE!
