### ISSUE TITLE
Need to change LeaderBoard Text

### ISSUE THREAD

**Issue by ghost** [OgarProject/Ogar#232]
I need to change  LeaderBoard Text to board cast.
It the only way to board cast.

Can u show me how to change it?
Plz add apis

**Comment by vram4** [comment]
What do you mean by board cast?

**Comment by genckaptan55** [comment]
I suppose to use it as announcement he meant.

**Comment by vram4** [comment]
In that case, i would use the `board` command in the ogar console.

>- Board [String 1] [String 2] [String 3] ...
>  - Replaces the text on the leaderboard with the string text.

**Comment by Agarian** [comment]
For example: board this is the string each word is one position

**Comment by MastaCoder** [comment]
@vram4 You *might* want to close this one too.
