### ISSUE TITLE
I need help!! Im using mac!

### ISSUE THREAD

**Issue by x38** [OgarProject/Ogar#234]
admins-iMac-2:~ admin$ sudo -s
Password:
bash-3.2# node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/admin/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
bash-3.2# 

Please help i got everything right i got the index.js file in src i cant seem to fix it i've installed bash, node js, and everything is normal. what the hell >:(

**Comment by Ephemerality** [comment]
When you're typing `node index.js` you're telling it "run the index.js file from the current directory" but from the looks of it, you're in /Users/admin not in the actual Ogar/src folder where the index.js is. You need to `cd` to the proper directory before running node.

**Comment by x38** [comment]
So i need to change directory how do i do that? I still am frustrated and i don't clearly get it :(

**Comment by Ephemerality** [comment]
It really depends where you have the Ogar folder and where you are. If it was in your Downloads folder and you started in /Users/admin (like it appears you are), you'd do:
`cd Downloads/Ogar/src`

**Comment by x38** [comment]
My ogar folder is in documents. this is what is inside the SRC: Ai, botnames.txt, entity, gamemodes, gameserver.ini, gameserver.js, index.js, modules, packet, packethandler.js, playertracker.js, start.bat. All folders are fine even the main ogar one. Something is missing or wrong and i cant seem to find :(

**Comment by x38** [comment]
Also eveything looks right, it used to work before now its just giving me hell of an error which i am running under documents so what do i put or do now?

**Comment by Ephemerality** [comment]
Paste the error here (or the first bit if it's long).

**Comment by x38** [comment]
admins-iMac-2:~ admin$ sudo -s
bash-3.2# node index.js
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/admin/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
bash-3.2#

**Comment by Ephemerality** [comment]
You're still not in the right folder. Try typing `cd Documents/Ogar/src` first.

**Comment by x38** [comment]
where to write?

**Comment by Ephemerality** [comment]
You're in Terminal, are you not? Since your Ogar folder is called Ogar-master the command would be `cd /Users/admin/Documents/Ogar-master/src` hit enter and make sure it works (should say Ogar-master on the next prompt) and then do your `node index.js`...

**Comment by x38** [comment]
Last login: Tue Sep 15 18:55:15 on ttys000
admins-iMac-2:~ admin$ cd /Users/admin/Documents/Ogar-master\ 3 
admins-iMac-2:Ogar-master 3 admin$ node index.js
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/admin/Documents/Ogar-master 3/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by Ephemerality** [comment]
You didn't do `cd /Users/admin/Documents/Ogar-master/src`, you left the /src off. The index.js file is in /src so you have to be in there.

**Comment by x38** [comment]
admins-iMac-2:~ admin$ cd /Users/admin/Documents/Ogar-master\ 3 /src
admins-iMac-2:Ogar-master 3 admin$ node index.js
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/admin/Documents/Ogar-master 3/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by Ephemerality** [comment]
Still not making it into the src folder... if you do an `ls` it will show what's in the current directory. You're making it into the Ogar-master folder so you should be able to `cd src` to get into src.

**Comment by x38** [comment]
admins-iMac-2:~ admin$ cd /Users/admin/Documents/Ogar-master\ 3 /src
admins-iMac-2:Ogar-master 3 admin$ node index.js
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/admin/Documents/Ogar-master 3/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by Ephemerality** [comment]
`cd src` before `node index.js`

**Comment by x38** [comment]
admins-iMac-2:~ admin$ cd /Users/admin/Documents/Ogar-master/src
admins-iMac-2:src admin$ node index.js
[Game] Ogar - An open source Agar.io server implementation
Error: listen EACCES 0.0.0.0:88
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at GameServer.startStatsServer (/Users/admin/Documents/Ogar-master/src/GameServer.js:907:21)
    at GameServer.start (/Users/admin/Documents/Ogar-master/src/GameServer.js:219:10)
    at Object.<anonymous> (/Users/admin/Documents/Ogar-master/src/index.js:25:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
[Error] Please make sure you are running Ogar with root privileges.
admins-iMac-2:src admin$ admins-iMac-2:~ admin$ cd /Users/admin/Documents/Ogar-master\ 3 /src
-bash: admins-iMac-2:~: command not found
admins-iMac-2:src admin$ admins-iMac-2:Ogar-master 3 admin$ node index.js
-bash: admins-iMac-2:Ogar-master: command not found
admins-iMac-2:src admin$ module.js:338
-bash: module.js:338: command not found
admins-iMac-2:src admin$     throw err;
-bash: throw: command not found
admins-iMac-2:src admin$     ^
-bash: ^: command not found
admins-iMac-2:src admin$ 
admins-iMac-2:src admin$ Error: Cannot find module '/Users/admin/Documents/Ogar-master 3/index.js'
-bash: Error:: command not found
admins-iMac-2:src admin$     at Function.Module._resolveFilename (module.js:336:15)
-bash: syntax error near unexpected token `('
admins-iMac-2:src admin$     at Function.Module._load (module.js:286:25)
-bash: syntax error near unexpected token `('
admins-iMac-2:src admin$     at Function.Module.runMain (module.js:475:10)
-bash: syntax error near unexpected token `('
admins-iMac-2:src admin$     at startup (node.js:117:18)
-bash: syntax error near unexpected token `('
admins-iMac-2:src admin$     at node.js:951:3
at: garbled time

**Comment by Ephemerality** [comment]
Try `sudo node index.js`

**Comment by x38** [comment]
Thanks dude.
