### ISSUE TITLE
How to edit cell speed using windows?

### ISSUE THREAD

**Issue by ZombieMIW** [OgarProject/Ogar#237]
I heard to edit on cell.js but I don't have that folder? where do i download so i can edit

**Comment by tmwilliamlin168** [comment]
You can just find PlayerCell.js and edit inside. Go to line 59, and you should have <code>var speed = Math.min(this.getSpeed(),dist);</code>, the speed variable is set. You can modify that variable to any value you want.

**Comment by Agarian** [comment]
ZombieMIW all you need to do is go into the folder "entity", then open "cell.js" in notepad. Upon doing so, hold "ctrl"+"f". make sure "down" is checked to find the code. paste this line of code.
return 30 * Math.pow(this.mass, -1.0 / 4.5)
Thats it. Change "30" to any number. Try not to go over 200 or else your cell is almost uncontrollable.

**Comment by NatsuTheGreat** [comment]
Are you using the latest Ogar? If so, that is simple found in gameserver.ini. You can search for *playerSpeed = 30* Change the 30 to hatever speed you'd like.

**Comment by Agarian** [comment]
this issue was before that update.

**Comment by NatsuTheGreat** [comment]
Is your issue fixed? Or do you still need help?

By the way, are you usin Ogar-Plus or Ogar?

**Comment by Agarian** [comment]
first off my issue was fixed a while ago. second off i use **both**

**Comment by MastaCoder** [comment]
@vram4 Close request?
