### ISSUE TITLE
Server Refresh?

### ISSUE THREAD

**Issue by LolSmilesxD** [OgarProject/Ogar#243]
I have had a lot of issues with having bots in my server (me obviously wanting them and adding them in the config) but then when I join my game, there is one bot called 'bot1' and he is literally the size of the map. He is constantly growing, and me and no other bots can spawn. I tried installing and reinstalling and it hasn't helped. I was just wondering if there was a way to make the server refresh, causing all the bots and me to restart at the amount of mass put on the config? Thanks. Also, a built-in updater would be nice :P

**Comment by abalabahaha** [comment]
If you're using Linux, [crontabs](http://code.tutsplus.com/tutorials/scheduling-tasks-with-cron-jobs--net-8800)

**Comment by LolSmilesxD** [comment]
I'm not, I'm on Windows.

**Comment by LolSmilesxD** [comment]
How would I set it up anyways?

**Comment by vram4** [comment]
>there is one bot called 'bot1' and he is literally the size of the map. He is constantly growing, and me and no other bots can spawn


The bot grows because other bots and food keep spawning inside of it (they have no where else to spawn if the bot is the size of the map), therefore feeding it. I would recommend increasing the size of the map, increasing mass decay, or reducing the max size of players.
