### ISSUE TITLE
Was Working Two Days Ago, But Not Now

### ISSUE THREAD

**Issue by LolSmilesxD** [OgarProject/Ogar#244]
It was working 2 days ago for me perfectly, but now, I cant move and everyone spawns in the same place. I didnt actually download if from here, but here http://dl.ogarproject.com/binaries/9bec5842ee427207578b9ae25ecc17e5da7179fa/. Anyway, please fix it.

**Comment by JaraLowell** [comment]
Sounds like your using a older client. Or one not compatible with the.. new standard of Agar.io

**Comment by JCookie20001** [comment]
Bump

**Comment by AgarioCheats** [comment]
Or, you changed map borders. Check the default and change it back in gameserver.ini
