### ISSUE TITLE
Node Ogar Command

### ISSUE THREAD

**Issue by higoing00** [OgarProject/Ogar#245]
I think I may be doing this wrong but anyway...

I had already completed the first two steps which was using the git shell and cloning the Ogar Project and downloading the "ws" dependicies. The only part I don't understand is ding the node command.

I reconized that you can't do the node command using npm. But when I do the node.js itself, it gives me this.

Error: Cannot find module 'C:\Users\KDWhite\Documents\GitHub\Ogar\Ogar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by vram4** [comment]
Try changing directory to your Ogar/src directory and then typing `node index.js`.

**Comment by higoing00** [comment]
Close this issue. You didn't write on the instructions that you had to go into the src directory and open up the start .bat
