### ISSUE TITLE
How To Name Bots?

### ISSUE THREAD

**Issue by Orcunegeacar** [OgarProject/Ogar#246]
Is There any code that I can rename bots? (Not Rename Code, I want default names in config)

**Comment by vram4** [comment]
You will have to create a file in the same directory as your config named "botnames.txt". Then add the names one by one. Here is an example: https://github.com/OgarProject/Ogar/blob/master/src/botnames.txt

**Comment by Orcunegeacar** [comment]
@vram4 Thank you so much!
