### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by Maxyfreeze** [OgarProject/Ogar#247]
when i connect to the server it just lags and doesnt let me spawn just goes white or red when i press play i deleted the files and redownloaded them and same thing happened i didnt edit the files the second time

**Comment by vram4** [comment]
Please make sure you are on the [latest](http://dl.ogarproject.com/binaries/9bec5842ee427207578b9ae25ecc17e5da7179fa/) version of the server and are connecting from the official client at http://agar.io
