### ISSUE TITLE
node index.js

### ISSUE THREAD

**Issue by Andrew5545** [OgarProject/Ogar#248]
When I boot up i get this
![whne i bout](https://cloud.githubusercontent.com/assets/13124313/10265084/cbbd85c4-69ef-11e5-8b2e-1359b193ee2a.PNG)

**Comment by vram4** [comment]
You need to install nodejs and its 'ws' module. However, since youre using windows, i would reccomend you use http://dl.ogarproject.com/ instead as you will not need to install anything to run that version.

**Comment by Andrew5545** [comment]
Thank you very much

**Comment by DaFudgeWizzad** [comment]
REQUEST CLOSE
