### ISSUE TITLE
How to put more speed to cell

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#250]
How to put more speed to cell? I need a server like agarabi.com speedy

**Comment by DaFudgeWizzad** [comment]
The formula is in the "Cell.prototype.getSpeed" function.
Make the value higher to increase the speed.

**Comment by Lukkez** [comment]
what i need to change in
Cell.prototype.getSpeed = function() {
    // Old formula: 5 + (20 * (1 - (this.mass/(70+this.mass))));
    // Based on 50ms ticks. If updateMoveEngine interval changes, change 50 to new value
    // (should possibly have a config value for this?)
    return 30 * Math.pow(this.mass, -1.0 / 4.5) * 50 / 40; 
?

**Comment by Lukkez** [comment]
Im not  good at code or configs

**Comment by vram4** [comment]
Change the `30` in `return 30 * Math.pow(this.mass, -1.0 / 4.5) * 50 / 40; ` to a higher number for a faster cell.

**Comment by Lukkez** [comment]
thx

**Comment by DaFudgeWizzad** [comment]
REQUEST CLOSE
