### ISSUE TITLE
how to set acid mode?

### ISSUE THREAD

**Issue by jackmio32** [OgarProject/Ogar#258]
I need to know how to set "setacid(true)" for a gamemode using the console and/or the gameserver.ini file?

in all thanks,
jackmio32

**Comment by vram4** [comment]
Acid mode has to be set client side. When playing agario, in your browser, type `javascript:setAcid(true);` and press enter.

**Comment by jackmio32** [comment]
in address bar?

**Comment by vram4** [comment]
Yes

**Comment by jackmio32** [comment]
thank you!!!!!!!
