### ISSUE TITLE
Please fix auto-generate gameserver.ini file

### ISSUE THREAD

**Issue by Darshil182** [OgarProject/Ogar#259]
I found this problem recently where if you delete the gameserver.ini file by mistake or on purpose the one auto-generated won't work you can't connect to the server at first I thought maybe I changed a value I wasn't supposed to then I auto-generated another one and the same thing happened after I downloaded the ogar server file again got that gameserver.ini replaced it with the old not working and it worked pls dev fix this issue or guide me to what I am supposed to do to fix it.

AND THANK YOU VERY VERY MUCH FOR THIS AWESOME MODE!!!! :)

**Comment by Luka967** [comment]
Have you used some other connection port on your old gameserver.ini? It might be the case.
