### ISSUE TITLE
Players freezing after some time

### ISSUE THREAD

**Issue by benelz** [OgarProject/Ogar#261]
I have players playing in my server, after some time, each player freeze - they are disappeard from Scoreboard and their skin is still shown in map - and the skin is flat, you can't do anything to it (eat it or feed it) sometimes you can feed it though!
PIC:http://prntscr.com/8t2utm
as you can see in the picutre - Satanist, he's not shown in leaderboards and his skin still there, when his screen frozen to death.
Please help.

**Comment by benelz** [comment]
Oh just to add - I've added the *Freeze* fix, yet, not working as it should

**Comment by batbug** [comment]
@benelz what is FREEZE FIX?

**Comment by MastaCoder** [comment]
@vram4 Topic is dead for months now. Close request?
