### ISSUE TITLE
[Resolved] How to change split distance?

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#262]
How to change split distance like: http://agar.io/?ip=vps56296.vps.ovh.ca:443

**Comment by hartsindale** [comment]
Hello, it's the owner of that server

I never really changed split distance, the instant merge setting is -300 to -3000 that's why the distance goes so little.

**Comment by Agarian** [comment]
I think he means when you hit viruses on that server. I want to know how that happens too.

**Comment by Luka967** [comment]
At line 594
```javascript
var splitSpeed = cell.getSpeed() * 6;
```
is determined the speed of split cells. Change the number `6` to some other number.

**Comment by Agarian** [comment]
that doesn't seem to affect when a player hits viruses. what i want to know is how to make it affect player splitting on viruses only please.

**Comment by hartsindale** [comment]
I don't you are talking about my server @Agarian 
My server's cell splitting was demonstrated on Wun Wun's 2nd Private Server Video

The server you are talking about is:
https://www.reddit.com/r/Agario/comments/3py1l1/247_instant_merge_server_lagless/

**Comment by Agarian** [comment]
Either way can you tell me how to make players split on viruses like in the server I was talking about?

**Comment by Luka967** [comment]
Sorry for misunderstanding;
In `entity\Virus.js` line 80:
```javascript
gameServer.newCellVirused(client, consumer, angle, splitMass,20);
```
number `20` represents speed of the splitting cell.

However @hartsindale **only made immediate merging possible**. The cells start at the radius of the splitting cell, and go away from it gradually. Ogar usually tells them *"it's not time to merge still, collide with your cells!"* and does it, but at @hartsindale's server with immediate merging they won't collide.

**Comment by Agarian** [comment]
Thank you! I cannot believe I literally unknowingly skipped over that before LOL.

**Comment by Agarian** [comment]
nothing changed...

**Comment by Agarian** [comment]
actually you gave the incorrect value. It actually was: (client, consumer, angle, splitMass,150). there are apparently two sets. Either way, thank you!

**Comment by Luka967** [comment]
Yeah there is a variable `bigSplits` which determines the amount of big splits included. `(client, consumer, angle, splitMass,150)` is for the tiny, 36 mass ones.

**Comment by Lukkez** [comment]
I put -200 and works... close

**Comment by Agarian** [comment]
what do you set to -200?
