### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by atilaro** [OgarProject/Ogar#264]
i install, and i access my server ip:443 get this message:

update required

**Comment by Darshil182** [comment]
Maybe you didn't install nodejs and the npm websockets or you didn't portfoward well you should watch this tutorial on how to do it properly https://www.youtube.com/watch?v=R_Hro4oH4cI

**Comment by vram4** [comment]
You need to connect to your server with the following url: `agar.io/?ip=[IP]:[PORT]` so if my ip was 127.0.0.1:443, i would connect to it with `agar.io/?ip=127.0.0.1:443`
