### ISSUE TITLE
[Suggestion] Bots

### ISSUE THREAD

**Issue by 20zinnm** [OgarProject/Ogar#265]
What if the bots were actually reduced versions of @Apostolique 's Agar bot (stripped of all graphics-related things and optimized for many)?

**Comment by makmm** [comment]
good idea!

**Comment by Luka967** [comment]
It would use a heckload of processing power, Apostolique's bot will group nearby food together, which is not cost-efficent with a lot of bots.
My suggestion is to just update the bot's minds more times a second.
