### ISSUE TITLE
Problem launching bat file

### ISSUE THREAD

**Issue by TruTriples** [OgarProject/Ogar#266]
I was watching a video on how to install ogar on my computer and i wouldn't be writing here if there was a problem. During the video, he told me to launch the bat file. when he did this it worked fine for him, but when i did it, it said "the system cannot find the path specified." I don't know why it did this. If anyone could help, i would be very happy.

**Comment by vram4** [comment]
The video was outdated, please download the latest version of the server from http://dl.ogarproject.com/
