### ISSUE TITLE
Error: Cannot find module '/Ogar'

### ISSUE THREAD

**Issue by digital-discuss** [OgarProject/Ogar#267]
I get this error after I installed the latest ws with`sudo npm install ws latest --save` (the advised command gave an error) and then trying `node Ogar` when inside the project directory. There were no errors during the installation so I'd think ws did indeed install properly. 

Latest Node in OS X 10.9.5.
```
module.js:339
    throw err;
    ^

Error: Cannot find module '[path-to]/Ogar'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3`
```

**Comment by digital-discuss** [comment]
Indeed I have the "node_modules" folder next to "src" and it does contain "ws".

**Comment by EvanCarroll** [comment]
Do `find .`

If you're outside of `Ogar`you do `node Ogar` (targeting the dirname). In node, targeting a directory means node will read `package.json` for a `main` entry and simply run that. If you're inside the Ogar directory, you'll want to run it manually. 

    pwd # returns /tmp.
    sudo node ./Ogar

or

    pwd # returns /tmp/Ogar
    sudo node ./src/index.js

**Comment by AgarioCheats** [comment]
After npm install ws run:

node index.js
or npm start
or node Ogar.
