### ISSUE TITLE
Can my friends play on my ogarproject private server?

### ISSUE THREAD

**Issue by EWZeiger** [OgarProject/Ogar#269]
So I made my private server and everything works great, I can change game modes, add bots and all that, but am I able to make my server global? I really want to make a private server for just me and my friends. I heard about port forwarding my router, but Im not sure how to do that. Help?

**Comment by EWZeiger** [comment]
My friends are in Canada and Im in the US so the connection can't be local.

**Comment by vram4** [comment]
Yes, you will have to either:
1. Port forward your router to allow people to connect
2. Purchase a dedicated server to run ogar on (this does not require port forwarding)
3. Use hamachi (or similar software) to bypass the port forwarding requirement. All players will need hamachi installed and be in the same group to connect to the server.

**Comment by EWZeiger** [comment]
What do you mean by we have to be in the same group to connect. Is that
something with hamachi? If so I'll probably use that can I get hamachi on a
mac computer? Thanks for your reply.

**Comment by vram4** [comment]
>Is that
something with hamachi?

Yes, when you setup hamachi, create a group in it and have your friends join the group. There is an ip address that hamachi will provide you with. Your friends will have to use that ip as the ip to connect to your server.

**Comment by EWZeiger** [comment]
Oh ok cool. Thank you!
