### ISSUE TITLE
Please help, agar.io server is not working!

### ISSUE THREAD

**Issue by PineapplePuncher** [OgarProject/Ogar#271]

**Comment by vram4** [comment]
Can you explain in greater detail on how its not working?

**Comment by PineapplePuncher** [comment]
Last login: Fri Oct 30 15:16:40 on ttys000
/Users/stevanperrino/Desktop/Ogar-master/src/Start.command ; exit;
Stevans-MacBook-Pro:~ stevanperrino$ /Users/stevanperrino/Desktop/Ogar-master/src/Start.command ; exit;
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/stevanperrino/index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
/Users/stevanperrino/Desktop/Ogar-master/src/Start.command: line 2: pause: command not found
logout

[Process completed]
here sorry for the delay

**Comment by PineapplePuncher** [comment]
I won't get back to you in about 19 hours so please help me a lot my friends and I want to play anyway thank you!

**Comment by JaraLowell** [comment]
node install ws . . . .

**Comment by MastaCoder** [comment]
@vram4 Topic writer dead for months. Close request?
