### ISSUE TITLE
How to access my own ogar server by using a custom domain?

### ISSUE THREAD

**Issue by theniceboy** [OgarProject/Ogar#279]
I followed the instruction and installed Ogar on my CentOS server successfully. But every time when my friends want to play on my server they have to use a google chrome and go to command lines and type 'connect("ws://agar.davidchen.com:443")'. It's not cool, because they think how the things work is you type a domain name (like 'agar.davidchen.com') then you can play the game, just like typing 'agar.io'. Is there any solution to this issue? Thanks!

**Comment by Benny1923** [comment]
Mabye you can try install web sever and put this on your server https://github.com/MJQCPP/agar-clone

**Comment by Benny1923** [comment]
Oh! and remeber configuration the "main_out.js".

**Comment by theniceboy** [comment]
@Benny1923  I think your solution is the right one, but I keep on failing:
     123.57.95.199socket error
    main_out.js:183 Connecting to ws://123.57.95.199:443
    https://cdnjs.org/track/stats.js?id=nocpfkkbaekckhcoekockfbidpcjgkbd&_=1447494342807 Failed to load resource: the server responded with a status of 403 (Forbidden)
    main_out.js:206 socket open
    main_out.js:219 socket close
    main_out.js:142 Find CN-China
    main_out.js:183 Connecting to ws://123.57.95.199:443
    main_out.js:206 socket open
    main_out.js:219 socket close
    main_out.js?542:142 Find CN-China
    main_out.js?542:183 Connecting to ws://123.57.95.199:443
    main_out.js?542:206 socket open
    main_out.js?542:219 socket close
    main_out.js?542:142 Find CN-China
    main_out.js?542:183 Connecting to ws://123.57.95.199:443
    main_out.js?542:206 socket open
    main_out.js?542:219 socket close
    main_out.js?542:142 Find CN-China
    main_out.js?542:183 Connecting to ws://123.57.95.199:443
    main_out.js?542:206 socket open
    main_out.js?542:219 socket close
    .......................

Is there anywhere else I should config beside "var CONNECTION_URL = "123.57.95.199:443";"?

thank you very much!!!

**Comment by Benny1923** [comment]
Only we have change "CONNECTION_URL" and the website should work.
If not work,I think mabye is client not compatibility the server.
I have another solution,type the URL: http://agar.io/?ip=yourip:port

**Comment by theniceboy** [comment]
http://agar.io/?ip=yourip:port @Benny1923  This one works!!!!! Thank you so much!!!!!!!
