### ISSUE TITLE
Problem with cigar cms

### ISSUE THREAD

**Issue by Sansossio** [OgarProject/Ogar#280]
When I try to connect this server to my website (cigarmaster) it gives me error, but if I come from agar.io all goes well, that I can do?
http://prntscr.com/93idc3

**Comment by vram4** [comment]
This server is only compatible with the official agario client at http://agar.io. Any other clients are not supported.

**Comment by Sansossio** [comment]
Ooh thanks

**Comment by Anthony33300** [comment]
Change emulator: http://1drv.ms/1KSyqcR

The linux version needs JX installed, to install that as root run the command "curl http://jxcore.com/xil.sh | bash" minus quotes.
