### ISSUE TITLE
How to deploy Ogar to Heroku?

### ISSUE THREAD

**Issue by SzAmmi** [OgarProject/Ogar#282]
How to deploy Ogar to Heroku? I have an error: the server can't load module 'GameServer.js'.

**Comment by Luka967** [comment]
Any more detailed information on the error?

**Comment by JaraLowell** [comment]
Heroku can have both Node and JS (Depending on the rented service i guess) so it should support it as service but more then that i can not say without a log either.

**Comment by Faris90** [comment]
...........
