### ISSUE TITLE
How to update to use new features

### ISSUE THREAD

**Issue by Gritham** [OgarProject/Ogar#284]
I use Windows Binary to run Ogar, not Node.js. I recently noticed that the gameserver.ini file was updated to include a way to adjust player speed. Will the binary build be updated to include these settings, or can someone make one?

**Comment by jcc10** [comment]
You would have to ask whoever makes / compiles Windows Binary. This is the Node.js version.

(If they base it off of the Node.js version (This thing) then yes, whenever they chose to update, if not then we really have no idea.)

**Comment by MastaCoder** [comment]
@vram4 Topic dead for more then a month. Close request? :D
