### ISSUE TITLE
Question for our next "hacking Ogar" session

### ISSUE THREAD

**Issue by lexoyo** [OgarProject/Ogar#288]
Hello

With @JbIPS and @silexlabs/silex-labs-contributors we organize a ["hacking Ogar" session next week](http://www.silexlabs.org/event/agar-io-hacking-session/).

The goal is to advertise how fun contributing can be, so we will try to hack Ogar with participants. Would you have any advice, or something simple to be done in 1 hour by new comers javascript programmers?

Also I tried to change the value `maxContenders` [here](https://github.com/OgarProject/Ogar/blob/master/src/gamemodes/HungerGames.js#L11) and  [here](https://github.com/OgarProject/Ogar/blob/9bec5842ee427207578b9ae25ecc17e5da7179fa/src/gamemodes/Tournament.js#L20) for a test and it did not have any effect, do you see why?

Thank you for this great hackable version of the game!

**Comment by aaxxo** [comment]
Thats probably because there is a [value](https://github.com/OgarProject/Ogar/blob/master/src/gameserver.ini#L72) set in the gameserver.ini config that will override that value.

    tourneyMaxPlayers = 12

I did not make this btw, just commenting randomly ^-^

**Comment by lexoyo** [comment]
thx that was useful!
