### ISSUE TITLE
Console crashes when playerlist is called twice

### ISSUE THREAD

**Issue by aaxxo** [OgarProject/Ogar#289]
In the console when the command playerlist is called twice, it won't allow any other commands and a restart is needed.  Anyone else having this issue?

**Comment by Agarian** [comment]
It happens with most commands. For example typing just "change" has the same effect. But typing just "kill" makes the console say "please specify a valid player ID! ".

**Comment by aaxxo** [comment]
Seems it messes up when memory is low which isn't really issue with Ogar but my VPS
