### ISSUE TITLE
'npm install ws' fails with ws@0.7.2

### ISSUE THREAD

**Issue by pianophage** [OgarProject/Ogar#291]
I get compilation errors when installing ws. According to [this issue on the ws page](https://github.com/websockets/ws/issues/620), the fix is to update the ws dependency to 0.8.0, which works completely fine for me. (Note: I am using node@4.2.2 and npm@3.5.0. Also note: I am not using the Linux install script but simply doing 'node src/index.js' after 'npm install ws', which works fine after the fix.)

**Comment by EvanCarroll** [comment]
This is also an error I'm getting. Ignoring the "ws" version string in `package.json` gets it through the install.

**Comment by EvanCarroll** [comment]
Pull request: https://github.com/OgarProject/Ogar/pull/359
