### ISSUE TITLE
why

### ISSUE THREAD

**Issue by gustisltugaming** [OgarProject/Ogar#292]
Game] Ogar - An open source Agar.io server implementation
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different

**Comment by BenCat07** [comment]
You need to change the connection Port in the settings or close skype
Am 01.12.2015 19:31 schrieb "gustisltugaming" <notifications@github.com>:

**Comment by JCookie20001** [comment]
This is not a problem with the actual ogar file not working. It's an issue on your end with the ports. Make sure that you setup the ports properly, and make sure your firewall is not blocking the ports.
