### ISSUE TITLE
mothercell not feeding

### ISSUE THREAD

**Issue by MRePotatoes** [OgarProject/Ogar#294]
Why the mother cell is not feeding ?

**Comment by Agarian** [comment]
This is why: when the map has hit the maximum amount of food, mothercells then cannot produce food. To change this, open "gameserver.ini" (not the .js) look for the value "foodMaxAmount" then change 500 to whatever you want.

**Comment by MRePotatoes** [comment]
Fixed

**Comment by Agarian** [comment]
Ok
