### ISSUE TITLE
change splitting?

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#295]
I want to know if there is a way to make splitting in ogar just like the splitting in real vanilla agar.io .

**Comment by xinyuweb** [comment]
this site http://cells.happyfor.me 四区 and 六区, "split" is very good!

**Comment by Agarian** [comment]
nothing to do with the issue BUT
──────────────▄▄▄▄▄▄▄▄▄▄▄▄▄▄
─────────────█▓▓▓▓▓▓▓▓██▓▓▓▓█
────────────█▓▓▓▓▓▓▓▓█──█▓▄▄▓█
───────────█▓▓▓▓▓▓▓▓█───▀█──█▀
──────────█▓▓▓▓▓▓▓▓▓▓█──█────█
─────────█▓▓▓▓▓▓▓▓▓▓▓▓█──█──█
────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█──▀▀
───────▄████████████████▄
───────██▀────────────▀██
───────██──────────────██
──────▄██▄────────────▄██▄
──────████████████████████
─────█────────────────────█
────█──────────────────────█
───█─────▄████▄──▄████▄─────█
───█───██▀────▀██▀────▀██───█
───█──██──▄▄▄──██──▄▄▄─▀██──█
──▄█████──███──██──███──█████▄
──██████──────████──────██████
──▀█▀─▀██▄▄▄███▀▀███▄▄▄██▀─▀█▀
───█────▀▀▀▀▀──────▀▀▀▀▀────█
───█──────▄▄───────▄▄───────█
───█▄──────▀▀▀▀▀▀▀▀▀───────▄█
───█▓█────────────────────█▓█
───█▓▓█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▓▓█
──▄██████████████████████████▄
──██▀──────────────────────▀██
▄█▀──█▄─▄█─█▀▀─█▀█─█▀█─█─█───▀█▄
██▀──█▀█▀█─█▄──█▄▀─█▄▀─█▄█───▀██
██▀──█───█─█▄▄─█─█─█─█─▄▄█───▀██
██▀──────────────────────────▀██
─█─█▀▐─█▐▀█▐─█▀─▀█▀▐▄─▄▌▐▀▌█▀─█
─█─█─▐▄█▐▄▀▐─▀█──█─▐▀█▀▌▐▄▌▀█─█
─█─█▄▐─█▐─█▐─▄█──█─▐───▌▐─▌▄█─█
─█▄▄────────────────────────▄▄█
──▀▀████████████████████████▀▀
────▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
─────▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
──────▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
───────▐▓▓▓▓▓▓▓▌▐▓▓▓▓▓▓▓▌
─────────▐▓▓▓▓▌──▐▓▓▓▓▓▌
────────▄████▀────▀████▄

**Comment by JCookie20001** [comment]
Please do not spam ascii characters in an issue post.
