### ISSUE TITLE
An unusual bug with mothercells:

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#297]
If a mothercell is large and you split around certain parts of it the split cell gets absorbed. A fix? I do not like that bug.

**Comment by JCookie20001** [comment]
What is a mothercell?

**Comment by JCookie20001** [comment]
Also, this is probably a bug with agar.io itself, not ogar.

**Comment by Agarian** [comment]
If you have played agar.io then you should know what mothercells are. The pink-ish viruses that spawn food around them. Found in Gamemode Experimental. And this does not happen in the real agar.io either.

**Comment by JCookie20001** [comment]
They are actually purple viruses. 

Now that I understand, can you please write the original question again,
>If a mothercell is large and you split around certain parts of it the split cell gets absorbed. A fix? I do not like that bug.

👆Is hard to understand what you are trying to say.

**Comment by Agarian** [comment]
In other words, if i have a mothercell that has a lot of mass, and i split next to it, then ogar will act like i split into the mothercell. Because the cell that was split got eaten by the mothercell even when I am not near it. This only happens to mothercells with 5,000 mass and over.

**Comment by NatsuTheGreat** [comment]
Mothercells absorb mass. These are purple viruses that get the mass, and feed it out. I don't think this is a bug...

**Comment by Agarian** [comment]
*facepalm* you don't know what were talking about do you?

**Comment by NatsuTheGreat** [comment]
Explain it better.
