### ISSUE TITLE
My cell won't move!!!

### ISSUE THREAD

**Issue by Jonathan1764** [OgarProject/Ogar#298]
I have done everything it said but yet my cell won't move!

**Comment by Jonathan1764** [comment]
please help

**Comment by xinyuweb** [comment]
your code ,write here!

**Comment by JCookie20001** [comment]
Have you updated your ogar version?

Could you also please include a log of the server.

**Comment by vram4** [comment]
You need the latest version of Ogar. (Can be downloaded from http://dl.ogarproject.com/ )
