### ISSUE TITLE
I cannot connect to my own server.

### ISSUE THREAD

**Issue by JCookie20001** [OgarProject/Ogar#299]
Ok, I Can't connect to my own ogar server.
---------------------------------------------------------------------

- I have port forwarded correctly. (i had ogar a while ago, and a minecraft server - i did the same process it worked fine.)
- I am running the latest version of ogar
- I am connecting from http://agar.io/?ip=(INSERTMYIPHERE):443 and/or http://agar.io/?ip=********.ddns.net
- My ip is static.

I get the same error message when I try to connect (either with local ip, public ip or dynamic dns)
Could I have some help please?
![img_20151211_123333](https://cloud.githubusercontent.com/assets/16248692/11733652/b44485c4-a003-11e5-9a44-b27449ae3de1.jpg)

**Comment by JCookie20001** [comment]
Help?

**Comment by vram4** [comment]
Thats not what the defaut ogar startup screen looks like. It seems like you are using a modded one, which could be the reason why it is not working for you.

**Comment by JCookie20001** [comment]
I got it from this website :/

On 15/12/2015 6:09 AM, vram4 <notifications@github.com> wrote:

Thats not what the defaut ogar startup screen looks like. It seems like you are using a modded one, which could be the reason why it is not working for you.

**Comment by JCookie20001** [comment]
I will re-download it and see what happens later.

**Comment by JCookie20001** [comment]
It worked :bento: :smiley:
