### ISSUE TITLE
Splitting Crashes The Server On Win.64

### ISSUE THREAD

**Issue by amazingty** [OgarProject/Ogar#302]
hey there ! im a noob so please be a lil patient with me

the server is running like a charm got working on hamachi for now, 
but everytime my friend gains to much cells lets say over 20 000 or so and he splitts or get hit by a virus he disconnects from the server, i saw another post about this issue but it was for .js files i think i got the windows version just the .ini file in the folder,

any easy way on fixing it ? please reply

**Comment by Agarian** [comment]
I am not sure what would cause that problem. Either the code was tampered with or you need to get the latest version.
