### ISSUE TITLE
How to make the food grow.

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarProject/Ogar#309]
I really need help with making the food grow. 

I wish it to be like after a minute all the pellets grow to 2 mass and so on (if not eaten of course) 

Agar.io has this feature and it's REALLY nice.

**Comment by mrmarktyy** [comment]
please see my comment in #312

**Comment by NatsuTheGreat** [comment]
@mrmarktyy Hey man it's really nice, but I didn't really understand the timer.. How do I create that?

And for the second method, do I copy the virusCheck and edit somethings? I will need help with that too :/

**Comment by mrmarktyy** [comment]
@NatsuTheGreat just made a PR for this feature (#333)
give it a shot and let me know how it goes.
