### ISSUE TITLE
smooth render ?

### ISSUE THREAD

**Issue by matrixreal** [OgarProject/Ogar#310]
Hi,
since the game freezing a lot i decided to use smooth render ...
how to set it by default ?
or what's the js call to smooth render ?
thank you

**Comment by matrixreal** [comment]
found it
setSmooth();

**Comment by genckaptan55** [comment]
Where exactly we must put this code and does it work as you want?

**Comment by matrixreal** [comment]
anyway ... this will prevent some lagg but you will have bad image quality

**Comment by Agarian** [comment]
@matrixreal Where is the line of code found?

**Comment by matrixreal** [comment]
@Agarian 
execute this javascript call in the main index.html or index.js

**Comment by Agarian** [comment]
none of the ogar js files have that line of code. where did index.html come from?

**Comment by Agarian** [comment]
where EXACTLY is the code and how do i get to it?

**Comment by AgarioCheats** [comment]
@Agarian  This must be the client's functionality, you need to press inspect element on chrome on your button to enable smooth render, find the value in javascript, and erase/change something there to make it enabled always.

**Comment by Agarian** [comment]
i couldn't find it.

**Comment by matrixreal** [comment]
@Agarian 
add this to your index.html or game.hbs before the </body>
<script type="text/javascript">
setSmooth(.4);
</script>

**Comment by Agarian** [comment]
it didnt do anything

**Comment by Agarian** [comment]
i search it up says "0 of 0"

**Comment by Agarian** [comment]
didnt work

**Comment by Agarian** [comment]
does nothing.

**Comment by fodse** [comment]
- a
