### ISSUE TITLE
TELL US HOW TO CREATE THE EFFECT OF FOOD GROWTH!

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#312]
PLEASE? also answer issues #307, #309, and #311 as they ask the same thing.

**Comment by JCookie20001** [comment]
Writing a title in capital letters isn't helpful. Also, if there is another issue about the exact same thing; don't ask the question again.

**Comment by Agarian** [comment]
That doesn't help the situation.

**Comment by Agarian** [comment]
i give up

**Comment by mrmarktyy** [comment]
@Agarian you can simply setup a timer to increase food mass in Food.js but this would cause potential performance issue (simplest way to code but cpu consuming)

On the other hand, what you can do is, give each food entity a born timestamp. and setup a `foodCheck` method like `virusCheck` in GameServer.js, which loops through all food entities and will increase food mass if certain condition matches (eg, current timestamp > food born timestamp + 2min)

With such mechanism, you can do a lot more just with imagination. Good luck.

**Comment by Lukkez** [comment]
How to setup this?, i not good at codes

**Comment by Agarian** [comment]
@Lukkez just download the latest version of ogar. vram4 added it from a pull request.

**Comment by Lukkez** [comment]
Yeah, i downloaded =P
