### ISSUE TITLE
collision of ejected mass?

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#314]
i want to know how to do that.

**Comment by NatsuTheGreat** [comment]
I know, the piling up on each other is annoying.. I am trying my best I can to fix this.

**Comment by Agarian** [comment]
so there's no fix currently?

**Comment by NatsuTheGreat** [comment]
Someone has done it, he knows how to. If you use Reddit, /u/HelpMeGetALife , he knows how to do it, tell me if he responds.

**Comment by Agarian** [comment]
OK I commented so I hope he responds.

**Comment by Agarian** [comment]
/u/HelpMeGetALife (Not Responding)

**Comment by mrmarktyy** [comment]
interesting to know how it's done. +1
