### ISSUE TITLE
coding help? (read 4 more info)

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#325]
I have tried looking for a line of code that edits the speed of the splitting cell. And I want to edit it in a way that resembled splitting of vanilla agar.io, anyone help? I have also wanted to code other parts of the server to resemble vanilla agar.io and someone on reddit has done it. His reddit name is: 
*/u/Helpmegetalife* 
and his server post is here: *https://www.reddit.com/r/Agario/comments/3vz18o/agario_ffa_server_with_miniclips_skins/*. 
This server is the closest to vanilla agar.io i may ever get if it happens to me at all. If you have any lines of code to make an ogar server as close to vanilla agar.io as possible, then tell me **please**.

**Comment by rsajeey** [comment]
If you don't know, how to use OgarProject/Ogar then stay away from it.

**Comment by mrmarktyy** [comment]
looks really good.

**Comment by Agarian** [comment]
@rsajeey your comment has nothing to do with the topic. I want code that gets me as close to vanilla agar.io as possible. **read the comment before commenting on it next time please, and if your not gonna help then stay away from it**

**Comment by rsajeey** [comment]
@Agarian, again. If you don't know how to use OgarProject/Ogar, then stay away from it.
