### ISSUE TITLE
Virus explosions

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarProject/Ogar#343]
Any idea from anyone on how to adjust the virus explosions and not make all the big splits and num splits come out of one place, it's a little weird. what I wanted is to make it so that the splits (big and num) go *all around the cell*.

Please and thanks.

**Comment by Ogarunite** [comment]
Agreed. in search of this too.

**Comment by Dogeyy** [comment]
/u/Helpmegetalife has a server that has something like this, maybe if he could give out the code or help us a bit we could add it to Ogar.

**Comment by NatsuTheGreat** [comment]
@Dogeyy I have asked...

**Comment by Agarian** [comment]
same
