### ISSUE TITLE
anyone know how to create the collision of ejected mass? (repost)(resolved)

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#345]
any idea on how to code ejected mass to collide?? this time stay on topic ***please?***

**Comment by AgarioCheats** [comment]
Collision of ejected mass, you mean so that they will collide with each other, and push each other instead of previously laying on top of each other?

**Comment by Agarian** [comment]
yes

**Comment by retslac** [comment]
I got the ejected mass collision working.  Will post code changes in a couple of days if you're still interested.

**Comment by AgarioCheats** [comment]
Interested :)

**Comment by DaFudgeWizzad** [comment]
@retslac I would like to see how this was done as well.

**Comment by retslac** [comment]
ok, here are the 5 changes i made to get the ejected mass collision to work.

###### 1. Replaced function calcMovePhys in Cell.js

```javascript
Cell.prototype.calcMovePhys = function(config) {
    // Movement engine (non player controlled movement)
    var speed = this.moveEngineSpeed;
    var r = this.getSize();
    this.moveEngineSpeed *= this.moveDecay; // Decaying speed
    this.moveEngineTicks--;

    // Calculate new position
    var sin = Math.sin(this.angle);
    var cos = Math.cos(this.angle);
    if (this.cellType == 3) {
        //movement and collision check for ejected mass cells
        var collisionDist = r * 2 - 5; // Minimum distance between the 2 cells (allow cells to go a little inside eachother before moving them)
        var maxTravel = r; //check inbetween places for collisions (is needed when cell still has high speed) - max inbetween move before next collision check is cell radius
        var totTravel = 0;
        var xd = 0;
        var yd = 0;
        do {
            totTravel = Math.min(totTravel + maxTravel, speed);
            var x1 = this.position.x + (totTravel * sin) + xd;
            var y1 = this.position.y + (totTravel * cos) + yd;
            for (var i = 0; i < this.gameServer.nodesEjected.length; i++) {
                var cell = this.gameServer.nodesEjected[i];
                if (this.nodeId == cell.nodeId) {
                    continue;
                }
                if (!this.simpleCollide(x1,y1,cell,collisionDist)) {
                    continue;
                }
                var dist = this.getDist(x1,y1,cell.position.x,cell.position.y);
                if (dist < collisionDist) { // Collided
                    var newDeltaY = cell.position.y - y1;
                    var newDeltaX = cell.position.x - x1;
                    var newAngle = Math.atan2(newDeltaX,newDeltaY);
                    var move = (collisionDist - dist + 5) / 2; //move cells each halfway until they touch
                    xmove = move * Math.sin(newAngle);
                    ymove = move * Math.cos(newAngle);
                    cell.position.x += xmove >> 0;
                    cell.position.y += ymove >> 0;
                    xd += -xmove;
                    yd += -ymove;
                    if (cell.moveEngineTicks == 0) {
                        cell.setMoveEngineData(0, 1); //make sure a collided cell checks again for collisions with other cells
                        if (this.gameServer.movingNodes.indexOf(cell) == -1) {
                            this.gameServer.setAsMovingNode(cell);
                        }
                    }
                    if (this.moveEngineTicks == 0) {
                        this.setMoveEngineData(0, 1); //make sure a collided cell checks again for collisions with other cells
                    }
                }
            }
        }
        while (totTravel < speed);
        x1 = this.position.x + (speed * sin) + xd;
        y1 = this.position.y + (speed * cos) + yd;
    } else {
        //movement for other than ejected mass cells (player split, virus shoot, ...)
        var x1 = this.position.x + (speed * sin);
        var y1 = this.position.y + (speed * cos);
    }

    // Border check - Bouncy physics
    var radius = 40;
    if ((x1 - radius) < config.borderLeft) {
        // Flip angle horizontally - Left side
        this.angle = 6.28 - this.angle;
        x1 = config.borderLeft + radius;
    }
    if ((x1 + radius) > config.borderRight) {
        // Flip angle horizontally - Right side
        this.angle = 6.28 - this.angle;
        x1 = config.borderRight - radius;
    }
    if ((y1 - radius) < config.borderTop) {
        // Flip angle vertically - Top side
        this.angle = (this.angle <= 3.14) ? 3.14 - this.angle : 9.42 - this.angle;
        y1 = config.borderTop + radius;
    }
    if ((y1 + radius) > config.borderBottom) {
        // Flip angle vertically - Bottom side
        this.angle = (this.angle <= 3.14) ? 3.14 - this.angle : 9.42 - this.angle;
        y1 = config.borderBottom - radius;
    }

    // Set position
    this.position.x = x1 >> 0;
    this.position.y = y1 >> 0;
};
```

###### 2. Added these 3 functions in Cell.js (just add them them at the end of the file)

```javascript
Cell.prototype.simpleCollide = function(x1,y1,check,d) {
    // Simple collision check
    var len = d >> 0; // Width of cell + width of the box (Int)

    return (this.abs(x1 - check.position.x) < len) &&
           (this.abs(y1 - check.position.y) < len);
};

Cell.prototype.abs = function(x) {
    return x < 0 ? -x : x;
};

Cell.prototype.getDist = function(x1, y1, x2, y2) {
    var xs = x2 - x1;
    xs = xs * xs;

    var ys = y2 - y1;
    ys = ys * ys;

    return Math.sqrt(xs + ys);
};
```

###### 3. Replaced moveDone function and added onAdd function in EjectedMass.js

```javascript
EjectedMass.prototype.moveDone = function(gameServer) {
    this.onAutoMove(gameServer);
};

EjectedMass.prototype.onAdd = function(gameServer) {
    gameServer.nodesEjected.push(this);
};
```

###### 4. Changed ejectMass function in GameServer.js:
the line of code that creates the ejected cell needs an extra parameter "this" at the end:

```javascript
var ejected = new Entity.EjectedMass(this.getNextNodeId(), null, startPos, this.config.ejectMass, this);
```

###### 5. Ejected mass collision should already work by now, but to be complete i did change two other things:

- to avoid spawning new players from ejected cells that are still moving i added an if condition in function onPlayerSpawn in FFA.js:
```javascript
            var e = gameServer.nodesEjected[index];

            if (e.moveEngineTicks == 0) {
                // Remove ejected mass
                gameServer.removeNode(e);

                // Inherit
                pos = {x: e.position.x, y: e.position.y};
                startMass = e.mass;

                var color = e.getColor();
                player.setColor({
                    'r': color.r,
                    'g': color.g,
                    'b': color.b
                });
            }
```

- to avoid eating ejected cells right after shooting them at higher playerSpeeds i changed startposition in ejectMass function in GameServer.js
```javascript
        var size = cell.getSize() + cell.getSpeed() + 5; //add speed of playercell
        var startPos = {
            x: cell.position.x + (size * Math.sin(angle)),
            y: cell.position.y + (size * Math.cos(angle))
        };
```


That's it i think!  Hope i didn't forget anything.  Enjoy, and let me know if it works ok for you.

**Comment by DaFudgeWizzad** [comment]
It does work! I forgot to add 'this' into the ejectMass function and to call the abs prototype :P

**Comment by NatsuTheGreat** [comment]
You are the best man, I am literally not even kidding.

**Comment by MastaCoder** [comment]
This is amazing! I am going to be taking most of this information that people are releasing here and forming one big OgarProject built by the community that is more like Agar.io. So far I got the split, w's moving in different directions done. This is just one more part to what I needed! The last part I need is the virus splitting :/

**Comment by NatsuTheGreat** [comment]
I can help.

**Comment by Agarian** [comment]
server crash with error

**Comment by NatsuTheGreat** [comment]
What error?

**Comment by Agarian** [comment]
nvm i fixed it

**Comment by Agarian** [comment]
@retslac U THE MAN!

**Comment by mrmarktyy** [comment]
awesome work @retslac  thanks !

**Comment by retslac** [comment]
glad i could help

@Agarian nice artwork there.  Can see you're enjoying it already.

**Comment by Agarian** [comment]
VERY MUCH ENJOYING

**Comment by Agarian** [comment]
can you make splitting on viruses like on regular agar? that would be amazing

**Comment by AgarioCheats** [comment]
Everything would be amazing .D

**Comment by MastaCoder** [comment]
@Agarian Close this if you don't need it anymore :)

@vram Close request?

**Comment by Lukkez** [comment]
I have error with FFA:
});
 ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Lucas\Desktop\Jogos\COISAS\src\gamemodes\index.js:3:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by Lukkez** [comment]
If i put do this error, i resolved with 0 chance to spawn player of ejected mass.... @Agarian how you resolved your error?
            if (e.moveEngineTicks == 0) {

**Comment by Agarian** [comment]
i put a line of code in the wrong area

**Comment by retslac** [comment]
You probably forgot to close the if condition with the closing bracket } at the end.

The extra condition is just there to avoid spawning from moving nodes.  You can still spawn from ejected cells that have stopped moving.

Here's the whole function as it should be.  Have fun...

```javascript
FFA.prototype.onPlayerSpawn = function(gameServer,player) {
    // Random color
    player.color = gameServer.getRandomColor();
    
    // Set up variables
    var pos, startMass;
    
    // Check if there are ejected mass in the world.
    if (gameServer.nodesEjected.length > 0) {
        var index = Math.floor(Math.random() * 100) + 1;
        if (index <= gameServer.config.ejectSpawnPlayer) {
            // Get ejected cell
            var index = Math.floor(Math.random() * gameServer.nodesEjected.length);
            var e = gameServer.nodesEjected[index];

            if (e.moveEngineTicks == 0) {
                // Remove ejected mass
                gameServer.removeNode(e);

                // Inherit
                pos = {x: e.position.x, y: e.position.y};
                startMass = e.mass;

                var color = e.getColor();
                player.setColor({
                    'r': color.r,
                    'g': color.g,
                    'b': color.b
                });
            }
        }
    }
    
    // Spawn player
    gameServer.spawnPlayer(player,pos,startMass);
};
```

**Comment by Lukkez** [comment]
Thx now works

**Comment by NatsuTheGreat** [comment]
@retslac Can you please tell me how make the bigger cells push harder against smaller cells? I am working on virus collision and I need that for it to probably work.

**Comment by Agarian** [comment]
Small cells push the larger cells. Solution -> Prioritize larger cells when splitting, and eventually the smaller ones afterwards?

**Comment by Agarian** [comment]
@retslac would you happen to know how to get smooth split physics like in  http://agar.io/?ip=parisgamma.iomods.com:1501

**Comment by retslac** [comment]
I finished the code for smooth physics, smooth collision, big cells pushing harder against small cells, virus splitting, etc.  It's a bunch of new features and code changes working together.  Was planning on gathering all changes later today and posting them on issue #349 where it belongs.

@Agarian I got my own smooth physics, which i think looks a lot like cell splitting on that site.  I've seen the site before, but I don't know how cells split on viruses on that site.  Also can't test it here at my current location to see how it works.  Maybe when i get back home I can test it.  Can you tell me what's so specific on virus splitting on that site?  For now i created my own smooth virus splitting, but maybe if they've got something that looks better i could try to code that...?

**Comment by NatsuTheGreat** [comment]
@vram4 Close please. xP

**Comment by Agarian** [comment]
@retslac Original ogar virus split:
![virusogar](https://cloud.githubusercontent.com/assets/15255724/12531117/37f13e2e-c1c1-11e5-9204-8256db151728.jpg)

Virus split on the site/server http://agar.io/?ip=parisgamma.iomods.com:1501:
![virussplitsite](https://cloud.githubusercontent.com/assets/15255724/12531135/8bc1d52c-c1c1-11e5-99d0-8cbac103968a.jpg)

**Comment by retslac** [comment]
Do you want the little split cells to go in random directions instead of evenly distributed around the origin cell or is it something else?

**Comment by Agarian** [comment]
i would like the little split cells to go in random directions instead of evenly distributed around the origin. i like the virus splitting on the parisgamma site.

**Comment by Agarian** [comment]
i think i have done that before with splitmass in virus.js with a math.random function

**Comment by retslac** [comment]
Just change the angle of the numsplits.  You don't need to change anything about the mass.

for evenly distributed little cells use:
```javascript
angle += 6.28/numSplits;
```

for random directions use:
```javascript
angle = Math.random() * 6.28;
```

I think i'm also gonna use the random angle.  It looks good!

**Comment by Agarian** [comment]
would you happen to know a way to add miniclip skins into ogar?

**Comment by Agarian** [comment]
have you tried PRs (Pull Requests)?

**Comment by retslac** [comment]
As far as i know skins are client side only.  I don't think it's possible without client side changes.
You could install something like agario-powerups or something similar.

**Comment by Agarian** [comment]
i have done that

**Comment by NatsuTheGreat** [comment]
@retslac Do you know how to make the explosions same size under 300 mass?

**Comment by retslac** [comment]
@NatsuTheGreat I'll see and let you know tomorrow.  Haven't got time today.

**Comment by NatsuTheGreat** [comment]
@retslac Alright.

**Comment by retslac** [comment]
@NatsuTheGreat  Took a quick look at it.  I guess you're looking after something like this.

```javascript
    // Cell consumes mass before splitting
    consumer.addMass(this.mass);

    var maxSplits = Math.floor(consumer.mass/16) - 1; // Maximum amount of splits
    var numSplits = gameServer.config.playerMaxCells - client.cells.length; // Get number of splits
    numSplits = Math.min(numSplits,maxSplits);
    var splitMass = Math.min(consumer.mass/(numSplits + 1), 36); // Maximum size of new splits
```

Just put the "consumer.addMass" BEFORE calculating the numSplits and the splitMass instead of after.  This should make all cells (including the origin cell) about the same size when cell mass <= 576.

**Comment by NatsuTheGreat** [comment]
Thanks man! It worked.
