### ISSUE TITLE
In GameServer.js, what does setTimeout do

### ISSUE THREAD

**Issue by mrmarktyy** [OgarProject/Ogar#355]
I see there're lines of code like this,

```
setTimeout(this.cellTick(), 0);
```

I wonder what does this `setTimeout` do here, and did it mean to be like this?

```
setTimeout(this.cellTick.bind(this), 0);
```

Thank you

**Comment by Agarian** [comment]
i believe that references *foodMassTimeout* in gameserver.ini which controls how much time (in seconds) a food pellot takes to grow by 1 mass.

**Comment by vram4** [comment]
This causes the game server to execute the function that updates all the cells.
