### ISSUE TITLE
How to prevent the Ogar Bots from suiciding into people randomly.

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarProject/Ogar#356]
How do I prevent this? It makes the game no fun. :(

**Comment by Agarian** [comment]
its in gameserver.ini as serverScrambleCoords
set it to 1 to activate it (prevents minions from working properly)
set it to 0 to deactivate it.

**Comment by NatsuTheGreat** [comment]
That is not what I am talking about man... I mean the player bots, with the BOT IP, that you add with serverBots in gameserver.ini or your console

**Comment by retslac** [comment]
@NatsuTheGreat I know what you mean.  Was already planning on making the bots a lot better.  Got many ideas for improvement, but little time to work on this.  If I can get something good working, i'll post it here.  But don't expect it anytime for the next couple of weeks.

**Comment by NatsuTheGreat** [comment]
@retslac alright man
