### ISSUE TITLE
Smoother Physics

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#362]
Plz someone help... i'm making a modded Ogar private and i need Smooth Physics like: http://agar.io/?ip=parisgamma.iomods.com:1501

**Comment by AgarioCheats** [comment]
You've already opened an issue before containing the exact same question formulated with different words.

**Comment by Lukkez** [comment]
But none help

**Comment by Lukkez** [comment]
I solved: go to line 621 on gameserv.js change
        var splitSpeed = cell.getSpeed() * 6;
to a number like
        var splitSpeed = cell.getSpeed() * 3;
:)

**Comment by MastaCoder** [comment]
Well that probably means we really can't? :D

**Comment by Ogarunite** [comment]
I'd honestly help you if I could. I spent a couple hours getting a ltitle bit of a smooth split to work, though it's far from perfect.

You can check it out under the "Collision" issue.
