### ISSUE TITLE
W Collison

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#367]
How to make w collide?

**Comment by ItzLevvie** [comment]
Don't create duplicate issues.

**Comment by Lukkez** [comment]
0 Person helped

**Comment by vram4** [comment]
They don't help either because they don't know or they are not interested in sharing. Making additional issues doesn't help at all and only clogs up the issue tracker.

**Comment by AgarioCheats** [comment]
What do you mean with W collide?

**Comment by Lukkez** [comment]
@AgarioCheats see this server: http://agar.io/?ip=parisgamma.iomods.com:1501

**Comment by AgarioCheats** [comment]
I've seen it, but i don't understand what is W collide?

**Comment by Ephemerality** [comment]
He wants ejected mass to collide.

**Comment by AgarioCheats** [comment]
What does ejected mass to colide, mean??? So the W you eject, collides with other mass you have ejected? That wouldn't make sense? Would be like ice-hockey...

**Comment by Ephemerality** [comment]
Probably why no one has helped him with it.
