### ISSUE TITLE
[Request]Leaderboard for gameserver.ini

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#369]
As it does for the leaderboard change from 10 to 15 or 5 etc , without having to go in the game mode code , put in gameserver.ini to help achieve , I have some friends who like change and they do not like having to go the code

**Comment by MastaCoder** [comment]
You mean change the number of players the leaderboard shows?

**Comment by Lukkez** [comment]
Yea

**Comment by Agarian** [comment]
interested to know how it's done :+1:

**Comment by Andrews54757** [comment]
change the file FFA.js in the game modes folder and change the numbers in this area

```
 } else if (lb.length < 10) {
            this.leaderboardAddSort(player,lb);
        } else {
            // 10 in leaderboard already
            if (playerScore > lb[9].getScore(false)) {
                lb.pop();
                this.leaderboardAddSort(player,lb);
            }
```

**Comment by Andrews54757** [comment]
for example (if you want 15 people)

```
 } else if (lb.length < 15) {
            this.leaderboardAddSort(player,lb);
        } else {
            // 15 in leaderboard already
            if (playerScore > lb[14].getScore(false)) {
                lb.pop();
                this.leaderboardAddSort(player,lb);
            }
```

**Comment by Andrews54757** [comment]
I shall add this feature in my fork

**Comment by Andrews54757** [comment]
I did it and now you can go to the gameserver.ini file and set ffaMaxLB to any number in [my fork] (https://github.com/Andrews54757/Andrews-version-of-Ogar-more-features-commands-gamemodes-opmode) of ogar

**Comment by ItzLevvie** [comment]
Close? @vram4.
