### ISSUE TITLE
Skype Problem Plz Help

### ISSUE THREAD

**Issue by Grantapus** [OgarProject/Ogar#371]
Hello all! im on linux(linux mint) and i wanted to make a agar.io private server. so i downloaded Ogar master, un ziped it, and than open the term. So i installed nodejs, (sudo apt-get install nodejs)
and than installed the WS thing( sudo apt-get install ws) than i did(cd Desktop)

than i did (sudo nodejs Ogar-master) than i typed my pass. than it came with  a error that says( please close out of Skype, or change you server port) First, i dont even have Skype, and second, what hpuld i change the server port too?

**Comment by MastaCoder** [comment]
Edit the gameserver.ini file in the Ogar folder and change the ServerPort at the top from 443 to 444 or anything else that is not closed or used.

**Comment by Grantapus** [comment]
Okay! i'll try!

**Comment by Grantapus** [comment]
Okay, it worked, but when i edit the gameserver.ini(change starting mass,etc) , it does not work any more! Pls help again!

**Comment by Agarian** [comment]
i have had that issue as well. the way i fixed it was by giving it line breaks. just copy this:

// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// serverStatsPort: Port for the stats server. Having a negative number will disable the stats server.
// serverStatsUpdate: Amount of seconds per update for server stats
// serverLogLevel: Logging level of the server. 0 = No logs, 1 = Logs the console, 2 = Logs console and ip connections
// serverScrambleCoords: Toggles scrambling of coordinates. 0 = No scrambling, 1 = scrambling. Default is 1.
serverMaxConnections = 64
serverPort = 443
serverGamemode = 0
serverBots = 0
serverViewBaseX = 1024
serverViewBaseY = 592
serverStatsPort = 88
serverStatsUpdate = 60
serverLogLevel = 1
serverScrambleCoords = 1

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 500
foodMass = 1
foodMassGrow = 1
foodMassGrowPossiblity = 50
foodMassLimit = 5
foodMassTimeout = 120
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusFeedAmount = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassCooldown: Time until a player can eject mass again (ms)
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassCooldown = 200
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur
// playerDisconnectTime: The amount of seconds it takes for a player cell to be removed after disconnection (If set to -1, cells are never removed)
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15
playerSpeed = 30
playerDisconnectTime = 60

// [Gamemode]
// Custom gamemode settings
// tourneyTimeLimit: Time limit of the game, in minutes.
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyTimeLimit = 20
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by vram4** [comment]
Or you can use a real text editor like notepad++ that will properly show linux line breaks.

**Comment by MastaCoder** [comment]
+1

**Comment by Grantapus** [comment]
Okay, i will try, and plz tell what a "line break" is? (i think i have a
idea)

**Comment by Agarian** [comment]
a line break is like this:

    line 1
    line 2

in other words if you press enter, you made a line break.
