### ISSUE TITLE
Collision on viruses

### ISSUE THREAD

**Issue by MastaCoder** [OgarProject/Ogar#373]
Has anyone tried this out yet?

When a player hits a virus instead of sending little cells around the big one, have all the cells the same size if the player was under 500 - 1000 mass?

I've tried messing with the onConsume function in virus.js, but nothing I try seems to work. Anyone can assist me on this?

**Comment by MastaCoder** [comment]
https://gyazo.com/fe4a7a9fae690ce878f3ec46853bda71

We are messing around with a bit more. If anyone has any suggestions and can help us more with this, it'd be great! :+1:

**Comment by NatsuTheGreat** [comment]
That is great man! How did you do that?

**Comment by MastaCoder** [comment]
Messed a bit with the onConsume command in entity/virus.js. Still needs a lot of more work because it's a bit glitched down at 300 mass. I am working on it though ;D

**Comment by NatsuTheGreat** [comment]
What did you do though? Can I get the code? xP

**Comment by MastaCoder** [comment]
Nevermind I think I got it. It's just a bit buggy, If you want to see it: http://abs0rb,me

I am still debating if I will release this, most likely might not. But who knows? :dancer:

**Comment by NatsuTheGreat** [comment]
Aww c'mon man :(

**Comment by MastaCoder** [comment]
I would release it, just the person I got most of the code from doesn't want it to be released, yet.

**Comment by Ogarunite** [comment]
Who here is running Elites.io? I liked the menorah.

**Comment by Agarian** [comment]
ffs just release it

**Comment by MastaCoder** [comment]
The issue is the guy I got some of the information from doesn't want to release it, yet.
