### ISSUE TITLE
disable smooth render in agar?

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#375]
you know how then you hit a certain size ant the graphics become smooth and you can no longer see cell borders? any way to disable it?

**Comment by BielSAA** [comment]
Its not possible by modifying the server, only the client.

**Comment by Agarian** [comment]
I know that part. Also I said agar not ogar.

**Comment by BielSAA** [comment]
In this forum we can't help with custom clients, thats agains the rules, sorry

**Comment by MastaCoder** [comment]
@vram4 Close request?
