### ISSUE TITLE
Colors + Splitting

### ISSUE THREAD

**Issue by elitajmx** [OgarProject/Ogar#378]
How do i modify the splitting to go more smoothly u kno what i mean? like in real agar.io
plus the colors, i want normal colors not this shit.

**Comment by Agarian** [comment]
see #349

**Comment by elitajmx** [comment]
okay but where exactly do iput that splitignorecollision=true
?

**Comment by Agarian** [comment]
scroll farther down

**Comment by Agarian** [comment]
much farther down

**Comment by elitajmx** [comment]
agarian do u have smooth splitting for yourself? like real agario splitting

**Comment by elitajmx** [comment]
if u do let me get your skype and u send me files k? thanks if u do

**Comment by Agarian** [comment]
https://www.mediafire.com/?lkdm7373k931v00 files are here

**Comment by Agarian** [comment]
https://www.mediafire.com/?lkdm7373k931v00 files are here.

**Comment by elitajmx** [comment]
Omg ty dude, also can u tell me why skins wont work?

**Comment by elitajmx** [comment]
THANK YOU SO MUCH MAN I LUV U, I EVEN TRRICKSPLITTED WITH MY FRIEND XD

**Comment by Agarian** [comment]
also idk why some skins don't work :\

**Comment by elitajmx** [comment]
agarian why cant i let my freind join he cant join

**Comment by ItzLevvie** [comment]
@elitajmx @Agarian http://goo.gl/Ao0jz5 xD

**Comment by Agarian** [comment]
i see u like the tyt bait name i made lol

**Comment by Agarian** [comment]
@ItzLevvie is that your minion? or a friend you got to join? if its someone u got to join then HOW U DID IT?

**Comment by ItzLevvie** [comment]
@Agarian minion

**Comment by Agarian** [comment]
you know if you get browsec then those minions work on reg. servers

**Comment by ItzLevvie** [comment]
@Agarian I know. :P

**Comment by NatsuTheGreat** [comment]
@vram4 Can you close this?

**Comment by elitajmx** [comment]
oi natsu why close ? is something wrong here
