### ISSUE TITLE
WHEN IS SPLITTING BEING FIXED?

### ISSUE THREAD

**Issue by elitajmx** [OgarProject/Ogar#380]
When is splitting being fixed please tell me
is it going to be fixed or no

Thanks :)

**Comment by Agarian** [comment]
please do not create a duplicate to another open issue.

**Comment by MastaCoder** [comment]
We can't just say. it will be up to someone in the community or part of the developers to make a fix for something. All you and we can do is wait.

**Comment by elitajmx** [comment]
ok

**Comment by AgarioCheats** [comment]
@MastaCoder Come on, you know it's already been provided by retslac. Why be greedy. The code is for us all to share. Elitajmx, read here: https://github.com/OgarProject/Ogar/issues/349 (Scroll all the way down and start reading upwards from there).

**Comment by MastaCoder** [comment]
@AgarioCheats I never said it hasn't been done. @elitajmx meant something as in the split to be perfected and when it will be added to Ogar. The current code that was provided in the other post, is great, but it's not perfect. I thought @elitajmx wanted something perfect. No hate :3

**Comment by elitajmx** [comment]
mastacoder do u have your server? like port forwarede

**Comment by MastaCoder** [comment]
Yes. Why?

**Comment by NatsuTheGreat** [comment]
@vram4 Close?

**Comment by elitajmx** [comment]
mastacoder could i join it? and my frined
