### ISSUE TITLE
who has a server port forwarded?

### ISSUE THREAD

**Issue by elitajmx** [OgarProject/Ogar#383]
if you have the server port forwarded can i please join ? ;)

**Comment by MastaCoder** [comment]
There are many servers on the http://reddit.com/r/agario. Here's a good list if you want: https://www.reddit.com/r/Agario/comments/3oc79z/list_of_private_servers/

**Comment by elitajmx** [comment]
yeah but i want this new smooth splitting i have now and i want to play with 1 friend only

**Comment by elitajmx** [comment]
and also most of those servers wont work

**Comment by MastaCoder** [comment]
http://agarserv.com

**Comment by jollesnaas** [comment]
You can rent a VPS (Windows or Linux) of me: 4 euro/month/512MB RAM or 8 euro/month/1GB RAM, 20 euro/Year/512MB RAM or 40 euro/year/1GB RAM.

If you want to know more or order, please contact me on skype: jolle.snaas
*Free test included! 

You can create your own server on this!

**Comment by Andrews54757** [comment]
i dont trust this . dont fall for it others! Only give money to trusted people
