### ISSUE TITLE
Instant merge help plss

### ISSUE THREAD

**Issue by KyraCloud** [OgarProject/Ogar#392]
i need help how do i do instant merge?

**Comment by ItzLevvie** [comment]
Change "playerRecombineTime = 30" in gameserver.ini to "playerRecombineTime = -1000".

**Comment by Luka967** [comment]
Set it to `0`. It'll automatically merge it - PlayerCell.js line 45
```javascript
if (base == 0) {
        r = true;
```

**Comment by KyraCloud** [comment]
Thx guys
