### ISSUE TITLE
any possible way for ogar to read facebook or google+ advantages?

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#394]
probably not but idk
or maybe even a working free roam camera?

**Comment by Luka967** [comment]
Facebook integration is a no until Zeach gives us some code. Free roam camera is an interesting idea, shouldn't be hard to implement.

**Comment by Agarian** [comment]
how about miniclip skins?

**Comment by Luka967** [comment]
You can use Agar.io Powerups to show them. (You're still able to connect to private servers, don't worry)

**Comment by Lukkez** [comment]
@Agarian If it's not possible make playerStartMass 43 or 132 (3X Start mass) i use this on my server

**Comment by vram4** [comment]
There wont be a way for ogar to access player account data from facebook/google because they are handled externally.
