### ISSUE TITLE
how do i make a pull request here?

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#399]

**Comment by Andrews54757** [comment]
Go to pull requests (tab) then click create new pull request

**Comment by Agarian** [comment]
doesn't let me click the button :\

**Comment by Agarian** [comment]
it says this:
Choose different branches or forks above to discuss and review changes.
there are no other branches.

**Comment by Andrews54757** [comment]
then I have no Idea, i just click it and it works

**Comment by NatsuTheGreat** [comment]
@vram4 close

**Comment by NatsuTheGreat** [comment]
Thanks @Agarian
