### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by DerpyUnlimited** [OgarProject/Ogar#401]
When I eject some mass my cell glitches out and sends my camera to a invisible cell with my name on it and it has 0 mass supposedly.

**Comment by Andrews54757** [comment]
What did you do? Is there any way I can reproduce your problem

**Comment by Andrews54757** [comment]
This happens when your cell has negative mass but how did you get debating mass

**Comment by Andrews54757** [comment]
I am pretty sure it is because you changed the playerMinMassEject value in config to something less than 16. It is supposed to be 32

**Comment by Andrews54757** [comment]
Issue is when playerMinMassEject is smaller than ejectMass

**Comment by DerpyUnlimited** [comment]
ok I changed that. Let me test it.

**Comment by NatsuTheGreat** [comment]
@vram4 Close
