### ISSUE TITLE
Error: WebSocket connection timed out

### ISSUE THREAD

**Issue by thomasmorelli** [OgarProject/Ogar#405]
I've got an Ubuntu server running Ogar on my network, I've set up port forwarding to the server for port 1500 (the game server) and port 1501 (the stats server), and I can't access it via the outside IP OR the local IP.

When I try to connect on the local IP (```agar.io/?ip=192.168.1.89:1500```):
```
Connecting to ws://192.168.1.89:1500
WebSocket connection to 'ws://192.168.1.89:1500/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
```

When I try to connect on the public IP (```agar.io/?ip=```MY PUBLIC IP```:1500```):
```
Connecting to ws://(MY PUBLIC IP):1500
WebSocket connection to 'ws://(MY PUBLIC IP):1500/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
```

What should I do?!

**Comment by Luka967** [comment]
I don't have any idea why but neither that my edited Ogar batch file won't go through the internet, only locally. I even added Node.js to firewall, still nothing!
Precompiled binaries still work for some reason.

**Comment by NatsuTheGreat** [comment]
@vram4 close

**Comment by TheDigitalOrchard** [comment]
Why was this closed without any further information added? Was it fixed? What was the solution?
