### ISSUE TITLE
Bots On Private Server

### ISSUE THREAD

**Issue by KyraCloud** [OgarProject/Ogar#410]
how do i use bots on my private server i wanna get big fast everytime i use the bots they just go in random direction (AgarPowerUps)

**Comment by Agarian** [comment]
change *serverScrambleCoords* in *gameserver.ini* to 0.

**Comment by Andrews54757** [comment]
you know what would be better? a way so that the server bots just run into you so others cant bot but you can (you specify player in console) I dont feel like making it though but when I do, I will add it to my fork

**Comment by KyraCloud** [comment]
Thanks guys :)
