### ISSUE TITLE
how change split cell distance to virus collision?

### ISSUE THREAD

**Issue by loboere** [OgarProject/Ogar#412]
similar to this server http://agar.io/?ip=agario.willsr71.net:443

**Comment by NatsuTheGreat** [comment]
Easy peasy,

Go to virus.js (in the entity folder) and scroll to about line 90.

You have two *for loops* there. You'll have a number like 150 and 20 in both loops. Change the 150 in the first loop to 500. Set it higher for more velocity.

If you need any more help, contact me.

**Comment by Luka967** [comment]
@NatsuTheGreat Those numbers don't exist anymore!
As of [this](https://github.com/Luka967/Ogar/commit/c27d45d2d4433d4f64659464506334d9f6bbce03) and [this](https://github.com/Luka967/Ogar/commit/2f76f997a3abce92932cf3b3a9b0439a9209878e) commit on my update, `newCellVirused` doesn't accept split speed anymore.

@loboere At `GameServer.js`, look at line 709:
```javascript
newCell.setMoveEngineData(newCell.getSpeed() * 6, 12); // Instead of fixed speed, use dynamic
```
Edit `* 6` to some other number.

**Comment by NatsuTheGreat** [comment]
@vram4 Close
