### ISSUE TITLE
how ejecuted mass random color?

### ISSUE THREAD

**Issue by loboere** [OgarProject/Ogar#413]

**Comment by NatsuTheGreat** [comment]
When you click w it gives you a random color instead of your cell color? Is that what's happening?

**Comment by loboere** [comment]
yes

**Comment by NatsuTheGreat** [comment]
Alright. I have a fix.

Go to GameServer.js and fix the *ejectMass* function. scroll down and you'll see this.

`
        // Create cell
        var ejected = new Entity.EjectedMass(this.getNextNodeId(), null, startPos, this.config.ejectMass);
		ejected.setAngle(angle);
        ejected.setMoveEngineData(this.config.ejectSpeed, 20);
        ejected.setColor(getRandomColor());
`

and replace it with:

`
        // Create cell
        var ejected = new Entity.EjectedMass(this.getNextNodeId(), null, startPos, this.config.ejectMass);
		ejected.setAngle(angle);
        ejected.setMoveEngineData(this.config.ejectSpeed, 20);
        ejected.setColor(cell.getColor());
`

**Comment by Andrews54757** [comment]
one time when I dont feel lazy, i am going to add a config feature to do this in my fork

**Comment by Andrews54757** [comment]
I added this feature so you can enable it in gameserver.ini [here] (https://github.com/AJS-development/Ogar-unlimited)

**Comment by NatsuTheGreat** [comment]
@vram4 close
