### ISSUE TITLE
PlayerTracker.getScore() function problem

### ISSUE THREAD

**Issue by Luka967** [OgarProject/Ogar#414]
So I'm really close on implementing free roam mode. All it's left is this piece of code under `mainLoop` which will find the client with most score if `specByLeaderboard` is `false`.
```javascript
            if (!this.gameMode.specByLeaderboard) {
                // Get client with largest score if gamemode doesn't have a leaderboard
                var lC;
                var lCScore = 0;
                for (var i = 0; i < this.clients.length; i++) {
                    if (typeof this.clients[i] == 'undefined') continue;
                    if (this.clients[i].getScore(false) > lCScore) lC = c;
                }
                this.largestClient = lC;
            } else this.largestClient = this.leaderboard[0];
```
I add 10 bots on my server and switch gamemode to Teams, and this error always pops out:
```
TypeError: this.clients[i].getScore is not a function
    at GameServer.MainLoop (GameServer.js:421:41)
    at wrapper [as _onTimeout] (timers.js:270:19)
    at Timer.listOnTimeout (timers.js:89:15)
```
The call stack doesn't pinpoint me the error. However **I'm suspecting `ai/FakeSocket.js`.**
I even added `getScore` function in `BotPlayer.js` but still nothing.

**Comment by Andrews54757** [comment]
I think it is because you didn't declare getScore . Shouldn't it be just Score

**Comment by Luka967** [comment]
Function `getScore` **IS** declared in `PlayerTracker.js`.

**Comment by Luka967** [comment]
Oh, I got it. Nevermind.
