### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by elitajmx** [OgarProject/Ogar#417]
When will we be able to have our Skins ?

**Comment by Luka967** [comment]
@elitajmx Never. You need both client and server to "know" if they're communicating for skins.
Agar.io client doesn't do it nor that it ever will.
You can use Agariomods though. They released an update which dramatically reduced lag.

**Comment by elitajmx** [comment]
okez

**Comment by NatsuTheGreat** [comment]
@vram4 close
