### ISSUE TITLE
Spectating

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarProject/Ogar#420]
This is about the new spectating feature.

What I have found out is that if you come in right away without spawning in the game, you cannot spectate, you get a white screen. (Like if you just came to the game and spectate right away with out actually spawning in the game, that happens.)

I have no idea how to fix this, could you guys figure this out?

**Comment by NatsuTheGreat** [comment]
Lol issue 420 xDDD

**Comment by Lukkez** [comment]
Smoke weed? everyday xDD
