### ISSUE TITLE
Weird issues.

### ISSUE THREAD

**Issue by MastaCoder** [OgarProject/Ogar#424]
I have found two issues. The split is very weird, it pushes back the cells a bit. I might know the fix to it. Also the virus is splitting is broken, I don't know what happened, but everytime I hit a virus I freeze and get an onConsume error.

This is on a fresh Ogar on a personal desktop running the latest version,

**Comment by Luka967** [comment]
Fixed the virus, and **its old weird collision**. About the split, it's more optimized for smooth splitting, although it still isn't exact.

**Comment by MastaCoder** [comment]
@Luka967 Great work! Now about the split, I don't know if it's just me, but it is *way* too slow.

**Comment by Agarian** [comment]
https://github.com/AJS-development/Ogar-unlimited go here this build has smooth split and more!

**Comment by NatsuTheGreat** [comment]
@vram4 Close?
