### ISSUE TITLE
Own website?

### ISSUE THREAD

**Issue by ElMay0r** [OgarProject/Ogar#443]
Hi, it is Posible to host Ogar on my own website like can do Cigar?

or 

you can only play ogar on agar.io

**Comment by Luka967** [comment]
You can only play ogar on agar.io.

**Comment by vram4** [comment]
Non official clients are not supported here.

**Comment by jollesnaas** [comment]
Contact me on skype, I can create it for you!

Or make it yourself:
You can rent a VPS (Windows or Linux) of me: 4 euro/month/512MB RAM or 8 euro/month/1GB RAM, 20 euro/Year/512MB RAM or 40 euro/year/1GB RAM.

If you want to know more or order, please contact me on skype: jolle.snaas
*Free test included!

**Comment by Andrews54757** [comment]
i dont trust this . dont fall for it others! Only give money to trusted people
