### ISSUE TITLE
Splitting like original agar.io

### ISSUE THREAD

**Issue by firelightning13** [OgarProject/Ogar#451]
I just want to make split looks like real agario, but I dunno how and I don't know how to code things(only few).

![ogar](https://cloud.githubusercontent.com/assets/17120382/12912463/b141b6a6-cf53-11e5-9003-f7fed76069de.png)
(The picture is just an example, my art sucks)

The point A is the position of the player, so I want to split from A to C(just act that is normal split range from agar.io). So the code is like this:
`        var splitSpeed = cell.getSpeed() * 9;`
but the split was too fast, I don't like it. However, if I change to:
`        var splitSpeed = cell.getSpeed() * 6;`
the split is slower and good but I only split from A to B.

So the question is, how to split far away but still make it slower?

**Comment by Luka967** [comment]
I'll play with splitting cells around with making adjustments and see what I accomplish.

**Comment by firelightning13** [comment]
Ok but btw if my cell is getting bigger, the split is very slower. The cell should have atleast add some speed when the cell is too big.

**Comment by Luka967** [comment]
This has been resolved. Close, @vram4
