### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by elitajmx** [OgarProject/Ogar#457]
How do i make friends join? i have hamcahi setup and everything..
(i cant portforward tho)

**Comment by Agarian** [comment]
same

**Comment by Andrews54757** [comment]
#434

**Comment by Agarian** [comment]
#434 does not help in any way.

**Comment by Andrews54757** [comment]
LOL I dont know how hamachi works

**Comment by NatsuTheGreat** [comment]
Multiple issues will not help, you'll have to find some hosting service to host it for you or figure out a way to port forward.

@vram4 Close?

**Comment by Agarian** [comment]
try c9.io

**Comment by jollesnaas** [comment]
You can rent a VPS (Windows or Linux) of me: 4 euro/month/512MB RAM or 8 euro/month/1GB RAM, 20 euro/Year/512MB RAM or 40 euro/year/1GB RAM.

If you want to know more or order, please contact me on skype: jolle.snaas
*Free test included!

**Comment by Andrews54757** [comment]
i dont trust this . dont fall for it others! Only give money to trusted people

**Comment by NatsuTheGreat** [comment]
Wasn't gunna buy something from someone I do not know at all xD
