### ISSUE TITLE
Apply border shrink feature to Ogar?

### ISSUE THREAD

**Issue by Luka967** [OgarProject/Ogar#470]
A recent addition in Agar.io has made bot-player coordinate obfuscation,
and a new feature that shrinks the border to a fixed size, which prevents minimaps from working correctly.
Should I try to apply border shrinking?

**Comment by Agarian** [comment]
why interfer with the minimaps anyway? also https://github.com/AJS-development/Ogar-unlimited has that feature. as a *shrink* and *enlarge* command.

**Comment by Andrews54757** [comment]
but i have a big question. Why do you want to obfuscate minimap's?

**Comment by Luka967** [comment]
Because agar.io does it.

**Comment by Andrews54757** [comment]
So to do that, you need to edit setborder.js in packet so it sends the wrong info about borders
