### ISSUE TITLE
help cant use npm install ws

### ISSUE THREAD

**Issue by GOpb** [OgarProject/Ogar#471]
when i use the npm install ws command thing happens 

npm WARN enoent ENOENT: no such file or directory, open '/Users/guthriepurinton-brown/package.json'

i am on a macbook pro

**Comment by firelightning13** [comment]
Have u install node.js correctly?

**Comment by Andrews54757** [comment]
to fix, you need to do
`cd (your directory to ogar)`
then do
`npm install`

**Comment by NatsuTheGreat** [comment]
@vram4 Close?
