### ISSUE TITLE
How to change cell speed?

### ISSUE THREAD

**Issue by LeninYT** [OgarProject/Ogar#472]
Hi! I want to change cell speed but i saw a lot of issues like this, but it didnt work.
All i have is Ogarwindows.exe and gameserver.ini. i dont have anything else and,there is no ''playerSpeed'' in gameserver.ini. Please halp meh!

**Comment by vram4** [comment]
The binary build of Ogar isnt updated with the latest features. Instead, you need to run the nodejs version. There are instructions in the readme.
