### ISSUE TITLE
When are we gonna be able to make friends join??

### ISSUE THREAD

**Issue by elitajmx** [OgarProject/Ogar#474]
DUZNT WORK WHAT NUW?

**Comment by firelightning13** [comment]
Lol idk only way is to port forward

**Comment by elitajmx** [comment]
yeah
wat about evolve?

**Comment by Andrews54757** [comment]
1. Why are you using other things when port forwarding is so easy
2. If you are using a raspberry pi like my test server, one great one is weaved
3. hamachi, i don't know if you should rely on hamachi because I've heard many times not just from ogar of problems with it

**Comment by Andrews54757** [comment]
also @elitajmx I think everyone at ogar heard your complaint on hamachi because there is #457 , #434 , #469 , and more. Currently, that is outside the scope of this project because hamachi is something separate from ogar. so please if you have a problem on hamachi, go look it up on google

**Comment by elitajmx** [comment]
I cant portforward because of my FUCKED UP internet okay?

**Comment by ThunderGemios10** [comment]
@elitajmx Then use Hamachi then. If you can't portforward, you have other choice.. Unless stated so.

**Comment by elitajmx** [comment]
hamachi isn't working >.<

**Comment by ThunderGemios10** [comment]
@elitajmx then port forward, If not. then there's nothing you can do.

**Comment by elitajmx** [comment]
k
i cant portforward.

**Comment by ThunderGemios10** [comment]
@elitajmx, Try searching for other methods for your friends to join.

**Comment by ThunderGemios10** [comment]
@elitajmx, Try searching for other methods for your friends to join.

**Comment by ThunderGemios10** [comment]
@elitajmx, Try searching for other methods for your friends to join.

**Comment by firelightning13** [comment]
@elitajmx  Do you know how to port forward properly? Port forward is so easy that everyone can do it.
Is it because you've used an application to port forwarding your router for you?
If that doesn't help, try to port forward manually:
http://www.howtogeek.com/66214/
http://www.wikihow.com/Set-Up-Port-Forwarding-on-a-Router

> I cant portforward because of my FUCKED UP internet okay?
srsly how is ur internet fucked up

**Comment by elitajmx** [comment]
i dont have router thats it

**Comment by Andrews54757** [comment]
really, then search up my ip in google and copy that number into the url area and if that does not work, do `192.168.1.1` in the url. if nothing pops up, then you do have a f**ked up internet

**Comment by elitajmx** [comment]
whats your ip

**Comment by elitajmx** [comment]
Would it be working with Evolve?

**Comment by Andrews54757** [comment]
just click [this] (https://www.google.com/search?q=my+ip&rlz=1CASMAE_enUS617US635&oq=my+ip&aqs=chrome..69i57j0l5.1319j0j7&sourceid=chrome&es_sm=93&ie=UTF-8&safe=active&ssui=on) and that number is your ip

**Comment by Andrews54757** [comment]
click this also [this] (http://192.168.1.1) This leads to the most common local ip for your router

**Comment by elitajmx** [comment]
i dont have router

**Comment by ItzLevvie** [comment]
not all router ip starts with 192.168.*.*

**Comment by ItzLevvie** [comment]
NOTE: Not all IPs starts with ```192.168.*.*``` some routers may use ```172.*.*.*``` extension.

**Comment by Andrews54757** [comment]
And it is impossible to not have a router. or else you cant msg us

**Comment by ItzLevvie** [comment]
@Andrews54757 Some people use Wi-Fi (those small devices that are 2 - 5 cm long) and Some people use routers.

**Comment by elitajmx** [comment]
i have internet, but i didn't buy the router whatever that hting is so u can port forward easy with it

**Comment by ThunderGemios10** [comment]
@elitajmx If you have an internet, then you should have a router.

**Comment by elitajmx** [comment]
oh i thought internet & router are different. Well my internet is very bad and we pay 60 euros a month like the fuck

**Comment by NatsuTheGreat** [comment]
@vram4 Close?

**Comment by Agarian** [comment]
try c9.io
