### ISSUE TITLE
Big cell at start

### ISSUE THREAD

**Issue by Crazytox** [OgarProject/Ogar#478]
Hello all,

First I'm sorry for my english, I'm french :stuck_out_tongue_winking_eye: 

My problem is when I click "Play game" on my page, my cell is immense and my name on leaderboard contains odd characters. You can see the screenshot for more details.

I tried several "main_out.js" but the bug is still present :confused: 

What is the problem ?

Thank you in advance for your help :smiley: 

![ogarbug](https://cloud.githubusercontent.com/assets/17298722/13117737/7804747e-d5a1-11e5-8b80-c70424fd47f7.png)

**Comment by ItzLevvie** [comment]
Download the latest Ogar, don't use Ogar for clients as it will need some modifications.

**Comment by Crazytox** [comment]
I had download the latest Ogar server. With what client should I use Ogar server ?

**Comment by Andrews54757** [comment]
If you dont know anythign about things such as packets or other things. it is best to use normal ogar or my version.

**Comment by Crazytox** [comment]
I like Ogar server cause it works with Node.JS and it is very customizable. However, I have this problem when I want to play :confused:

**Comment by Andrews54757** [comment]
yes normal ogar is the same and so is my version

**Comment by Andrews54757** [comment]
all ogar servers uses nodejs

**Comment by Crazytox** [comment]
I wanted to say that there is no executable file to start server.

**Comment by Andrews54757** [comment]
a binary or a .bat file ?

**Comment by Andrews54757** [comment]
oh nvm, i thought you were yousing something else. not useing normal ogar

**Comment by Andrews54757** [comment]
are you useing a client clone?

**Comment by Crazytox** [comment]
> all ogar servers uses nodejs
This Ogar server don't use .exe file, just a .bat file and I prefere.

> are you useing a client clone?
What is it ? (I'm french, sorry :laughing: )

**Comment by Andrews54757** [comment]
are you not useing `agar.io/?ip=yourip`?

**Comment by Crazytox** [comment]
Oh, no I use my own client hosted on my own website.

**Comment by Andrews54757** [comment]
exactly, 1. ogar doesnt support clients that do not use `agar.io` link. 2. it is very illegal to do that

**Comment by Crazytox** [comment]
Oh, so we can not have a private server ?
--
Do you know why my cell is big on start ?

**Comment by ItzLevvie** [comment]
@Crazytox You can actually have a private server. Use http://agar.io/?ip=[yourip]:443

**Comment by Andrews54757** [comment]
pls read the readme.md file completrely

**Comment by vram4** [comment]
Its because your client is outdated, not an Ogar problem and doesn't really belong here as custom clients are not supported.

**Comment by Luka967** [comment]
Wait. What was your border configuration?
There is a bug that causes cells to spawn all in one place when the border is set to ex. 6000 on top, bottom, left and right.

**Comment by Andrews54757** [comment]
BTW @Luka967 did you see the formula i created for virus mech on the suggestions issue. I think i solved you problem of making it simple
