### ISSUE TITLE
splitting

### ISSUE THREAD

**Issue by awikwee** [OgarProject/Ogar#479]
when i split the splitting is almost instant and i want it to be like normal agarios splitting speed

**Comment by Andrews54757** [comment]
Try ogar unlmited or ogar 1

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/Ogar-unlimited

**Comment by Luka967** [comment]
@awikwee change playerSmoothSplit to `1` in gameserver.ini

**Comment by firelightning13** [comment]
playerSmoothSplit should set 1 to default so ppl will not confuse

**Comment by awikwee** [comment]
none of these work for me so anything else to fix it?

**Comment by firelightning13** [comment]
You need to download zip instead of using windows binary(not update for months :/)

**Comment by NatsuTheGreat** [comment]
@vram4 Close?
