### ISSUE TITLE
Are there new Default Map Border Values?

### ISSUE THREAD

**Issue by Benunzee** [OgarProject/Ogar#482]
Since the New Agar Update, I am not sure if there are new Defaults (Since I would like the Minimap for Agarplus to work.) Also I would like my Map bigger but also Default.

**Comment by ItzLevvie** [comment]
These are the values you'll need to change.
```
borderRight = 14142
borderBottom = 14142
ejectMass = 13
```

**Comment by NatsuTheGreat** [comment]
@ItzLevvie How do we figure out the map values?

**Comment by firelightning13** [comment]
@Benunzee Change **serverScrambleCoords** to **0**, then change the line:
```
borderLeft = 0
borderRight = 11180.3398875
borderTop = 0
borderBottom = 11180.3398875
```
to
```
borderLeft = -5590.16994375
borderRight = 5590.16994375
borderTop = -5590.16994375
borderBottom = 5590.16994375
```
I calculated the value by 11180.3398875 _(ogar said it was a default value for vanilla agar.io)_ divided by 2._(You can change the value if you want but make sure you divide by 2)_
Then, it should works in your minimap.
Oh, and about serverScrambleCoords, if you want your server to be public, its really **bad idea** to put it into 0.
