### ISSUE TITLE
DMCA Takedown?

### ISSUE THREAD

**Issue by aaxxo** [OgarProject/Ogar#489]
Is this referring to the copyright notice?  As in copyright notice goes in for Ogar, it is good to use still?

Hi there,

I'm contacting you on behalf of GitHub Support because we've received a DMCA takedown notice regarding the following content:

https://github.com/aaxxo/OgarServ
https://github.com/aaxxo/Ogar-unlimited

You can view the notice and the details of the requested changes below.

In this case only certain files were identified as allegedly infringing. Since it's not possible to disable individual files within a GitHub repository, we're giving you a 24 hour opportunity to remove the content named in the takedown. Please follow the steps in the following article to remove the content from the history:

https://help.github.com/articles/remove-sensitive-data

Once you've done that, please reply to this message to confirm the change. If we don't hear from you that a change is made within the next 24 hours, we will need to disable the entire repository according to our GitHub DMCA Takedown Policy, which you can find here:

https://help.github.com/articles/dmca-takedown-policy/

If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described on the DMCA Takedown Policy page.

PLEASE NOTE: It is important that you reply within 24 hours to confirm whether you have made the requested changes. If you do not, the repository will be disabled.

---

Hello,

I have read and understand GitHub's Guide to Filing a DMCA Notice.

The original work is located at: https://github.com/OgarProject/Ogar
The license for the original work (Apache 2.0 license) is located at: https://github.com/OgarProject/Ogar/blob/master/LICENSE.md

Infringing materials are as follows:
---

https://github.com/JaraLowell/OgarServ

Entire repository is a derivative work from the original, and has been relicensed under an incompatible license (GPL version 2, found at https://github.com/JaraLowell/OgarServ/blob/master/LICENSE). To remedy this error, the code can be relicensed the Apache 2.0 license or a compatible license, such as GPL version 3.
In addition, the repository removes my name from the license, which is a violation of the Apache 2.0 license requiring that the original copyright be included.

https://github.com/aaxxo/OgarServ
https://github.com/Agarian/OgarServ
https://github.com/LEVATHIAN/OgarServ
https://github.com/MastaCoder/OgarServ
Forks of the above project that carry the same license incompatibility.

---

https://github.com/AJS-development/Ogar-unlimited

Entire repository is a derivative work from the original. The following commit removes my name from the license, which is a violation of the Apache 2.0 license requiring that the original copyright be included. I request that the below commit is disabled and that the repository owner updates the file to include the original copyright.
https://github.com/AJS-development/Ogar-unlimited/commit/afa8558d5497ced6f5a0d4d2b86ee482e0a5e769

https://github.com/aaxxo/Ogar-unlimited
https://github.com/Agarian/Ogar-unlimited
https://github.com/Andrews54757/Ogar-unlimited
https://github.com/ItzLevvie/Ogar-unlimited
https://github.com/JoeLiu333/Ogar-unlimited
https://github.com/Lbniese/Ogar-unlimited
https://github.com/Luka967/Ogar-unlimited
https://github.com/NatsuTheGreat/Ogar-unlimited
Forks of the above project that carry the same incompatibility.

---

I request that the above projects are disabled expediently until the requested changes are made.

I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, its agent, or the law.

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

Signed,
[private]

Email: [private]
Mobile: [private]

**Comment by Andrews54757** [comment]
Well, that was my fault, i didn't know but i have fixed it and updated

**Comment by aaxxo** [comment]
I'm just glad it was only a credit issue and not a takedown of the repo.  You have done some amazing work on improving Ogar so far.

**Comment by Andrews54757** [comment]
Thanks
