### ISSUE TITLE
Cannot play in the same server with friends on the same wifi.

### ISSUE THREAD

**Issue by grahamcracker1234** [OgarProject/Ogar#493]
I am trying to play with a friends locally, we are on the same wifi and have the same IP, but we cannot join the same server. I know that it should work if we are on the same server and wifi, what is wrong?

**Comment by Andrews54757** [comment]
instead of `127.0.0.1:443` you need to use your lan wifi

**Comment by Andrews54757** [comment]
search up how to find my lan wifi on google

**Comment by grahamcracker1234** [comment]
Andrew the thing is I already used the IP address for the network. Should I try using the 127.0.0.1:443

**Comment by Andrews54757** [comment]
No i mean a LAN ip address, it is different

**Comment by Andrews54757** [comment]
You used the PUBLIC ip address, it wont work unless your port foward

**Comment by Andrews54757** [comment]
Lan ips typically begin with 192.168. So example, my servers lan ip is 192.168.1.13

**Comment by grahamcracker1234** [comment]
My LAN's IP is 192.168.20.132, my friends is 192.168.20.234 It is different, and they don't work, when we try to play.

**Comment by Andrews54757** [comment]
it should work, mabye it has to do with a firewall on your computer.

**Comment by grahamcracker1234** [comment]
I don't believe I had installed any unless they are pre-installed. So it doesn't matter that it is different. It should still work?

**Comment by grahamcracker1234** [comment]
I tried it with my public ip didn't work for anyone. And I tried the 127.0.0.1 and that only worked for the laptop hosting it.

**Comment by Luka967** [comment]
Which OS are you running?
If you have Windows 7+,
Is your wi-fi set to `public`, `home` or `work`? If not, replace it to `home` or `work` (it'll do the same).
Try moving the server's files folder to another place or rename the main folder. A popup might appear for settings of the firewall. If it appears, press Allow Access elevated permissions required.

**Comment by NatsuTheGreat** [comment]
Go to the default gateway of your ISP and somewhere there it should have information about LAN devices. Find your LAN IP if you haven't already and the link will become *http://agar.io/?ip=YourLANIP:YourPort*

**Comment by GoCyb3r** [comment]
Just google : what's my ip

**Comment by Andrews54757** [comment]
Do some research on google such as "how to port foward a application" @vram4  Close?
