### ISSUE TITLE
Minions bots

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#497]
How to put minions like ogar-unlimited? [Click here](https://github.com/AJS-development/Ogar-unlimited)

**Comment by Luka967** [comment]
This is supposed to be as agar.io as it can be, so we don't want this.

**Comment by davidmann4** [comment]
maybe interessting for you https://github.com/davidmann4/ogar-feeder-bot

any thoughts about disallowing my header (I circumvented Ogar scramble) ?

**Comment by davidmann4** [comment]
https://github.com/OgarProject/Ogar/issues/372

**Comment by Andrews54757** [comment]
Its to complicated david

**Comment by Lukkez** [comment]
@davidmann4 The reason i put here is because your bots don't go to my server at 127.0.0.1, 192.168.1.1, external ip, and all proxys are working

**Comment by davidmann4** [comment]
if you want to use them lcoalhost you have to connect them to 127.0.0.1 without any proxies - just use NOPROXY

**Comment by Andrews54757** [comment]
Also, i am going to update the scramble soon

**Comment by Andrews54757** [comment]
Also, i am going to update the scramble soon

**Comment by davidmann4** [comment]
ahh cool - what is the new aproach? Maybe we figure out something secure.

**Comment by davidmann4** [comment]
any details?

**Comment by Andrews54757** [comment]
i have an idea, this will also improve anti team and there is no way you can avoid all these tests.
1. Test if one players mouse coords are in close rrange with lots of other players
2. check if lots of people under some mass go into you in a timeout
3. finally see if lots of people split or shoot mass at the same time

Some of these tests are probably easy to go past but all of them togethor are harder.
