### ISSUE TITLE
Popsplit/Virus throw

### ISSUE THREAD

**Issue by Lukkez** [OgarProject/Ogar#498]
On ogar popsplit not work how to make work? and virus throw too

**Comment by Luka967** [comment]
It does rarely.

**Comment by NatsuTheGreat** [comment]
What are virus throws?

**Comment by Lukkez** [comment]
[Click here to see what is virus throw](https://www.youtube.com/watch?v=aBWk3csDDEc)

**Comment by NatsuTheGreat** [comment]
Oh I've done that, Just never heard of it.

**Comment by Megabyte918** [comment]
i think editing the splitspeed when u split on a virus in virus.js might give you a better chance at a successful splitpop

**Comment by Megabyte918** [comment]
but im not sure how

**Comment by NatsuTheGreat** [comment]
@vram4 Close?
