### ISSUE TITLE
Board command doubel space

### ISSUE THREAD

**Issue by Ciao121** [OgarProject/Ogar#503]
Hi,
just saw that if the board command is sent with two (or more)  spaces in the string to be displayed, consecutive spaces after the first display a line with the current player.

**Example with "Ciao121" nickname** ans <space> to be more clear

`Board This<space>is<space>a<space>test displays:`
1 This
2 is
3 a
4 test

**BUT**

`Board This<space>is<space><space>a<space>test<space><space>displays:`
1 This
2 is
3 Ciao121
4 a
5 test
6 Ciao121

Don't know if Ogar shold strip out consecutive spaces or this is used for something I don't know.

**Comment by retslac** [comment]
Yeah, thx for bringing it up.  Had not noticed this before.  Agar.io screws up leaderboard again: when you send empty string it displays your nickname.  Don't know why agar.io makes it this way.  To fix you can replace empty string with space in ogar.

To fix, search for this line in board command in CommandList.js:
```
newLB[i - 1] = split[i];
```
And replace it with this:
```
if (split[i]) {
    newLB[i - 1] = split[i];
} else {
    newLB[i - 1] = " ";
}
```

**Comment by Andrews54757** [comment]
Nah, not very significant though
