### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by karleKremen** [OgarProject/Ogar#506]
I have just set up Ogar server on my Cloud9 server. 
Server says that everything is OK [(pastebin)](http://pastebin.com/AAk2HtGk).
But when I connect, it says: 
```
WebSocket connection to 'ws://agar-server-karlekremen1.c9users.io:1203/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
```.
Cloud9 uses Ubuntu.

**Comment by ItzLevvie** [comment]
Cloud9 doesn't act like a VMS. Use something like koding.com.

**Comment by ItzLevvie** [comment]
Cloud9 won't allow you to create servers like that.

**Comment by karleKremen** [comment]
Problem fixed. Cloud9 allows usage of only 3 ports 8080, 8081, 8082. I moved server to 8081 and 8082 and all's working now. Closed.
