### ISSUE TITLE
Check description for more info.

### ISSUE THREAD

**Issue by ItzLevvie** [OgarProject/Ogar#508]
Can someone add this?

In Agar.io, when you keep your mouse at the center of the screen, and then split, your cell doesn't go back to the center, instead the cell drops below your cell. 

Also, how about continuing on https://github.com/OgarProject/Ogar/issues/470? I know people will be like, why add border shrinking, but remember Ogar's motto is to be as close as vanilla Agar.io as possible. If a new feature was recently added onto Agar.io, then why not add it into Ogar? Don't just leave that feature till some another time or in the future, since 45% or more of the people on reddit are just going to be like 'Why aren't some of the features on the vanilla Agar.io on Ogar?' We all know that Ogar is NodeJS based and Agar.io is C++ based, but it shouldn't be that hard to implement all these useful features.

EDIT: I could work on this, but I don't have computer access till the next 2 - 3 months, so I was wondering if someone could do this?

**Comment by Andrews54757** [comment]
question, Where did your fork go?

**Comment by ItzLevvie** [comment]
@Andrews54757 I moved it into a private repository.

**Comment by Andrews54757** [comment]
okay

**Comment by ItzLevvie** [comment]
@Luka967

**Comment by firelightning13** [comment]
Yeah, ive been think about that too.

Oh and also:
![ogar2](https://cloud.githubusercontent.com/assets/17120382/13554127/c7060c8a-e3da-11e5-8e8d-5399099d9dc2.png)

Can you make it horizontally instead of vertically?

**Comment by Lukkez** [comment]
See this video [Click here](https://youtu.be/YJsAcneEzf4?t=46) This is what need to happen as @firelightning13 said, ik the mouse is not on center and i will make a print of what happen on agario with this 
![image](https://cloud.githubusercontent.com/assets/15003706/13576736/e25d6f26-e46d-11e5-9fce-3533618884c8.png)

**Comment by ItzLevvie** [comment]
@Luka967

**Comment by Luka967** [comment]
Working on it don't worry!
