### ISSUE TITLE
Split not Smooth

### ISSUE THREAD

**Issue by NoorAgario** [OgarProject/Ogar#515]
is there any way to make the splitting like real agario ? please help fast ! 
thanks

**Comment by ItzLevvie** [comment]
Change ```playerSmoothSplit = 0``` to ```playerSmoothSplit = 1```.

**Comment by Megabyte918** [comment]
yis

**Comment by NoorAgario** [comment]
Where can I change that ? in which file >.<

**Comment by ItzLevvie** [comment]
gameserver.ini

**Comment by NatsuTheGreat** [comment]
Change this in gameserver.ini where you see a bunch of player configs like "playerRecombineTime" Along the bottom of those settings you'll find it.
