### ISSUE TITLE
Virus explosions

### ISSUE THREAD

**Issue by Megabyte918** [OgarProject/Ogar#521]
How do i make the virus explosions like this?

![animation](https://cloud.githubusercontent.com/assets/17245196/13902494/dcc06eda-ee07-11e5-9a24-c01495c011e7.gif)

I just like the way they pop out all around the cell better

**Comment by batbug** [comment]
Change playerSmoothSplit = 0 to playerSmoothSplit = 1

**Comment by Megabyte918** [comment]
Already tried, didnt work

**Comment by NatsuTheGreat** [comment]
I might have something like that but I don't know for certain, maybe sometime we can check it out.

**Comment by Megabyte918** [comment]
Yes pls

**Comment by NatsuTheGreat** [comment]
Alright, where can we have a faster chat system?

**Comment by Megabyte918** [comment]
Add me on discord im Megabyte918, but right now im on vacation so I dont have access to my computer :(

**Comment by NatsuTheGreat** [comment]
Oh so are you able to connect to my server? Or no?

**Comment by Megabyte918** [comment]
Maybe hold on

**Comment by NatsuTheGreat** [comment]
Alright, I am still open.

**Comment by Megabyte918** [comment]
Alright i got a laptop whats ur server?

**Comment by NatsuTheGreat** [comment]
Hang on let me get on discord.

**Comment by NatsuTheGreat** [comment]
Come to this channel https://discordapp.com/channels/125461430366371840/125461430366371840

**Comment by Megabyte918** [comment]
not letting me join

**Comment by NatsuTheGreat** [comment]
Weird I'm going to try to add you.

**Comment by NatsuTheGreat** [comment]
What does it say?

**Comment by Megabyte918** [comment]
nothing

**Comment by NatsuTheGreat** [comment]
Try again or reload.

**Comment by Megabyte918** [comment]
didnt work wtf is wrong with discord lol

**Comment by Megabyte918** [comment]
join this https://discord.gg/0sD1CqPXwAPqHZSb
