### ISSUE TITLE
[Question] Joining the development of Ogar2?

### ISSUE THREAD

**Issue by ThunderGemios10** [OgarProject/Ogar#522]
Hi there! I would like to join the development of Ogar2, Or at least maintain it and be on a look out for issues/pull requests.

**Comment by firelightning13** [comment]
@ThunderGemios10 [Here](https://github.com/OgarProject/Ogar2-Server)

**Comment by ThunderGemios10** [comment]
@firelightning13 I would like to be a collaborator, Able to close/reopen issues as well as merging pull requests, I am experienced in Java, I want to be able to maintain it.

**Comment by firelightning13** [comment]
@ThunderGemios10 You need to ask @forairan if you want to be a collaborator.

**Comment by ThunderGemios10** [comment]
@firelightning13 He seems inactive and does not respond at all. What about the other devs?
