### ISSUE TITLE
Cannot Move in the Private Server

### ISSUE THREAD

**Issue by mr-sniper20** [OgarProject/Ogar#526]
Everything is working fine for the ogar server, but when I open it, I can not move myself.  I can split, but not move.  Please help.

**Comment by NatsuTheGreat** [comment]
What gamemode are you using?

**Comment by mr-sniper20** [comment]
It's ok, I installed a different version and it works fine.

**Comment by NatsuTheGreat** [comment]
Oh Okay.

@vram4 Close?
