### ISSUE TITLE
Read description for more info.

### ISSUE THREAD

**Issue by ItzLevvie** [OgarProject/Ogar#527]

**Comment by ItzLevvie** [comment]
@Luka967

**Comment by Luka967** [comment]
2) Fixed - replace function `Cell.prototype.addMass` with this (Simply put auto-split needs to happen BEFORE eating mass):
```javascript
Cell.prototype.addMass = function(n) {
    // Check if the cell needs to autosplit before adding mass
    if (this.mass > this.gameServer.config.playerMaxMass && this.owner.cells.length < this.gameServer.config.playerMaxCells) {
        var splitMass = this.mass / 2;
        var randomAngle = Math.random() * 6.28 // Get random angle
        this.gameServer.createPlayerCell(this.owner, this, randomAngle, splitMass);
    } else {
        this.mass = Math.min(this.mass, this.gameServer.config.playerMaxMass);
    }
    this.mass += n;
};
```
1 & 3) Fixed - replace from `PlayerTracker.prototype.update`:
```javascript
    // Map obfuscation
    var width = this.viewBox.width;
    var height = this.viewBox.height;

    if (this.cells.length == 0 && this.gameServer.config.serverScrambleMinimaps >= 1) {
        // Update map, it may have changed
        this.socket.sendPacket(new Packet.SetBorder(
            this.gameServer.config.borderLeft,
            this.gameServer.config.borderRight,
            this.gameServer.config.borderTop,
            this.gameServer.config.borderBottom
        ));
    } else {
        // Send a border packet to fake the map size
        this.socket.sendPacket(new Packet.SetBorder(
            Math.max(this.centerPos.x + this.scrambleX - width, this.gameServer.config.borderLeft + this.scrambleX),
            Math.min(this.centerPos.x + this.scrambleX + width, this.gameServer.config.borderRight + this.scrambleX),
            Math.max(this.centerPos.y + this.scrambleY - height, this.gameServer.config.borderTop + this.scrambleY),
            Math.min(this.centerPos.y + this.scrambleY + height, this.gameServer.config.borderBottom + this.scrambleY)
        ));
    }
```
4) Same owner cells can eat themselves while moving. Because most of the split distance is `collisionRestoreTicks` being 0; that little split distance will mean that the cells instantly recombine.

**Comment by Megabyte918** [comment]
What will this do? @Luka967

**Comment by ItzLevvie** [comment]
@Megabyte918 The first one part of the code, makes it like this "My mass was 19K, the biggest guy was 20K, and the smallest guy was 5K. In vanilla agario, when I ate the 5K guy on top of the 20K guy, my cell would have surpassed the 22.5K limit into 24K for just long enough for me to eat the 20K guy, then my cells would have split into two 22K pieces. But this doesn't happen in ogar."

and the other one you already know.

**Comment by ItzLevvie** [comment]
In Ogar, when I got up to 16 pieces, with 22500 mass in each cells, which results into 360K mass in total, but when people feed into me, the score will stay at 360K and will not move further up the stairs.

This is what it should be like in vanilla Agar.io @ https://youtu.be/Kj_Gtjj1010 (pay attention to the score and the people feeding him)

@Luka967

**Comment by ItzLevvie** [comment]
@Luka967

**Comment by Andrews54757** [comment]
its done in my fork (was there for a while). you know what i mean by my fork, which is ogar unlimited

**Comment by ItzLevvie** [comment]
I know, but I'm not going to use Ogar-unlimited for now because Ogar seems to be more realistic than Ogar-unlimited.

**Comment by Megabyte918** [comment]
I agree @ItzLevvie
and if this is added, the physics will almost be perfect :D

**Comment by Megabyte918** [comment]
@Andrews54757 you ok with me making a pull request with the code? i got it to work on my private version
