### ISSUE TITLE
Old colors

### ISSUE THREAD

**Issue by mogokcp** [OgarProject/Ogar#529]
How do i switch to the old color style?

Now the colors are like in normal agar [of cells/food] but i like the old ones, ill like to switch :) thx

edit. 
I disabled scramblers, both, and my bots still go to corners. Please help

**Comment by ItzLevvie** [comment]
Edit GameServer.js, and replace GameServer.prototype.getRandomColor{...} with this
```
GameServer.prototype.getRandomColor = function() {
    var rand = Math.floor(Math.random() * 3);
    if (rand == 0)
        return {
            r: 255,
            b: Math.random() * 255,
            g: 0
        };
    else if (rand == 1)
        return {
            r: 0,
            b: 255,
            g: Math.random() * 255
        };
    else
        return {
            r: Math.random() * 255,
            b: 0,
            g: 255
        };
};
```

**Comment by NatsuTheGreat** [comment]
If you want the old colors do the following:

Find this line:
    // Gamemodes
    this.gameMode = Gamemode.get(this.config.serverGamemode);

And under it put this:	
	    // Colors
    this.colors = [
        {'r':235, 'g': 75, 'b':  0},
        {'r':225, 'g':125, 'b':255},
        {'r':180, 'g':  7, 'b': 20},
        {'r': 80, 'g':170, 'b':240},
        {'r':180, 'g': 90, 'b':135},
        {'r':195, 'g':240, 'b':  0},
        {'r':150, 'g': 18, 'b':255},
        {'r': 80, 'g':245, 'b':  0},
        {'r':165, 'g': 25, 'b':  0},
        {'r': 80, 'g':145, 'b':  0},
        {'r': 80, 'g':170, 'b':240},
        {'r': 55, 'g': 92, 'b':255},
    ];


Then find:

GameServer.prototype.getRandomColor = function() {
    var rand = Math.floor(Math.random() * 3);
    if (rand == 0)
        return {
            r: 255,
            b: Math.random() * 255,
            g: 0
        };
    else if (rand == 1)
        return {
            r: 0,
            b: 255,
            g: Math.random() * 255
        };
    else
        return {
            r: Math.random() * 255,
            b: 0,
            g: 255
        };
};

And replace it with:
GameServer.prototype.getRandomColor = function() {
    var index = Math.floor(Math.random() * this.colors.length);
    var color = this.colors[index];
    return {
        r: color.r,
        b: color.b,
        g: color.g
    };
};

**Comment by ItzLevvie** [comment]
or ^

**Comment by ItzLevvie** [comment]
@NatsuTheGreat the getRandomColor has been changed (https://github.com/OgarProject/Ogar/commit/a2aff8166a199c391206a7411aee600a23a1d1f6)

**Comment by NatsuTheGreat** [comment]
Thanks @ItzLevvie ^^

**Comment by mogokcp** [comment]
@NatsuTheGreat  i used your code and i got this

`TypeError: Cannot read property 'length' of undefined
    at GameServer.getRandomColor (/home/agario/GameServer.js:349:55)
    at GameServer.spawnFood (/home/agario/GameServer.js:559:21)
    at GameServer.startingFood (/home/agario/GameServer.js:546:14)
    at GameServer.<anonymous> (/home/agario/GameServer.js:192:14)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:117:20)
    at net.js:1076:10
    at process._tickCallback (node.js:763:13)
    at Function.Module.runMain (module.js:723:11)
    at startup (node.js:323:14)
`


???? 

code is

`    // Gamemodes
    this.gameMode = Gamemode.get(this.config.serverGamemode);
}

    // Colors
    this.colors = [
        {'r':235, 'g': 75, 'b':  0},
        {'r':225, 'g':125, 'b':255},
        {'r':180, 'g':  7, 'b': 20},
        {'r': 80, 'g':170, 'b':240},
        {'r':180, 'g': 90, 'b':135},
        {'r':195, 'g':240, 'b':  0},
        {'r':150, 'g': 18, 'b':255},
        {'r': 80, 'g':245, 'b':  0},
        {'r':165, 'g': 25, 'b':  0},
        {'r': 80, 'g':145, 'b':  0},
        {'r': 80, 'g':170, 'b':240},
        {'r': 55, 'g': 92, 'b':255},
    ];
    
    
module.exports = GameServer;`

**Comment by NatsuTheGreat** [comment]
I see what you did wrong, I mean AFTER 
`
` // Gamemodes
this.gameMode = Gamemode.get(this.config.serverGamemode);
`

Make your code:
` 
// Gamemodes
this.gameMode = Gamemode.get(this.config.serverGamemode);

// Colors
this.colors = [
    {'r':235, 'g': 75, 'b':  0},
    {'r':225, 'g':125, 'b':255},
    {'r':180, 'g':  7, 'b': 20},
    {'r': 80, 'g':170, 'b':240},
    {'r':180, 'g': 90, 'b':135},
    {'r':195, 'g':240, 'b':  0},
    {'r':150, 'g': 18, 'b':255},
    {'r': 80, 'g':245, 'b':  0},
    {'r':165, 'g': 25, 'b':  0},
    {'r': 80, 'g':145, 'b':  0},
    {'r': 80, 'g':170, 'b':240},
    {'r': 55, 'g': 92, 'b':255},
];

}
```

**Comment by mogokcp** [comment]
Thanks a lot m8!

**Comment by NatsuTheGreat** [comment]
No problem.
