### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by techpulse** [OgarProject/Ogar#53]
Sorry, no idea where.

I want to log stuff into my database (hosting it on a windows vps, since it seems to have issues installing on linux).

Whatsoever.

I hope to see some kind of database connection, outgoing api so it logs the leaderboards into a remote database.. this would be issue as i would need mysql to be open, so i guess if you can somehow make web requests instead so i can make an api that would be better

**Comment by techpulse** [comment]
also ability to ban with ip.txt and username.txt

**Comment by Jackster35** [comment]
^^ Good idea

**Comment by Jackster35** [comment]
So I can sync those two files between 14 of my servers. Also, call those every time somebody connects or every few minutes so we don't have to use a reload command or something.

**Comment by techpulse** [comment]
yeah, i want to ban bots but doing it with firewalls are very annoying lol,

some kind of db would also be nice for people that has this for sites that want top 10 etc

**Comment by vram4** [comment]
The ban feature was removed because too many bans ended up crashing the server.

**Comment by ezramod** [comment]
who can help me how to send Score to Database?

**Comment by z3ntu** [comment]
Request update or close!

**Comment by techpulse** [comment]
i still want this idea added

**Comment by DaFudgeWizzad** [comment]
bump

**Comment by Darshil182** [comment]
How about adding a pop-up window before closing the command-prompt cause every time a write a command I always forget to minimize and just close it Please

**Comment by DaFudgeWizzad** [comment]
@Darshil182 Like a prompt asking if you are sure?

**Comment by Darshil182** [comment]
Yes

**Comment by Ephemerality** [comment]
Pretty sure a closing prompt won't be possible until Ogar 2 comes out.

**Comment by Porama6400** [comment]
good way if ogar have option
Database: [OPTION]
[OPTION] = true or false

if it's true , you need to enter sql config or something like
DatabaseIP: localhost
DatabasePort: 32132
DatabaseUser: root
DatabasePassword: banana

**Comment by Ephemerality** [comment]
I think the bottom line here (and other devs can correct me if they plan otherwise but it's been over a month) is that there is not going to be any leaderboard-database option added (possibly in O2 if anything). That's not to say you couldn't add it yourself, though. That's the point of open source after all.
