### ISSUE TITLE
Get position/coordinates of all playercells

### ISSUE THREAD

**Issue by Ogarunite** [OgarProject/Ogar#531]
Hi, i'm trying to figure out how to fetch the coordinates of all the cells by running a for loop inside PacketHandler.js

What I have managed so far is to fetch the coordinates of my cell only when using this: 
            console.log(this.socket.playerTracker.cells[0].position);

But how can I do it if i wish to output everyone's coordinates?

`for (var i = 0; i < this.gameServer.clients.length; i++) {

            var allClientsCoords = this.socket.playerTracker.cells[i].position); 
console.log(allClientsCoords);
}
`
Wouldn't work because i use this.socket. I tried combinations of this.gameServer.clients[i].position and this.gameServer.playerTracker, etc, etc. Didn't manage :(

**Comment by Ogarunite** [comment]
I finally managed to figure it out. Took some days, but whoever would need this in the future, this is how it was done:

`        for (var i = 0; i < this.gameServer.nodes.length; i++) {
            var playerCell = this.gameServer.nodes[i];
            if (playerCell.getType() == 0) {
                console.log(playerCell.position);
            }
        }
`

**Comment by vram4** [comment]
I would recommend looping through nodesPlayer instead of nodes. That way, you can get rid of the if statement that checks for the node type.

**Comment by Ogarunite** [comment]
Oh, okay thanks!
