### ISSUE TITLE
New Ogar 2 Fork! (Ogario Project)

### ISSUE THREAD

**Issue by ThunderGemios10** [OgarProject/Ogar#533]
We are pleased to announce the new fork of Ogar2, **The Ogario Project!**
## Features:
- Plugins
- Leaderboard
- Multi-Colored Food
- Better configuration
- Performance enhancements
- Bugfixes
- Splitting and Ejecting..
## Planned/Upcoming Features:
- Bots
- Teams
- Chat (Maybe?)
- Commands API
- Many API features.
## Known Bugs:
- Entities sometimes are not disappearing/deleted from the world.
## Our GitHub repositories:
- [Ogar2-API](https://github.com/OgarioProject/Ogar2-API)
- [Ogar2-Server](https://github.com/OgarioProject/Ogar2-Server)
## Our Team members:
- SkorrloreGaming - (Project Lead/Implementation Lead Developer)
- ThunderGemios10 - (Developer/API Lead Developer)

Any help or contributions is always appreciated!

**Comment by HuddaFire** [comment]
I'd rather fork it when it's a little more updated and polished. I don't think forking it now is a good idea...
