### ISSUE TITLE
Size Problem

### ISSUE THREAD

**Issue by HEROx29** [OgarProject/Ogar#534]
guys I need your help I start SO BIG  

http://prntscr.com/am2ld9 

PLZ HELLPPPPPP

**Comment by firelightning13** [comment]
@HEROx29 That's client side problem

**Comment by Luka967** [comment]
Check your config again. Too much food or too many bots are notable causes.

**Comment by Andrews54757** [comment]
no, he was using a custom client. Clients are not discussed here as they are also illegal

**Comment by Andrews54757** [comment]
close? @vram4
