### ISSUE TITLE
agar.io terms of service

### ISSUE THREAD

**Issue by jrockway** [OgarProject/Ogar#535]
I was reading the agar.io ToS today:

http://agar.io/terms.txt

It says:

> You agree not to do any of the following:
> ...
> 7.    Create or use any server emulators;

Has anyone gotten in trouble for this?  Reddit tells me that they are now banning accounts that ran agar-lvlgen, for example, even though that's not mentioned in their ToS at all.

**Comment by Megabyte918** [comment]
Shhhhh... :)

**Comment by MohamedAmine** [comment]
In ToS, They have no reason for banning!! :/

**Comment by ItzLevvie** [comment]
@MohamedAmine They're not exactly going to ban the user, they'll wipe their entire Agar.io account.

**Comment by Andrews54757** [comment]
I think they mean client servers not physics servers.

**Comment by ItzLevvie** [comment]
@jrockway It was answered here: https://www.reddit.com/r/Agario/comments/4cs44g/terms_of_service_ogar/

**Comment by christopherkardas** [comment]
@ItzLevvie i spoke to the Moneyclip community manager in the YouTube lifestream, he also told me that they will remove all coins, skins, and the lvl.
Now after the 3 or 2 day agar pc ban, we can play again with all coins, skins, our lvl.... So it was all fake and intimidation :)

**Comment by ItzLevvie** [comment]
Close? @vram4
