### ISSUE TITLE
Physics/bugs/suggestions

### ISSUE THREAD

**Issue by Megabyte918** [OgarProject/Ogar#536]
Hello, i've gathered a list of stuff that are bugs and suggestions on the physics of Ogar. Most of these are from [this,](https://github.com/AJS-development/Ogar-unlimited/issues/268) but i thought i'd bring mine and some other people's here just to shed some light. If anybody has anything else to add on, please, leave it here :)

Credit: @fodse
> - If a player spawns from an Ejected Mass, he will always have the size of that mass (13 by default), and not the size that is displayed on "PlayerStartMass" in "Gameserver.ini" (which is 43 in my case).
- 80% of the time you'll spawn very close to some other player/bot or even dead. (The same happens with viruses).
- In vanilla Agar.io, when you split with the cursor in the middle of the cell, it doesn't split horizontaly, it actually splits to alot of directions and then freezes.

Credit: @Lukkez
> - Cells still move when getting hit by a virus while mouse is in center. (used to work in previous versions of ogar but now it doesnt?)

Credit: @firelightning13
> - <del>When splitting a new cell, the new cell shouldnt be move by cursor (or move a little bit) until cRestoreTicks is finish ticking. I don't know it is a mech from vanilla agar.io but you'll notice when you're too big. </del>
- The camera sometimes only focus to the smaller cell instead of the big one (possibly giving priority for the big cell?) (you'll notice when you have 2 pieces which is huge cell with very small cell at another one)

And here is a list of mine:
- [Virus explosions] (https://github.com/AJS-development/Ogar-unlimited/issues/242) could be a little better when big
- Splitpops do not work 90% of the time like they should
- Virus throws do not work
- Doublesplits could be more accurate
- Cells need to have a little more "bounce back" or "spring" to them when doublesplitting or tricksplitting. And just splitting in general.
- When in max pieces, and max size in each of those pieces, cells cant surpass 360k mass. They should be able to #527 
- Cells on the same team on teams mode can prevent another cell from moving, this is very annoying cause sometimes bots like to stick to you
- Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed
- Bots are lazy and don't split for people most of the time
- In vanilla agario, when doublesplitting, some of your cells have a chance of switching order, which allows you to splitkill someone when you doublesplit at them over a virus.
- Splitting and w-ing against the border of the map should be more bouncy
- The range of which a cell consumes another cell is too short (**possible config for this?**)
- Needs a better anti-bot system, servers can still get infested with suicide bots even when all anti-bot systems are active
- Splitspeed and distance between cells when splitting needs to be increased. The seperation of the cells when splitting is slow af right now
- Player speed needs to be 35 by default, as it is more similar to the regular speed of vanilla agario
- When out of bot names in realisticnames.txt or botnames.txt, they should reuse the same names instead of bot[#], (bot then number of bot)

**Comment by ItzLevvie** [comment]
@Luka967

**Comment by Luka967** [comment]
Oh my god, that'll take ages ;-;

I started working on it.

**Comment by Megabyte918** [comment]
@Luka967 thank god. these have been bugging me forever. if these are fixed, then the physics will almost be exactly like vanilla :D

**Comment by ItzLevvie** [comment]
https://www.reddit.com/r/Agario/comments/4cuev7/important_big_update_and_new_moderators/

**Comment by firelightning13** [comment]
WOW, Miniclip, wow.

5000 coins to play private server,for only 10 people...

:smile: :gun:

**Comment by Megabyte918** [comment]
RIP agario :(

**Comment by Lukkez** [comment]
WOW, Miniclip, wow.

5000 coins to play private server,for only 10 people...

:smile: :gun:

And rip for party mode...
**I'M SAD :( :gun: **

**Comment by Luka967** [comment]
But unfortunately it isn't even an april fools joke...

**Comment by Megabyte918** [comment]
Wow... im not suprised xd
they just f*cked themselves and agario.

**Comment by NatsuTheGreat** [comment]
Hey Mega! I'm trying to fix some of these issues right now.

**Comment by Megabyte918** [comment]
sweet! i wish i could pm u on skype or disc right now, but i only have access to github atm (its kind of a long story >.<)

**Comment by NatsuTheGreat** [comment]
Lel. It's okay. I fixed so far;

cells stopping when mouse in the middle;
random angles when splitting and mouse is in the middle;
changed playerspeed to 35;
fixed spawning mass from ejected mass (now starts with playerStartMass);
and made more bouncy physics with borders;

**Comment by NatsuTheGreat** [comment]
I think that'll be it, I don't feel good right now.

**Comment by Megabyte918** [comment]
Thank you man :) i hope you get better soon

**Comment by NatsuTheGreat** [comment]
Thanks!

**Comment by ItzLevvie** [comment]
It's was april fools, now everything is back to normal.

**Comment by Megabyte918** [comment]
GG miniclip

**Comment by ThunderGemios10** [comment]
@Megabyte918 Actually, GG Agar.io subreddit moderators :)

**Comment by ItzLevvie** [comment]
https://www.reddit.com/r/Agario/comments/4d1431/ragario_april_fools_fools/

**Comment by batbug** [comment]
> Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed

Pretty sure, this exists in vanilla, always been bugging me

**Comment by NatsuTheGreat** [comment]
> Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed

This actually does exist in vanilla, if you WANT to get rid of you'll need to make all cells equal speed.

**Comment by Luka967** [comment]
> When splitting a new cell, the new cell shouldnt be move by cursor (or move a little bit) until cRestoreTicks is finish ticking. I don't know it is a mech from vanilla agar.io but you'll notice when you're too big.

Does happen in vanilla too.

> Smaller cells can push owners own bigger cells, and same with bots, which gives you a speed boost. This needs to be fixed

Does happen in vanilla too but has a much, MUCH smaller degree.

The problem arised when double collision was implemented again. Revert it and it'll all be fine.

**Comment by ItzLevvie** [comment]
@Luka967 Are you still working on this?

**Comment by Luka967** [comment]
@ItzLevvie Not really, I've fixed some issues however. School catched up on me last week.

**Comment by ItzLevvie** [comment]
@Luka967 Okay.

**Comment by Megabyte918** [comment]
@Luka967 ripped?

**Comment by Megabyte918** [comment]
@Luka967 ripped?

**Comment by Megabyte918** [comment]
ill update this later

**Comment by Megabyte918** [comment]
@Luka967 i added some bugs and edits and crossed things out

**Comment by Megabyte918** [comment]
@Luka967 I crossed some things out, ill put the bugs in a new issue
