### ISSUE TITLE
Getting error from latest pull

### ISSUE THREAD

**Issue by DeWilX** [OgarProject/Ogar#546]
Error message - 
http://pastebin.com/6AidR1nf

**Comment by firelightning13** [comment]
@DeWilX Do `npm install` again or click `Install Dependencies.bat` again

**Comment by NatsuTheGreat** [comment]
That is a vector2 problem

do:

````
npm install vectore2-node
````

**Comment by DeWilX** [comment]
@firelightning13 Thanks, `npm install` worked. :)
