### ISSUE TITLE
Slither

### ISSUE THREAD

**Issue by Logan7432** [OgarProject/Ogar#559]
There should be a ogar for the new trend Slither.io, Please make this a thing!!!

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/349

**Comment by Andrews54757** [comment]
probably not going to happen for a long time

**Comment by Luka967** [comment]
They still didn't decode the protocol to the root. Until then, only tests can be made.
Also the slither.io website doesn't support connecting to servers outside official ones.

**Comment by ItzLevvie** [comment]
Creating private servers in slither.io is possible now

**Comment by Logan7432** [comment]
We would have to make a similar client as slither and then make a server to work with it.

**Comment by ThunderGemios10** [comment]
@everyone, You can check: https://github.com/ClitherProject/Slither.io-Protocol
