### ISSUE TITLE
Agar.io has updated their website & servers

### ISSUE THREAD

**Issue by ItzLevvie** [OgarProject/Ogar#561]
They've fixed bots, most of the lag and anti-teaming but now private servers doesn't seem to be working.

**Comment by ItzLevvie** [comment]
I'm 100% sure this has to do something with packets. Just spawned with the name "LOL" and the console returns "佌L" also when going into the spectate mode I just see a huge blue screen .


![image](https://cloud.githubusercontent.com/assets/11600822/15050275/92fdbec6-12ea-11e6-98a4-70344f127503.png)
![image](https://cloud.githubusercontent.com/assets/11600822/15050282/a69dac5c-12ea-11e6-8048-4813de92a011.png)

**Comment by Megabyte918** [comment]
UGHHH MINICLIP

**Comment by Luka967** [comment]
Really bad news:
*Looks like UpdateNodes packet is changed. We've got to change it.*

**Comment by ItzLevvie** [comment]
Okay.

**Comment by NatsuTheGreat** [comment]
They chinese character and the blue screen are UpdateNodes problems. I played around with UpdateNodes.js before, and what I got are chinese character names and weird shapes.

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b0rubk yay look at this.

**Comment by scholtes** [comment]
Once this issue is resolved, please update the protocol wiki as well: http://agar.gcommer.com/index.php?title=Protocol

**Comment by NatsuTheGreat** [comment]
I see how we get the black cells, they tried fixing the skin zooming in bug.

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b0t0vz

**Comment by NatsuTheGreat** [comment]
Even some food cells disappear and some turn black.

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b0t41a

Yeah I don't think they patched bots.

Lol my screenshot is  *bot*41a

**Comment by Luka967** [comment]
Reverting packet handler to the "debug" state, I came to some weird discoveries:
- Facebook login actually sends a packet. *Facebook/Google+ integration is possible.* However the packet is [messy](http://imgur.com/ijnUjxf).
- The Facebook packet is apparently also sent every minute or so.
- [There is a new packet 17 every time you press S](http://imgur.com/RD8rovp).

I'm looking for my friend to help me with catching agario server packets.

**Comment by Luka967** [comment]
My friend just came and I've captured an UpdateNodes packet sample from both Ogar and agar.io. I'm going to compare them now.

**Comment by mkalex777** [comment]
They changed protocol completely.

**Comment by AuguxAX** [comment]
Guys im coding bots... but the patched everythink

**Comment by JustLexor** [comment]
When I start the private server this happens ;( 
![random compilation 118 - ft_ raceist fat joke depressed cyclist i propose a new law - youtube - google chrome 06 05 2016 20_22_49](https://cloud.githubusercontent.com/assets/19212746/15082572/ba14f81a-13c8-11e6-88c6-14384ced0c2c.png)

**Comment by LegitSoulja** [comment]
@JustLexor Are you using that extension? Other than that you can connect your private server to agar.io as of right now..

**Comment by Aanis12** [comment]
they completely removed private server i think

**Comment by Lukkez** [comment]
Just update the packets will solve and you can use [agario infinity](http://a-infinity.tk) as a extension on chrome to solve this, this extension still use old protocol

**Comment by ItzLevvie** [comment]
"they completely removed private server i think" They've not removed private servers.

**Comment by SkorrloreGaming** [comment]
"Just update the packets will solve and you can use agario infinity as a extension on chrome to solve this, this extension still use old protocol" W0W thanks! I will be using this until all the Ogar packages in existence gets updated

**Comment by ThunderGemios10** [comment]
@SkorrloreGaming This means i need to update the packets at our Ogar 2 version :/, Anyone managed to document the new protocol?

**Comment by LegitSoulja** [comment]
@ThunderGemios10 yes

**Comment by AmClan** [comment]
isn't agar infinity a bot extension?

**Comment by SkorrloreGaming** [comment]
@AmClan Not just a bot extension but a complete agar mod with tons of mods. I know I recommended it earlier, but just give me a few days and I will have a forked version out that is much better.

**Comment by F0RIS** [comment]
@AuguxAX yeap(

**Comment by lukerayman** [comment]
That's why Hungry Cells (my agar.io client for Windows Phone) stopped working. The new code is so hard to read. Looks impossible to figure out the new protocol for me. I'm thinking about starting my own server using Ogar to keep Hungry Cells alive... Do you guys think you will figure out the new protocol?

**Comment by Luka967** [comment]
Probably never.
I'm currently making a special client app for Ogar.

2016-05-09 11:02 GMT+02:00 Łukasz Rejman <notifications@github.com>:

**Comment by F0RIS** [comment]
@lukerayman while you thinking, i am already done that with my android app called "Blob") Got $50 on DigitalOcean as student and setup everything)). Ogar works fine excluding it perfomance :(

**Comment by kcxx** [comment]
Maybe my old Java client will be useful for now

**Comment by Luka967** [comment]
Shh.
[There is still hope...](http://i.imgur.com/wq9kakq.png)

**Comment by Megabyte918** [comment]
i dont know which emoji i just picked i cant see it haha

**Comment by Megabyte918** [comment]
@Luka967 awesome! now maybe in another 5 months it will be fixed :D

**Comment by Andrews54757** [comment]
I created a guide to install the client for ogarul https://github.com/AJS-development/Ogar-unlimited/issues/537

**Comment by ThunderGemios10** [comment]
@Luka967 Holy crap, Your actually contacting Miniclip for this?!

**Comment by firelightning13** [comment]
5 months lol

**Comment by Luka967** [comment]
@ThunderGemios10 Ye, why not?

**Comment by ThunderGemios10** [comment]
@Luka967 I don't really expect Miniclip to help us xD

**Comment by F0RIS** [comment]
@kcxx thx for client, enought nice code. I wroted my client for android in may 2015 and network part looks like obfuscated js code, because in that way it was easier to write))) now i can make good refactoring. Btw your client with this server work with some gubs now)

**Comment by F0RIS** [comment]
@Luka967 they are asshols) and they will not discard update for us)

**Comment by Luka967** [comment]
@F0RIS Who said they'll revert the update? They'll probably help us in some other way

**Comment by Andrews54757** [comment]
I already contacted them lots of times to help us but they reply "we do not share that information"

**Comment by SkorrloreGaming** [comment]
Just keep looking through the code, you don't have to understand it just
implement it and make sense of it while your going.

**Comment by Andrews54757** [comment]
And im tired of moneyclip holding all the cards

**Comment by lukerayman** [comment]
I'm reading the data from agar.io servers using Wireshark and it looks like packets with leaderboard info didn't change. :P

**Comment by SkorrloreGaming** [comment]
Just focus on the things that are no longer working instead of looking
through the whole thing, the joining packet, sending packets out, etc. Just
don't over work yourselves, I know from experience that it is a very bad
idea.

**Comment by lukerayman** [comment]
OK, I can connect and read the leaderboard. :D Not too much but more than nothing...

![leaderboard](https://cloud.githubusercontent.com/assets/1166994/15155387/84d13d40-16e2-11e6-8fac-b6d755dff073.PNG)

**Comment by Andrews54757** [comment]
I already posted the new client so that ogar unlimited can run http://ajs-development.github.io/client/

**Comment by Luka967** [comment]
Hey, this is Ogar here.

**Comment by F0RIS** [comment]
@lukerayman hm. how you make that? can describe somewhere?

**Comment by lukerayman** [comment]
@F0RIS here: http://agar.gcommer.com/index.php?title=Protocol#Initial_Connection

**Comment by SkorrloreGaming** [comment]
Okay so you guys are getting somewhere, you got connecting to work. We found out that the version being sent out is now v6. I will keep watching this thread and the commits if I find that it is probably fixed then I will make sure to push the same changes to every other Ogar framework in existence. Good luck everyone! Remember.. Never give up hope.

**Comment by batbug** [comment]
isn't it illegal to make custom clients?

**Comment by F0RIS** [comment]
@batbug i think that makin own servers not legal too)

**Comment by Luka967** [comment]
@F0RIS I actually asked this on Reddit. Mod told me that it isn't.

**Comment by Andrews54757** [comment]
soo, back on topic, did anyone figure it out yet? I mean the packets. Mabye we should just make a open source game called ogar.io thats like agario except it looks different so its legal. I mean, I feel like us devs are being trodden by moneyclip. They dont care and their support is a lie, and so is their saying that they care about the community. with ogar.io, we could add some useful features like chat and stuff.

**Comment by Andrews54757** [comment]
it can be a github pages website because it doesnt require like mysql or somthing. That way, we can add all the major devs from ogar to edit the website

**Comment by TheMaskedMonkey** [comment]
https://github.com/OgarProject/Ogar/issues/561#issuecomment-218594111

So you're suggestion gota.io?

**Comment by makmm** [comment]
well, i want to help. but, i dont know nothing about making a game in html5... well yes, i know a bit, but nothing too big... if there's a way to pm or something here, just pm me with a tutorial or something... thanks :)

**Comment by Megabyte918** [comment]
@Andrews54757 that idea has some potential

**Comment by batbug** [comment]
Miniclip insists that have have copyrighted exclusive rights to the overal design and in-game content (i think they mean circles, W, etc)

**Comment by Andrews54757** [comment]
How is that even possible? Patenting circles? If this is true, my geometry teacher would have been arrested

**Comment by batbug** [comment]
go here https://euipo.europa.eu/eSearch/#basic and search for 3081652 - you will get 10 docs of registered design

CRD 3081652-0001
CRD 3081652-0003
CRD 3081652-0004
CRD 3081652-0005
CRD 3081652-0006
CRD 3081652-0007
CRD 3081652-0008
CRD 3081652-0009
CRD 3081652-0010

**Comment by EnTerr** [comment]
"""
Suffice it to say that copyright can apply to your video game, marketing materials, documentation, and website, but cannot apply to the name of your game or an idea about a game. You can’t get a copyright for a witty slogan or a listing of ingredients. 
[...] 
Also note that you can’t copyright a game mechanic. That is, no one has the copyright on the idea of falling blocks disappearing when they form lines. You can’t copyright the idea of people running out of the way of oncoming vehicles.
"""

**Comment by batbug** [comment]
@EnTerr 
good point, but we need to examine those CRDs before doing anything

**Comment by TheMaskedMonkey** [comment]
I think you're all a bit late to the show honestly. Clones like Gota and Petridish have already been around for a year (coming up to it at least)

**Comment by makmm** [comment]
@TheMaskedMonkey but if we make our own client, we can connect to ogar servers, and modify it how we want.

**Comment by SkorrloreGaming** [comment]
Its plain ILLEGAL, how about that answer huh?

**Comment by makmm** [comment]
and why gota.io, agarabi.com, abs0rb.me, etc. are still alive?

**Comment by TheMaskedMonkey** [comment]
How about I told you I own Gota and I can tell you for a fact it isn't illegal. We made the client and server our self. https://en.wikipedia.org/wiki/Video_game_clone

**Comment by F0RIS** [comment]
@TheMaskedMonkey what you use on server side?

**Comment by TheMaskedMonkey** [comment]
https://forums.gota.io/thread-8391.html

**Comment by Thunder45455** [comment]
You can still get onto servers using the old versions of ogar at 
[dl.ogarproject.com/binaries/9bec5842ee427207578b9ae25ecc17e5da7179fa/](url)
then download an extension on the chrome store (I recommend bagar helper) 
Then start the server and play like normal on [http://agar.io/?ip=127.0.0.1:443](url)

**Comment by firelightning13** [comment]
nah we dont want an old version

**Comment by Megabyte918** [comment]
@ItzLevvie you have privileges now?

**Comment by Andrews54757** [comment]
no, she just closed her own issue

**Comment by Megabyte918** [comment]
LOL I forgot it was her own I'm stupid :P

**Comment by hertzbug** [comment]
@Luka967 Can you drop me an email at i t s h e r t z @gmail[[.com]] (preventing cralwers) ? I wanna have a talk with you. Thanks!

**Comment by IAP-Reloaded** [comment]
@hertzbug Don't post your email...
