### ISSUE TITLE
Private servers on miniclip's client  have now been blocked.

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#563]

**Comment by Luka967** [comment]
Can't argue with possibility, but it just ain't right.
http://prntscr.com/b1hh96

**Comment by Agarian** [comment]
whats that image about?

**Comment by Luka967** [comment]
Proves that agar.io still connects to private servers without a problem.

**Comment by Agarian** [comment]
you can connect but u cant play on em

**Comment by Ckicky** [comment]
But what if they blocked it by putting a screen picture there?
99.9% they won't do that, but it's worth trying, right?

**Comment by lukerayman** [comment]
They just changed the protocol. The client can connect but it expects packets in the new format. For example, the "update world" packet has a new opcode: 255, but previously it was 16. Ogar servers are still sending packets in the old format, so the new agar.io client can't read them.
