### ISSUE TITLE
What settings so trick split etc works?

### ISSUE THREAD

**Issue by CalvinDKHD** [OgarProject/Ogar#564]
Title says it, it sucks not to be able to do tricksplit etc.

**Comment by ItzLevvie** [comment]
Tricksplit works

**Comment by firelightning13** [comment]
It works btw

**Comment by CalvinDKHD** [comment]
Ohh lol, cuz do you guys know Cigar? They used Ogar but made the client side. But tricksplit aint working on it, Try out here : agarextreme.ml   Its my website.

**Comment by ItzLevvie** [comment]
Ciger's gameserver is very outdated and uses an old physics engine thus that's why you cannot tricksplit

**Comment by CalvinDKHD** [comment]
Ok ok, but i really need a client side. Like cigar. But i wanna use ogar.

**Comment by ItzLevvie** [comment]
![image](https://cloud.githubusercontent.com/assets/11600822/15099111/de5a8bb8-1544-11e6-8b5f-e23edcd6ccbc.png)
:P

**Comment by Megabyte918** [comment]
is that the old version

**Comment by ItzLevvie** [comment]
@Megabyte918 That's Ogar in Cigar
