### ISSUE TITLE
new way to connect to servers easily

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#568]
http://ajs-development.github.io/client/

**Comment by Andrews54757** [comment]
@Agarian it doesnt work for ogar, it only works for ogarUL

**Comment by Agarian** [comment]
oh nvm

**Comment by Agarian** [comment]
i suggest adding the "connecting" message to it. i may be able to do so...

**Comment by Andrews54757** [comment]
you can do so

**Comment by Agarian** [comment]
how easily?

**Comment by Andrews54757** [comment]
not too hard

**Comment by Agarian** [comment]
ok imma try it

**Comment by Andrews54757** [comment]
Things you have to edit:


* Main_out.js
* Css files
* Index.html

**Comment by Agarian** [comment]
oh all that?

**Comment by Agarian** [comment]
which css file?

**Comment by Agarian** [comment]
i cant get it to work xD
