### ISSUE TITLE
I need agar.io old graphics

### ISSUE THREAD

**Issue by LostCodesy** [OgarProject/Ogar#570]
Hello,

I need agar.io old graphics,

index.html, main_out.js, i18.js, environment.js, agario.js and other files

Please give me, my skype = greenskypark

Thanks to everyone.

**Comment by Andrews54757** [comment]
no one has them

**Comment by Andrews54757** [comment]
weve been searching for a long time but we havent found the latest graphics

**Comment by F0RIS** [comment]
@LostCodesy https://yadi.sk/d/5ZVUAv0OrgDzd

**Comment by IsMaiLeMaster** [comment]
you cant use raga.pw

**Comment by Luka967** [comment]
k
