### ISSUE TITLE
The chat not working on cigar

### ISSUE THREAD

**Issue by RelTakeover** [OgarProject/Ogar#580]
pls help me the chat not working :(

**Comment by Andrews54757** [comment]
Pop quiz!

1. What is the name of this project?
* Cigar
* ogarserv
* ogar-1
* ogar unlimited
* ogarproject

**Comment by RelTakeover** [comment]
pls help me >.<

**Comment by Andrews54757** [comment]
answer to quiz please

**Comment by Andrews54757** [comment]
The answer is ... Ogarproject!!

> If you got it wrong, your smartness is lower than a cow but hey, at least your smarter than that of Moneyclip!

**Comment by RelTakeover** [comment]
pls help me mi chat not working pls pls help :(

**Comment by jrgryph** [comment]
I think this is what you are looking for...
https://github.com/CigarProject/Cigar

**Comment by Andrews54757** [comment]
OK
>The Story of Bill, by Andrews54757


>Bill was very sad, He was an honest person who was basically perfect in every way, yet he had failed his first job. He was a game developer at Miniclip, and was working on a game called "Who's Smarter!". The game was to put people into a list based apon their smartness. Later, after the game was released, Miniclip had to take it back. Still though, thousands have already played it. Miniclip became the laughing stock of the year. Poor Bill was fired as well. Whats the point of this story? the point is dont be too honest as what Bill did by putting the CEO of miniclip last on the list.

**Comment by NatsuTheGreat** [comment]
I am on the floor Andrews ROFL!

**Comment by NatsuTheGreat** [comment]
But seriously, rel, this is like the fourth issue that is out of scope here. IT'S OGAR PROJECT MAN!!!

**Comment by Andrews54757** [comment]
I feel comical

**Comment by NatsuTheGreat** [comment]
Try this!!!:
https://github.com/CigarProject/Cigar/issues
Haven't seen a single of your issues there.

**Comment by Andrews54757** [comment]
I need to submit that story to Cadence. I bet I will get the gold key first prize!

**Comment by NatsuTheGreat** [comment]
Really, you should.

**Comment by Andrews54757** [comment]
>In miniclip, a new employee was getting his training.
The employer said: Now, I will give you a short quiz to check you are not insane

>Now, what does a chicken give you?
>								Eggs!
>Good! what does sheep give you?
>								Clothes!
>Awesome!  what does a pig give you? 
>								Bacon!
>Great! Now what does the fat cow give you?
>								Questions!
>
> John was never hired

**Comment by NatsuTheGreat** [comment]
@Andrews54757 

> Great! Now what does the fat cow give you?
Questions!

LMAO right now xD. He called him a fat cow xD lmao.
