### ISSUE TITLE
Goodbye private servers. It's been a fun ride.

### ISSUE THREAD

**Issue by Luka967** [OgarProject/Ogar#583]
2 weeks after the version 6 protocol change, [new protocol version 7 has completely encrypted the messages sent](http://pastebin.com/rTyju8P6). It's complete nonsense.

**Goodbye private servers.
It's been a fun ride.**

**Comment by Barbosik** [comment]
agree.

It shows that they fighting not with bots, but with private servers.

**Comment by Megabyte918** [comment]
Does this mean Ogar is officially RIP?
I don't get it, why patch private servers when your still getting ad revenue out of them, all they did was make themselves lose money and cause a lot of people to quit because they cant have their own custom servers

**Comment by ItzLevvie** [comment]
You can still use Ogar for custom clients.

**Comment by lukerayman** [comment]
Ogar works fine for my mobile client. Thank you for your hard work! Ogar gave a new life for my game after agar.io team changed their protocol. You're the best!

![servers2](https://cloud.githubusercontent.com/assets/1166994/15405268/753996f4-1e01-11e6-8876-0093e699bad1.PNG)

**Comment by Luka967** [comment]
Client sending is "obfuscated" only.
