### ISSUE TITLE
how to configure multiple servers?

### ISSUE THREAD

**Issue by RelTakeover** [OgarProject/Ogar#585]
FFA 1
FFA 2 
FFA 3
BIG 1

HOW TO CONFIGURE MASTERSERVER FOR MULTIPLE SERVER ON MY PRIVATE AGAR ?

**Comment by NoiseControllers** [comment]
multiple screens=?¿

**Comment by Andrews54757** [comment]
I just recently created something called multiverse in ogar ul. Im gonna make commands for it soon

**Comment by firelightning13** [comment]
THIS IS OGARPROJECT NOT CIGARPROJECT HOW MANY TIMES DID I TELL YOU!??

**Comment by Andrews54757** [comment]
Exactly ^^^

**Comment by Megabyte918** [comment]
vram is alive? :O
