### ISSUE TITLE
CHEAP VPS HOST

### ISSUE THREAD

**Issue by jollesnaas** [OgarProject/Ogar#596]
If anyone needs a cheap VPS for hosting, I CAN HELP!

Here is what I offer:
You can rent a VPS (Windows or Linux) of me: 4 euro/month/512MB RAM or 8 euro/month/1GB RAM, 20 euro/Year/512MB RAM or 40 euro/year/1GB RAM.

If you want to know more or order, please contact me on skype: jolle.snaas
*Free test included! 

Thanks for reading!

**Comment by lukerayman** [comment]
OVH is cheaper. :)
**$3.49**/month with **2GB** RAM

**Comment by TDashDog1** [comment]
@lukerayman If you want high-end-ish, [Contabo](http://contabo.com) is even cheaper and their SSD Boosted line offers insane value, with more cores, more RAM, and waaaayyyyy more storage. If you want lower end (found this on lowendbox), [AlphaVPS](https://lowendbox.com/blog/alpharacks-ddos-protected-linux-windows-vps-starting-9-99year-los-angeles-usa/) is offering $10/year for 512MB RAM

**Comment by Andrews54757** [comment]
i dont trust this . dont fall for it others! Only give money to trusted people

**Comment by Andrews54757** [comment]
close @vram4 .

**Comment by TDashDog1** [comment]
@Andrews54757 correct.

**Comment by Andrews54757** [comment]
@jollesnaas dont try to make ogar a cash cow

**Comment by vram4** [comment]
I'm sorry, but Ogar's github is not a place for you to advertise your vps hosting.
