### ISSUE TITLE
Skins don't work.

### ISSUE THREAD

**Issue by hlevine9** [OgarProject/Ogar#598]
I try to do <kraken>, and it doesn't give a skin on my cell. Also, when I do in the command thing >name <kraken>, it comes up as saying that "Cell #1 now has the Kraken skin, but there's no skin. Please fix.

Also, if you can't fix that, pls make the IP compatible with Vanilla Agario because i want to play on it with AgarPlusio.

Thanks!

**Comment by hlevine9** [comment]
Also, the skins Trump, Hillary, and other Democratic/Country leaders don't work. I want to be able to record a video of trump Wrecking Hillary and show it to a Trump fan.

**Comment by Barbosik** [comment]
skins are not used in ogar server
