### ISSUE TITLE
Slither Private Server?

### ISSUE THREAD

**Issue by RowanHarley** [OgarProject/Ogar#603]
Can you please make a private server. I know this has been asked before but now there is a documented protocol [here](https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md) and it is possible to connect to a server of choice by using `forceServer(ip,port)`

**Comment by firelightning13** [comment]
This is OgarProject, means it's ogar only. You should visit the other project that is working on slither.io's client/server implementation. Just google it.

**Comment by RowanHarley** [comment]
ok
