### ISSUE TITLE
What can I remove in the Ogar code to disable players/bots eating each other?

### ISSUE THREAD

**Issue by IAP-Reloaded** [OgarProject/Ogar#605]
I am triyng to make it so that my Ogar server only allows players to eat food. How can I disable players eating each other?

**Comment by NatsuTheGreat** [comment]
There are a couple of ways... But why would you want that? xD

**Comment by IAP-Reloaded** [comment]
I'm trying to add it to each gamemode's code so I can make one gamemode that disables it. But please just tell me. I want to keep the code for what happens when eaten, also.

**Comment by NatsuTheGreat** [comment]
Oh specific gamemodes, I will look into it later.

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat, what triggers death events though?

**Comment by NatsuTheGreat** [comment]
Kills?

**Comment by IAP-Reloaded** [comment]
What triggers the code for mass gain and when someone kills another?

**Comment by NatsuTheGreat** [comment]
.onConsume

**Comment by IAP-Reloaded** [comment]
Where is the code that triggers it?

**Comment by NatsuTheGreat** [comment]
in the entity folder. There are files which have ```onConsume``` functions.

**Comment by IAP-Reloaded** [comment]
Hmm... so I can't just remove it and add it to each gamemode. Is there a way to consume if the gamemode id is not 5 (Peace mode)

**Comment by NatsuTheGreat** [comment]
You need the onConsume function for the entities. You can't have it in gamemode.

**Comment by IAP-Reloaded** [comment]
but is there an if statement that I can use so that if the gamemode is not 5/Peace, it will not do the onConsume function?

**Comment by NatsuTheGreat** [comment]
onConsume functions have two parameters, ```consumer``` and ```gameServer``` the consumer parameter is actually the player consuming the entity. You CAN add an if statement, just make sure you use the right roots.

**Comment by IAP-Reloaded** [comment]
Can you show example code? I'm bad at JavaScript.

**Comment by NatsuTheGreat** [comment]
I'll try, hang on.

**Comment by IAP-Reloaded** [comment]
Okay.

**Comment by Barbosik** [comment]
Look at Cell.js, function visibleCheck. It detects collision and returns 2 if some cell eats some other one.

Just add the following check before for loop and players will not be able to eat each other:
```
    if (this.cellType == 0) return 1;   // <= added
    // To save perfomance, check if any client's cell collides with this cell
    for (var i = 0; i < cells.length; i++) {
```

But it means that player will not be able to eat self also. So, he will not be able to remerge.
In order to allow remerge, there is need to extend this mod. You need to modify for loop to detect remerge only.

**Comment by IAP-Reloaded** [comment]
@Barbosik Does this only work if the gamemode is set to ID 5?

**Comment by Barbosik** [comment]
it works for any game mode

**Comment by IAP-Reloaded** [comment]
@Barbosik Can you change it so it only works for gamemode ID 5?

**Comment by NatsuTheGreat** [comment]
Add something like ```if(gameServer.getMode === "Peace") if (this.cellType == 0) return 1;   // <= added``` *First try getting rid of ```if (this.cellType == 0) return 1;   // <= added``` and add what I told you```* Peace is whatever gamemode you have. Not sure if will work though, haven't tested.

**Comment by Barbosik** [comment]
no, I'm working on physics and performance improvements for MultiOgar.
If you want to check it for specific game mode, look at GameServer getCellsInRange:
```
                    // If one of cells can't merge
                    if (!cell.canRemerge() || !check.canRemerge()) {
                        // Check if merge command was triggered on this client
                        if (!cell.owner.mergeOverride) continue;
                    }
```

This code from MultiOgar. Ogar uses a little different approach, it check recombineTicks instead of call to canRemerge. TeamZ also uses it. So you can investigate if you can utilize it in the same way

**Comment by IAP-Reloaded** [comment]
Can you put that into a code block?

**Comment by IAP-Reloaded** [comment]
@Barbosik I'm confused.

**Comment by NatsuTheGreat** [comment]
@IAP-Reloaded Look at what Barbosik posted before. "if (this.cellType == 0) return 1;   // <= added" replace that line with ```if(gameServer.getMode === "Peace") if (this.cellType == 0) return 1; // <= added``` Idk if it works.

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat use code blocks!

**Comment by IAP-Reloaded** [comment]
`
hi
`

**Comment by NatsuTheGreat** [comment]
... Fine.

```if(gameServer.getMode === "Peace") if (this.cellType == 0) return 1; // <= added
    // To save perfomance, check if any client's cell collides with this cell
    for (var i = 0; i < cells.length; i++) {
```
Find that loop in cell.js

**Comment by IAP-Reloaded** [comment]
That's not right.

**Comment by IAP-Reloaded** [comment]
```
if(gameServer.getMode === "Peace") if (this.cellType == 0) return 1; // <= added
// To save perfomance, check if any client's cell collides with this cell
for (var i = 0; i < cells.length; i++) {
```

**Comment by NatsuTheGreat** [comment]
Yeah, use that, whatever.

**Comment by IAP-Reloaded** [comment]
Can you add the full loop? Here's the full statement:

```
        isThere = (this.abs(this.position.x - centerPos.x) < lenX) && (this.abs(this.position.y - centerPos.y) < lenY);
    }
    if (isThere) {
        // It is
        // To save perfomance, check if any client's cell collides with this cell
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];
            if (!cell) continue;
            
            var xs = this.position.x - cell.position.x;
            var ys = this.position.y - cell.position.y;
            var sqDist = xs * xs + ys * ys;
            
            var collideDist = cell.getSquareSize() + this.getSquareSize();
            
            if (sqDist < collideDist) {
                return 2;
            }// Colliding with one
        }
        return 1; // Not colliding with any
    }
    else return 0;
};
```

**Comment by NatsuTheGreat** [comment]
Replace ```// It is``` with ```if(gameServer.getMode === "Peace") if (this.cellType == 0) return 1; // <= added```

**Comment by IAP-Reloaded** [comment]
Can you just update that block of code?

**Comment by NatsuTheGreat** [comment]
```
        isThere = (this.abs(this.position.x - centerPos.x) < lenX) && (this.abs(this.position.y - centerPos.y) < lenY);
    }
    if (isThere) {
        if(gameServer.getMode === "Peace") if (this.cellType == 0) return 1; // <= added
        // To save perfomance, check if any client's cell collides with this cell
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];
            if (!cell) continue;

            var xs = this.position.x - cell.position.x;
            var ys = this.position.y - cell.position.y;
            var sqDist = xs * xs + ys * ys;

            var collideDist = cell.getSquareSize() + this.getSquareSize();

            if (sqDist < collideDist) {
                return 2;
            }// Colliding with one
        }
        return 1; // Not colliding with any
    }
    else return 0;
};
```

ffs

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat That seems to break everything.

**Comment by NatsuTheGreat** [comment]
Idk how it broke... Specify please.

**Comment by IAP-Reloaded** [comment]
Errors:

```
ReferenceError: gameServer is not defined
    at Cell.visibleCheck (/Users/Kaminsky/Ogar/src/entity/Cell.js:154:12)
    at PlayerTracker.calcVisibleNodes (/Users/Kaminsky/Ogar/src/PlayerTracker.js:448:26)
    at PlayerTracker.calcViewBox (/Users/Kaminsky/Ogar/src/PlayerTracker.js:379:27)
    at PlayerTracker.<anonymous> (/Users/Kaminsky/Ogar/src/PlayerTracker.js:167:35)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by NatsuTheGreat** [comment]
do:
```
        isThere = (this.abs(this.position.x - centerPos.x) < lenX) && (this.abs(this.position.y - centerPos.y) < lenY);
    }
    if (isThere) {
        if(this.gameServer.getMode === "Peace") if (this.cellType == 0) return 1; // <= added
        // To save perfomance, check if any client's cell collides with this cell
        for (var i = 0; i < cells.length; i++) {
            var cell = cells[i];
            if (!cell) continue;

            var xs = this.position.x - cell.position.x;
            var ys = this.position.y - cell.position.y;
            var sqDist = xs * xs + ys * ys;

            var collideDist = cell.getSquareSize() + this.getSquareSize();

            if (sqDist < collideDist) {
                return 2;
            }// Colliding with one
        }
        return 1; // Not colliding with any
    }
    else return 0;
};
```

**Comment by IAP-Reloaded** [comment]
Here's the new error:

```
/Users/XXX/Ogar/src/PlayerTracker.js:1
(function (exports, require, module, __filename, __dirname) { Ivar Packet = require('./packet');
                                                                   ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/XXX/Ogar/src/GameServer.js:9:21)
    at Module._compile (module.js:541:32)
```

**Comment by NatsuTheGreat** [comment]
Wtf? I don't even know where that came from...

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat It just appears when I start from the original copy and paste it in.

**Comment by NatsuTheGreat** [comment]
Idk then, I don't know what cause that bug, it doesn't specify...

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat Seems to be from here: https://github.com/OgarProject/Ogar/blob/f3e6b419f4990968a5ec6479a94f7112350d1e6b/src/PacketHandler.js

**Comment by NatsuTheGreat** [comment]
We did nothing with PacketHandler...

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat I haven't done anything with it. I'm going to reinstall Ogar but keep Peace.js and index.js for gamemodes, and redo this.

**Comment by IAP-Reloaded** [comment]
Okay, server works until I run around, then I get this:

```
TypeError: Cannot read property 'getMode' of undefined
    at Cell.visibleCheck (/Users/Kaminsky/Ogar/src/entity/Cell.js:154:27)
    at PlayerTracker.calcVisibleNodes (/Users/Kaminsky/Ogar/src/PlayerTracker.js:448:26)
    at PlayerTracker.calcViewBox (/Users/Kaminsky/Ogar/src/PlayerTracker.js:379:27)
    at PlayerTracker.<anonymous> (/Users/Kaminsky/Ogar/src/PlayerTracker.js:167:35)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by NatsuTheGreat** [comment]
Find the place where ```getMode``` function is.

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat, it's at `(this.gameServer.getMode === "Peace")`

**Comment by NatsuTheGreat** [comment]
No, I mean the actual function.

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat 

```
GameServer.prototype.getMode = function() {
	    return this.gameMode;
};
```

**Comment by NatsuTheGreat** [comment]
Dangit, I don't know why it says it can't get the property...

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat Seemed to go away when I used this:

```this.getMode```

instead of this:

```this.gameServer.getMode```

**Comment by NatsuTheGreat** [comment]
alright then.

**Comment by IAP-Reloaded** [comment]
@NatsuTheGreat I can steal eat others

**Comment by NatsuTheGreat** [comment]
idk I give up.

**Comment by IAP-Reloaded** [comment]
Okay, I have successfully made this possible.

Simply used `(this.getMode = 5)`, the gamemode **ID**, not the gamemode **name** (and the code `(this.getMode === "Peace")`

**Comment by NatsuTheGreat** [comment]
kkk.

**Comment by Barbosik** [comment]
it's good, because string comparison is a bad idea for performance

**Comment by IAP-Reloaded** [comment]
@Barbosik That's nice /s

**Comment by XtremePlayzCODE** [comment]
this.getMode() is right, not this.getMode

**Comment by NatsuTheGreat** [comment]
^^ As it's a function.

**Comment by XtremePlayzCODE** [comment]
Thanks natsu

**Comment by NatsuTheGreat** [comment]
:P No problem.

**Comment by XtremePlayzCODE** [comment]
Ps can you make a video on my new private server, my laptop is broke and I'm using CodeHub.


Link here: github.com/XSProject/XtremeServer
Installation is in installation.md

**Comment by IAP-Reloaded** [comment]
@XtremePlayzCODE  no.

**Comment by XtremePlayzCODE** [comment]
i was asking natsu
