### ISSUE TITLE
Server launches but I cannot join (locally)

### ISSUE THREAD

**Issue by TsjipTsjip** [OgarProject/Ogar#606]
When I do playerlist I see myself dead or not playing; I am in the map but cant do anything.
Any help?

**Comment by Megabyte918** [comment]
disable extensions and use play.ogarul.tk

**Comment by TsjipTsjip** [comment]
Somehow this does not work, It asks me to enter an IP where can I find this

**Comment by IAP-Reloaded** [comment]
Did you type in `agar.io/?ip=127.0.0.1`?

**Comment by Megabyte918** [comment]
google your ip and use the port specified in the settings

**Comment by IAP-Reloaded** [comment]
@Megabyte918, this is LOCALLY, so the IP I use is correct.

**Comment by TsjipTsjip** [comment]
Still not working....
I want to join LOCALLY and agar.io/?ip=127.0.0.1:443 does not work

**Comment by TsjipTsjip** [comment]
I will upload my logs and ini file here if that could help
[Gameserver copy.txt](https://github.com/OgarProject/Ogar/files/303221/Gameserver.copy.txt)

**Comment by Megabyte918** [comment]
i dont think agar.io/?ip= works with ogarul anymore, go to play.ogarul.tk and enter 127.0.0.1:443 when it asks you

**Comment by Barbosik** [comment]
FYI: they changed protocol to 8. It's the same as 7, but it also implements additional messages. And they disabled private servers because it encrypts data for private servers again. Hope they will fix it soon

**Comment by TsjipTsjip** [comment]
So currently i cannot use private servers

**Comment by Barbosik** [comment]
why? you can still use a bunch of different clients. 

For example try this one: http://ogar.mivabe.nl/?ip=127.0.0.1:443
Here is master server, so you can find private server: http://ogar.mivabe.nl/master

**Comment by TsjipTsjip** [comment]
I see only time can help me :(

_**-=CLOSED=-**_

**Comment by Barbosik** [comment]
just use any client to connect to your private server

For example use http://ogar.mivabe.nl/?ip=<YOUR SERVER IP>:<YOUR SERVER PORT>
And you can play on your private server.
