### ISSUE TITLE
Can't locate the "Ogar-master" folder

### ISSUE THREAD

**Issue by InfinityRunner** [OgarProject/Ogar#611]
Hello,
My server is working properly when I do `sudo node Ogar`, but I cannot locate the server folder. When I right-click on the folder icon on top of the Terminal, it tells me it's in the Desktop. When I look, there is nothing to be seen. And for your information, my desktop if very clean, and I would have seen it if it was there.

**Comment by ErikParacelsus** [comment]
`cd Ogar-master`

**Comment by InfinityRunner** [comment]
OK thanks! Will try!

**Comment by InfinityRunner** [comment]
This is what it says: `-bash: cd: Ogar-master: No such file or directory`

**Comment by InfinityRunner** [comment]
Actually, nevermind, I just reinstalled it. Now it works. Thanks!
