### ISSUE TITLE
how the Physics are like vanilla 100% ?

### ISSUE THREAD

**Issue by David1ali12** [OgarProject/Ogar#614]
https://www.youtube.com/watch?v=U6fxanugkcA

I saw some youtubers videos using a version of ogar that the Physics are like vanilla 100% 
where can I get that do you have any idea ?
Maybe some ppl have the physics but dont want to share

**Comment by ItzLevvie** [comment]
they're probably using Ogar-unlimited, or Ogar

**Comment by David1ali12** [comment]
nah its not Ogar-unlimited ,the physics of it not that good

**Comment by ItzLevvie** [comment]
or they could be using Ogar, MultiOgar.

**Comment by NatsuTheGreat** [comment]
I have physics very similar to agar.io. You and I can play on my server sometime.

**Comment by David1ali12** [comment]
nvm guys I made physics it better than agario 
@NatsuTheGreat What  is server ip?

**Comment by NatsuTheGreat** [comment]
May I have your skype real quick?

**Comment by David1ali12** [comment]
david12ali9
