### ISSUE TITLE
is there anyway to use Ogarfeeder with my ogar server

### ISSUE THREAD

**Issue by David1ali12** [OgarProject/Ogar#626]
it wont work with bagario , and wont work with agario protocol

**Comment by ItzLevvie** [comment]
Use protocol 5

**Comment by David1ali12** [comment]
user script wont load

**Comment by ItzLevvie** [comment]
It's better to use Agar Powerups instead of agar-feeder-bot

**Comment by David1ali12** [comment]
its freezes with Agarpowerups
