### ISSUE TITLE
Border Source

### ISSUE THREAD

**Issue by Chancerst** [OgarProject/Ogar#641]
This is old border source:
        // Find center
        var width = gameServer.config.borderRight - gameServer.config.borderLeft;
        var height = gameServer.config.borderBottom - gameServer.config.borderTop;
        this.centerPos.x = gameServer.config.borderLeft + width / 2;
        this.centerPos.y = gameServer.config.borderTop + height / 2;
        // Player id
        this.pID = gameServer.getNewPlayerID();
        // Gamemode function
        gameServer.gameMode.onPlayerInit(this);
        // Only scramble if enabled in config
        if (gameServer.config.serverScrambleCoords == 1) {
            // avoid mouse packet limitations
            var maxScrambleX = Math.max(0, 32767 - 2000 - width / 2);
            var maxScrambleY = Math.max(0, 32767 - 2000 - height / 2);
            this.scrambleX = Math.floor(maxScrambleX * Math.random());
            this.scrambleY = Math.floor(maxScrambleY * Math.random());
        }
        this.scrambleId = (Math.random() * 0xFFFFFFFF) >>> 0;

![default](https://cloud.githubusercontent.com/assets/19770308/16679184/7ef3c4e4-4520-11e6-942f-2fbd3a11c7fb.png)
![1](https://cloud.githubusercontent.com/assets/19770308/16679183/7ef0b6d2-4520-11e6-94a4-e38ff372591c.png)

it works agarplus.io and other source correctly.

But now, i think you rewritten border code, so it doesn't work other clients.

can you fix it, please?
I opened 24 hours server, but it is old serverpack.. so it has some bug and lag.

(i think you deleted border top, left, right, bottom, so it doesn't work)

**Comment by ItzLevvie** [comment]
You posted it in the wrong repo.

Make your issue over here: https://github.com/Barbosik/MultiOgar

**Comment by Chancerst** [comment]
@ItzLevvie sorry..
