### ISSUE TITLE
http://ogarproject.com/

### ISSUE THREAD

**Issue by ZfsrGhS953** [OgarProject/Ogar#642]
The website is disabled right now. (not working) Maybe it was disabled because people downloaded from dl.ogarproject.com and the builds were outdated? The developer probably wanted to always deliver the last version.

**Comment by ItzLevvie** [comment]
^^ Not because of that. The domain is expired.

**Comment by SimonOrJ** [comment]
Will the domain name be renewed?

**Comment by Luka967** [comment]
Probably not. It all depends on forairan.
