### ISSUE TITLE
Blank Grid

### ISSUE THREAD

**Issue by iiTehEpicGuy** [OgarProject/Ogar#644]
Hi, When I try connecting to my Ogar server I just get a blank grid and the console spits out a error
`TypeError: Cannot set property 'movePacketTriggered' of undefined
    at PacketHandler.handleMessage (C:\Users\Mason\Desktop\Ogar-master\src\PacketHandler.js:77:40)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.onbinary (C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\WebSocket.js:848:10)
    at C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\Receiver.js:628:18
    at Receiver.applyExtensions (C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\Receiver.js:371:5)
    at C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\Receiver.js:604:14
    at Receiver.flush (C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.opcodes.2.finish (C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\Receiver.js:633:12)
    at Receiver.expectHandler (C:\Users\Mason\Desktop\Ogar-master\node_modules\ws\lib\Receiver.js:589:33)`

**Comment by NatsuTheGreat** [comment]
You are using a pretty old version. ```movePacketTriggered``` was removed LONG ago, Update to the latest version.

**Comment by ApleetServers** [comment]
@NatsuTheGreat I forgot to mention:
This is a fresh install of OgarProject and Node.

**Comment by NatsuTheGreat** [comment]
Well if it was fresh, you wouldn't have ```movePacketTriggered``` :/ You either modified it, or just really don't have the latest version.

**Comment by ApleetServers** [comment]
@NatsuTheGreat All I did modify `GameServer.js` and remove `        // ----- Client authenticity check code -----
        // !!!!! WARNING !!!!!
        // THE BELOW SECTION OF CODE CHECKS TO ENSURE THAT CONNECTIONS ARE COMING
        // FROM THE OFFICIAL AGAR.IO CLIENT. IF YOU REMOVE OR MODIFY THE BELOW
        // SECTION OF CODE TO ALLOW CONNECTIONS FROM A CLIENT ON A DIFFERENT DOMAIN,
        // YOU MAY BE COMMITTING COPYRIGHT INFRINGEMENT AND LEGAL ACTION MAY BE TAKEN
        // AGAINST YOU. THIS SECTION OF CODE WAS ADDED ON JULY 9, 2015 AT THE REQUEST
        // OF THE AGAR.IO DEVELOPERS.
        var origin = ws.upgradeReq.headers.origin;
        if (origin != 'http://agar.io' && origin != 'https://agar.io'
            && origin != 'http://localhost' && origin != 'https://localhost'
            && origin != 'http://127.0.0.1' && origin != 'https://127.0.0.1') {
            ws.close();
            return;
        }`
And if it's really not the latest version where do I download the latest version?

**Comment by NatsuTheGreat** [comment]
https://github.com/OgarProject/Ogar > Clone or Download > Download

**Comment by ApleetServers** [comment]
@NatsuTheGreat Now, I got a blank grid with no error.

**Comment by NatsuTheGreat** [comment]
no modifications?

**Comment by ApleetServers** [comment]
@NatsuTheGreat No modifications.

**Comment by NatsuTheGreat** [comment]
The packets might be causing problems @Luka967

**Comment by ApleetServers** [comment]
@NatsuTheGreat Okay. So just wait for @Luka967 to reply?

**Comment by Luka967** [comment]
Will look immediately. I have a bit deviated server here on cloud9 which sends server version along with some starting adjustments to make users able to connect via any client. There's going to be config unfortunately, due to the client authenticity warning, and will be enabled by default.

**Comment by ApleetServers** [comment]
@Luka967 Ok, thanks!

**Comment by Luka967** [comment]
All nice here, even a fresh install works nicely - can move, split, W... regardless of the error described in the first comment.
@iiTehEpicGuy Check if you get any errors on client side by using `Inspect element` or something similarly named, then go to the `Console` panel and copy any text that looks like an error.
However I noticed that I get some weird errors while giving mass to somebody just recently connected sometimes.

**Comment by Luka967** [comment]
Apparently I started getting it now for no apparent reason. ???

**Comment by iiTehEpicGuy** [comment]
@Luka967 It's really weird. I made a little video of me messing around with OgarServer just to see errors.
https://youtu.be/bg3QahDyGWc

**Comment by ItzLevvie** [comment]
Just remove this: https://github.com/OgarProject/Ogar/blob/master/src/PacketHandler.js#L77

**Comment by iiTehEpicGuy** [comment]
@ItzLevvie You killed it..

**Comment by ItzLevvie** [comment]
Anyways Ogar-unlimited client doesn't work as it uses protocol 4 and the server doesn't support it yet. Also, for ogar.mivabe.nl you'll have to add a early protocol 5 mouse movement packet.

Currently Ogar only supports protocol 8 and protocol 5
