### ISSUE TITLE
Gamemodes Not Working

### ISSUE THREAD

**Issue by tidle** [OgarProject/Ogar#646]
Gamemodes malfunctioning:
2: expirimental (sort of, it gives errors but works)
10: tounament
11: hunger games
12: zombie
13: team z
14: team x

here is the error message for 12:zombie

[error_message_Zombie_example.txt](https://github.com/OgarProject/Ogar/files/374036/error_message_Zombie_example.txt)

all the others are basically the same

**Comment by Luka967** [comment]
Known. They haven't been updated for quite a while, and the files had a lot of edits since last fixes.
Integrating them again would be probably hard.

**Comment by tidle** [comment]
ok I got It thx , Maybe i'll fix them
