### ISSUE TITLE
Session stats

### ISSUE THREAD

**Issue by F0RIS** [OgarProject/Ogar#680]
Who know, does this server collecting these data?

![image](https://cloud.githubusercontent.com/assets/10178982/21153265/62f3f1e6-c172-11e6-8973-a676d510922a.png)

**Comment by Luka967** [comment]
Server doesn't collect match data.

**Comment by F0RIS** [comment]
@Luka967 yes

**Comment by mrmarktyy** [comment]
AFAK , These data wasn't returned from server, It's purely from client side.
