### ISSUE TITLE
Team X not working.

### ISSUE THREAD

**Issue by GhostShot3** [OgarProject/Ogar#682]
![](http://image.prntscr.com/image/87bc824e62d347ff983770c89691a4a9.png)

**Comment by Luka967** [comment]
TeamX is ID 21. I changed most IDs when I implemented plugin support. See `gamemodes/GamemodeList.js` for all IDs.

**Comment by GhostShot3** [comment]
Thx

**Comment by GhostShot3** [comment]
Look  #683

**Comment by GhostShot3** [comment]
I changed the id on gameserver and gave another error.

**Comment by GhostShot3** [comment]
![dssddd](https://cloud.githubusercontent.com/assets/18537420/21374122/8194ce38-c70b-11e6-91ac-c921526b7830.png)

**Comment by Luka967** [comment]
All gamemodes except FFA, Teams, Experimental and Rainbow aren't working.

**Comment by GhostShot3** [comment]
Why ?,Is this going to be fixed?

**Comment by ItzLevvie** [comment]
Team X is an easy fix but not Team Z

**Comment by GhostShot3** [comment]
@ItzLevvie you know how to fix ?

**Comment by ItzLevvie** [comment]
@GhostShot3 Yes, but I'm not on my computer yet.
