### ISSUE TITLE
Can't add players bot

### ISSUE THREAD

**Issue by Flavorounet** [OgarProject/Ogar#687]
Hi,

I already use ogarproject on my private agario server. I read the folowwing sentences in src/ai/README.md:

[Ogar player bots]
These bots are designed to be used for testing new commits of Ogar.
To install this module, set the serverBots config field in gameserver.js to an amount higher than 0 (10 is a good amount),
or issue command addBots [number] in console.

I already try to edit the serverBots config field in gameserver.js and try the command addBots x too, but it didn't work. Can anybody help me to add some bots in my server please ?

Thank's !

**Comment by Luka967** [comment]
It's `addbot` not `addbots`

**Comment by Flavorounet** [comment]
Oh, thank's !
