### ISSUE TITLE
Problem with Client

### ISSUE THREAD

**Issue by Tyskacz** [OgarProject/Ogar#689]
Hey. I have a problem with jumping screen
namely:

see on YouTube
https://www.youtube.com/watch?v=of7wc4SWnfA

**Comment by Agarian** [comment]
That's the scrambling minimap feature bug, disable scrambleMinimaps and it should be fine.

**Comment by Luka967** [comment]
This is a client problem. It's involved with the `SetBorder` packet but I don't know exacly how.
