### ISSUE TITLE
Getting frustrated

### ISSUE THREAD

**Issue by NovaHowl** [OgarProject/Ogar#691]
How the hell do you connect to the server? I've used http://agar.io/?ip=localhost:443 (Yes, I set the port to 446) and connect("ws://localhost:446"). None of them work, so how do I connect to the server?

**Comment by NovaHowl** [comment]
And I can't find ANYTHING on this bloody topic.

**Comment by Luka967** [comment]
The syntax is http://agar.io/?ip=IP:PORT so in your case it would be http://agar.io/?ip=localhost:443. `connect(...)` function was removed a long time ago.

**Comment by NovaHowl** [comment]
Yeah well, it doesn't work. The play button doesn't work.

**Comment by NovaHowl** [comment]
And when I go to the console it doesn't say anything about an IP connected which I know it used to do when someone connected.

**Comment by NovaHowl** [comment]
Just started working... WTF?

**Comment by NovaHowl** [comment]
Most of the time it doesn't work, but it works other times.
