### ISSUE TITLE
Play Button

### ISSUE THREAD

**Issue by NovaHowl** [OgarProject/Ogar#692]
Rarely it works but when It doesn't it clicks but it doesn't load me into the game, but I can spectate, also a lot of commands are broken.

**Comment by Luka967** [comment]
This project is really outdated and unstable. Use MultiOgar-Edited, do simple search on github for the repo.

**Comment by ItzLevvie** [comment]
@NovaHowl (https://github.com/Megabyte918/MultiOgar-Edited)[MultiOgar-Edited]

**Comment by NovaHowl** [comment]
Thanks!
