### ISSUE TITLE
Team mode leaderboard not working

### ISSUE THREAD

**Issue by P3il3** [OgarProject/Ogar#704]
https://snag.gy/1CIVoK.jpg
FFA leaderboard is fine.
Edit: Forgot to say, adblock was disabled

**Comment by Agarian** [comment]
Let me just say that adblock has nothing to do with that.

**Comment by Fan7asy** [comment]
@P3il3 The leaderboard has been broken for a while.

**Comment by Agarian** [comment]
And likely will stay broken here, as @vram4 has abandoned the project, and no longer accepts Pull Requests

**Comment by P3il3** [comment]
That's sad... I'm gonna close this then

**Comment by Agarian** [comment]
Your welcome to try https://github.com/Megabyte918/MultiOgar-Edited/

**Comment by P3il3** [comment]
Okay I will try that.

**Comment by Agarian** [comment]
Might I add that the physics are much better there, in my opinion.
