### ISSUE TITLE
Ejected mass goes through cell

### ISSUE THREAD

**Issue by maixuanhan** [OgarProject/Ogar#73]
I notice that with the standard configuration. I shoot the virus when I am too closed to it, the ejected mass just goes through the virus (Actually, Mother cell in Experiment mode). Same issue when I feed my teammate, especially if he is small.

Another issue, is below code missed update? (`this.angle = 1 - this.angle;`)
```javascript
Cell.prototype.calcMovePhys = function(config) {
...
    if ((this.position.x + radius) > config.borderRight) {
        // Flip angle horizontally - Right side
        this.angle = 1 - this.angle;
        X = config.borderRight - radius;
    }
...
};
```

**Comment by ryush00** [comment]
I also have a problem.

**Comment by Porama6400** [comment]
me too

**Comment by z3ntu** [comment]
Is this problem still present?

**Comment by DaFudgeWizzad** [comment]
Yes, I have it too

**Comment by DaFudgeWizzad** [comment]
Temporary solution: Change the ejectSpeed to a lower value

**Comment by Ciao121** [comment]
DaFudgeWizzadm what speed are you using to fix?

**Comment by DaFudgeWizzad** [comment]
@ Ciao121 about 90

**Comment by NatsuTheGreat** [comment]
Your ejected mass shouldn't go through green viruses, (or atleast it has never happened to me).

If you want your mothercells to stop that, do the following:

You have this in Experimental.js:

    // Config
    this.motherCellMass = 200;
    this.motherUpdateInterval = 5; // How many ticks it takes to update the mother cell (1 tick = 50 ms)
    this.motherSpawnInterval = 100; // How many ticks it takes to spawn another mother cell - Currently 5 seconds
    this.motherMinAmount = 20;
}

Simply change 

    this.motherUpdateInterval = 5; // How many ticks it takes to update the mother cell (1 tick = 50 ms)

to a lower value like 1. 

If it still does pass the ejectedmass through, contact me.

**Comment by NatsuTheGreat** [comment]
I sadly do not now how to fix that with players.. Hopefully the Ogar developers would know.

**Comment by DaFudgeWizzad** [comment]
I may have a solution, as I have found out how to create dynamic moving nodes. I did this on http://abs0rb.me with the split, I will test it with the ejected mass.

**Comment by Luka967** [comment]
@vram4 Close?
