### ISSUE TITLE
process out of memory?

### ISSUE THREAD

**Issue by joery1337** [OgarProject/Ogar#98]
Hey,

After like 12 hours I get this error..
`FATAL ERROR: Evacuation Allocation failed - process out of memory`

![free -m](http://scrsha.re/XR0b.png)

After this commit by the way https://github.com/forairan/Ogar/commit/c904c096245ff1e6310d13e72c697678282d60bb

Oh this commit brings the memory leak also back.

**Comment by listenyoumusic** [comment]
Yes, apparently returned memory loss

**Comment by joery1337** [comment]
This commit (https://github.com/forairan/Ogar/commit/6ebfceaa157cace04c08712ce2effb2b0a6c7c41) also made it worse.

**Comment by z3ntu** [comment]
Request update or close!
